// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAccountIdentity = `-- name: DeleteAccountIdentity :exec
DELETE FROM account_identity WHERE id = $1 AND account_id = $2
`

type DeleteAccountIdentityParams struct {
	ID        int64 `json:"id"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) DeleteAccountIdentity(ctx context.Context, arg DeleteAccountIdentityParams) error {
	_, err := q.db.Exec(ctx, deleteAccountIdentity, arg.ID, arg.AccountID)
	return err
}

const getAccountIdentityByIssuerSub = `-- name: GetAccountIdentityByIssuerSub :one
SELECT id, account_id, upstream_idp_id, upstream_iss, upstream_sub, upstream_email, linked_at FROM account_identity WHERE upstream_iss = $1 AND upstream_sub = $2
`

type GetAccountIdentityByIssuerSubParams struct {
	UpstreamIss string `json:"upstreamIss"`
	UpstreamSub string `json:"upstreamSub"`
}

func (q *Queries) GetAccountIdentityByIssuerSub(ctx context.Context, arg GetAccountIdentityByIssuerSubParams) (AccountIdentity, error) {
	row := q.db.QueryRow(ctx, getAccountIdentityByIssuerSub, arg.UpstreamIss, arg.UpstreamSub)
	var i AccountIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UpstreamIdpID,
		&i.UpstreamIss,
		&i.UpstreamSub,
		&i.UpstreamEmail,
		&i.LinkedAt,
	)
	return i, err
}

const insertAccountIdentity = `-- name: InsertAccountIdentity :one
INSERT INTO account_identity (account_id, upstream_idp_id, upstream_iss, upstream_sub, upstream_email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, upstream_idp_id, upstream_iss, upstream_sub, upstream_email, linked_at
`

type InsertAccountIdentityParams struct {
	AccountID     int32       `json:"accountId"`
	UpstreamIdpID int64       `json:"upstreamIdpId"`
	UpstreamIss   string      `json:"upstreamIss"`
	UpstreamSub   string      `json:"upstreamSub"`
	UpstreamEmail pgtype.Text `json:"upstreamEmail"`
}

func (q *Queries) InsertAccountIdentity(ctx context.Context, arg InsertAccountIdentityParams) (AccountIdentity, error) {
	row := q.db.QueryRow(ctx, insertAccountIdentity,
		arg.AccountID,
		arg.UpstreamIdpID,
		arg.UpstreamIss,
		arg.UpstreamSub,
		arg.UpstreamEmail,
	)
	var i AccountIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UpstreamIdpID,
		&i.UpstreamIss,
		&i.UpstreamSub,
		&i.UpstreamEmail,
		&i.LinkedAt,
	)
	return i, err
}

const listAccountIdentitiesByAccount = `-- name: ListAccountIdentitiesByAccount :many
SELECT ai.id, ai.account_id, ai.upstream_idp_id, ai.upstream_iss, ai.upstream_sub, ai.upstream_email, ai.linked_at, ip.slug AS idp_slug, ip.display_name AS idp_display_name
FROM account_identity ai
JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
WHERE ai.account_id = $1
`

type ListAccountIdentitiesByAccountRow struct {
	ID             int64              `json:"id"`
	AccountID      int32              `json:"accountId"`
	UpstreamIdpID  int64              `json:"upstreamIdpId"`
	UpstreamIss    string             `json:"upstreamIss"`
	UpstreamSub    string             `json:"upstreamSub"`
	UpstreamEmail  pgtype.Text        `json:"upstreamEmail"`
	LinkedAt       pgtype.Timestamptz `json:"linkedAt"`
	IdpSlug        string             `json:"idpSlug"`
	IdpDisplayName string             `json:"idpDisplayName"`
}

func (q *Queries) ListAccountIdentitiesByAccount(ctx context.Context, accountID int32) ([]ListAccountIdentitiesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listAccountIdentitiesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountIdentitiesByAccountRow
	for rows.Next() {
		var i ListAccountIdentitiesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.UpstreamIdpID,
			&i.UpstreamIss,
			&i.UpstreamSub,
			&i.UpstreamEmail,
			&i.LinkedAt,
			&i.IdpSlug,
			&i.IdpDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
