// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearActiveAvatar = `-- name: ClearActiveAvatar :exec
UPDATE account SET avatar_source = $1::text, avatar_etag = NULL, avatar_content_type = NULL, updated_at = now()
WHERE id = $2
`

type ClearActiveAvatarParams struct {
	Source    string `json:"source"`
	AccountID int32  `json:"accountId"`
}

func (q *Queries) ClearActiveAvatar(ctx context.Context, arg ClearActiveAvatarParams) error {
	_, err := q.db.Exec(ctx, clearActiveAvatar, arg.Source, arg.AccountID)
	return err
}

const countActiveAdminsForUpdate = `-- name: CountActiveAdminsForUpdate :one
SELECT COUNT(*) FROM account WHERE role = 'admin' AND NOT disabled FOR UPDATE
`

func (q *Queries) CountActiveAdminsForUpdate(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminsForUpdate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccountByID = `-- name: DeleteAccountByID :exec
DELETE FROM account WHERE id = $1
`

func (q *Queries) DeleteAccountByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAccountByID, id)
	return err
}

const deleteAvatarSource = `-- name: DeleteAvatarSource :exec
DELETE FROM account_avatar WHERE account_id = $1 AND source = $2
`

type DeleteAvatarSourceParams struct {
	AccountID int32  `json:"accountId"`
	Source    string `json:"source"`
}

func (q *Queries) DeleteAvatarSource(ctx context.Context, arg DeleteAvatarSourceParams) error {
	_, err := q.db.Exec(ctx, deleteAvatarSource, arg.AccountID, arg.Source)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, display_name, webauthn_user_handle, oidc_subject, role, attributes, disabled, created_at, updated_at, email, email_verified, avatar_content_type, avatar_etag, avatar_source FROM account WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.OidcSubject,
		&i.Role,
		&i.Attributes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSource,
	)
	return i, err
}

const getAccountByIDForUpdate = `-- name: GetAccountByIDForUpdate :one
SELECT id, username, display_name, webauthn_user_handle, oidc_subject, role, attributes, disabled, created_at, updated_at, email, email_verified, avatar_content_type, avatar_etag, avatar_source FROM account WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccountByIDForUpdate(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIDForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.OidcSubject,
		&i.Role,
		&i.Attributes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSource,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, display_name, webauthn_user_handle, oidc_subject, role, attributes, disabled, created_at, updated_at, email, email_verified, avatar_content_type, avatar_etag, avatar_source FROM account WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.OidcSubject,
		&i.Role,
		&i.Attributes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSource,
	)
	return i, err
}

const getAccountByWebauthnUserHandle = `-- name: GetAccountByWebauthnUserHandle :one
SELECT id, username, display_name, webauthn_user_handle, oidc_subject, role, attributes, disabled, created_at, updated_at, email, email_verified, avatar_content_type, avatar_etag, avatar_source FROM account WHERE webauthn_user_handle = $1
`

func (q *Queries) GetAccountByWebauthnUserHandle(ctx context.Context, webauthnUserHandle []byte) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByWebauthnUserHandle, webauthnUserHandle)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.OidcSubject,
		&i.Role,
		&i.Attributes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSource,
	)
	return i, err
}

const getActiveAvatarBySubject = `-- name: GetActiveAvatarBySubject :one
SELECT av.bytes, av.content_type, av.etag, a.disabled
FROM account a JOIN account_avatar av ON av.account_id = a.id AND av.source = a.avatar_source
WHERE a.oidc_subject = $1
`

type GetActiveAvatarBySubjectRow struct {
	Bytes       []byte      `json:"bytes"`
	ContentType pgtype.Text `json:"contentType"`
	Etag        pgtype.Text `json:"etag"`
	Disabled    bool        `json:"disabled"`
}

func (q *Queries) GetActiveAvatarBySubject(ctx context.Context, oidcSubject pgtype.UUID) (GetActiveAvatarBySubjectRow, error) {
	row := q.db.QueryRow(ctx, getActiveAvatarBySubject, oidcSubject)
	var i GetActiveAvatarBySubjectRow
	err := row.Scan(
		&i.Bytes,
		&i.ContentType,
		&i.Etag,
		&i.Disabled,
	)
	return i, err
}

const getAvatarSourceBySubject = `-- name: GetAvatarSourceBySubject :one
SELECT av.bytes, av.content_type, av.etag, a.disabled
FROM account a JOIN account_avatar av ON av.account_id = a.id
WHERE a.oidc_subject = $1 AND av.source = $2
`

type GetAvatarSourceBySubjectParams struct {
	OidcSubject pgtype.UUID `json:"oidcSubject"`
	Source      string      `json:"source"`
}

type GetAvatarSourceBySubjectRow struct {
	Bytes       []byte      `json:"bytes"`
	ContentType pgtype.Text `json:"contentType"`
	Etag        pgtype.Text `json:"etag"`
	Disabled    bool        `json:"disabled"`
}

func (q *Queries) GetAvatarSourceBySubject(ctx context.Context, arg GetAvatarSourceBySubjectParams) (GetAvatarSourceBySubjectRow, error) {
	row := q.db.QueryRow(ctx, getAvatarSourceBySubject, arg.OidcSubject, arg.Source)
	var i GetAvatarSourceBySubjectRow
	err := row.Scan(
		&i.Bytes,
		&i.ContentType,
		&i.Etag,
		&i.Disabled,
	)
	return i, err
}

const hasAnyActiveAdmin = `-- name: HasAnyActiveAdmin :one
SELECT EXISTS(SELECT 1 FROM account WHERE role = 'admin' AND NOT disabled) AS has_admin
`

func (q *Queries) HasAnyActiveAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyActiveAdmin)
	var has_admin bool
	err := row.Scan(&has_admin)
	return has_admin, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO account (
  username, display_name, webauthn_user_handle, role, attributes, disabled, email, email_verified
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, display_name, webauthn_user_handle, oidc_subject, role, attributes, disabled, created_at, updated_at, email, email_verified, avatar_content_type, avatar_etag, avatar_source
`

type InsertAccountParams struct {
	Username           string      `json:"username"`
	DisplayName        string      `json:"displayName"`
	WebauthnUserHandle []byte      `json:"webauthnUserHandle"`
	Role               string      `json:"role"`
	Attributes         []byte      `json:"attributes"`
	Disabled           bool        `json:"disabled"`
	Email              pgtype.Text `json:"email"`
	EmailVerified      bool        `json:"emailVerified"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.Username,
		arg.DisplayName,
		arg.WebauthnUserHandle,
		arg.Role,
		arg.Attributes,
		arg.Disabled,
		arg.Email,
		arg.EmailVerified,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.OidcSubject,
		&i.Role,
		&i.Attributes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSource,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
  a.id, a.username, a.display_name, a.webauthn_user_handle, a.oidc_subject, a.role, a.attributes, a.disabled, a.created_at, a.updated_at, a.email, a.email_verified, a.avatar_content_type, a.avatar_etag, a.avatar_source,
  (SELECT MAX(c.last_used_at) FROM webauthn_credential c WHERE c.account_id = a.id)::timestamptz AS last_sign_in_at,
  COALESCE((
    SELECT jsonb_agg(
      jsonb_build_object(
        'id', ai.id,
        'providerSlug', ip.slug,
        'providerDisplayName', ip.display_name,
        'protocol', ip.protocol,
        'subject', ai.upstream_sub,
        'email', ai.upstream_email,
        'data', ai.upstream_data,
        'linkedAt', ai.linked_at
      )
      ORDER BY ai.linked_at DESC, ai.id DESC
    )
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    CROSS JOIN LATERAL (
      SELECT CASE $1::text
        WHEN 'subject' THEN ai.upstream_sub
        WHEN 'email' THEN COALESCE(ai.upstream_email, '')
        WHEN 'steamId' THEN ai.upstream_sub
        WHEN 'personaName' THEN COALESCE(ai.upstream_data->>'personaName', '')
        WHEN 'userId' THEN ai.upstream_sub
        WHEN 'displayName' THEN COALESCE(ai.upstream_data->>'displayName', '')
        ELSE ''
      END AS field_value
    ) selected
    WHERE ai.account_id = a.id
      AND (
        (
          $2::text IS NOT NULL
          AND (
            (
              ai.upstream_sub || E'\n' ||
              COALESCE(ai.upstream_email, '') || E'\n' ||
              COALESCE(ai.upstream_data->>'personaName', '') || E'\n' ||
              COALESCE(ai.upstream_data->>'displayName', '') || E'\n' ||
              COALESCE(ai.upstream_data->>'profileUrl', '')
            ) ILIKE '%' || $2::text || '%'
          )
        )
        OR (
          $3::text IS NOT NULL
          AND ip.slug = $3::text
          AND (
            $1::text IS NULL
            OR CASE
              WHEN $4::text = 'exact'
                AND $1::text IN ('personaName', 'displayName')
                THEN ai.upstream_data @> jsonb_build_object(
                  $1::text,
                  to_jsonb($5::text)
                )
              WHEN $4::text = 'exact'
                THEN lower(selected.field_value) = lower($5::text)
              WHEN $4::text = 'prefix'
                THEN lower(selected.field_value) LIKE lower($5::text) || '%'
              WHEN $4::text = 'contains'
                THEN lower(selected.field_value) LIKE '%' || lower($5::text) || '%'
              ELSE false
            END
          )
        )
      )
  ), '[]'::jsonb)::text AS matching_identities
FROM account a
WHERE (
    $2::text IS NULL
    OR a.id IN (
      SELECT searched.id
      FROM account searched
      WHERE (
        searched.username || E'\n' ||
        searched.display_name || E'\n' ||
        COALESCE(searched.email, '')
      ) ILIKE '%' || $2::text || '%'
      UNION
      SELECT ai.account_id
      FROM account_identity ai
      WHERE (
        ai.upstream_sub || E'\n' ||
        COALESCE(ai.upstream_email, '') || E'\n' ||
        COALESCE(ai.upstream_data->>'personaName', '') || E'\n' ||
        COALESCE(ai.upstream_data->>'displayName', '') || E'\n' ||
        COALESCE(ai.upstream_data->>'profileUrl', '')
      ) ILIKE '%' || $2::text || '%'
    )
  )
  AND (
    $3::text IS NULL
    OR EXISTS (
      SELECT 1
      FROM account_identity ai
      JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
      CROSS JOIN LATERAL (
        SELECT CASE $1::text
          WHEN 'subject' THEN ai.upstream_sub
          WHEN 'email' THEN COALESCE(ai.upstream_email, '')
          WHEN 'steamId' THEN ai.upstream_sub
          WHEN 'personaName' THEN COALESCE(ai.upstream_data->>'personaName', '')
          WHEN 'userId' THEN ai.upstream_sub
          WHEN 'displayName' THEN COALESCE(ai.upstream_data->>'displayName', '')
          ELSE ''
        END AS field_value
      ) selected
      WHERE ai.account_id = a.id
        AND ip.slug = $3::text
        AND (
          $1::text IS NULL
          OR CASE
            WHEN $4::text = 'exact'
              AND $1::text IN ('personaName', 'displayName')
              THEN ai.upstream_data @> jsonb_build_object(
                $1::text,
                to_jsonb($5::text)
              )
            WHEN $4::text = 'exact'
              THEN lower(selected.field_value) = lower($5::text)
            WHEN $4::text = 'prefix'
              THEN lower(selected.field_value) LIKE lower($5::text) || '%'
            WHEN $4::text = 'contains'
              THEN lower(selected.field_value) LIKE '%' || lower($5::text) || '%'
            ELSE false
          END
        )
    )
  )
  AND (
    $6::timestamptz IS NULL
    OR (a.created_at, a.id) < ($6, $7::int4)
  )
ORDER BY a.created_at DESC, a.id DESC
LIMIT $8
`

type ListAccountsParams struct {
	Field          pgtype.Text        `json:"field"`
	Q              pgtype.Text        `json:"q"`
	Provider       pgtype.Text        `json:"provider"`
	Match          pgtype.Text        `json:"match"`
	Value          pgtype.Text        `json:"value"`
	AfterCreatedAt pgtype.Timestamptz `json:"afterCreatedAt"`
	AfterID        pgtype.Int4        `json:"afterId"`
	Limit          int32              `json:"limit"`
}

type ListAccountsRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"displayName"`
	WebauthnUserHandle []byte             `json:"webauthnUserHandle"`
	OidcSubject        pgtype.UUID        `json:"oidcSubject"`
	Role               string             `json:"role"`
	Attributes         []byte             `json:"attributes"`
	Disabled           bool               `json:"disabled"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	Email              pgtype.Text        `json:"email"`
	EmailVerified      bool               `json:"emailVerified"`
	AvatarContentType  pgtype.Text        `json:"avatarContentType"`
	AvatarEtag         pgtype.Text        `json:"avatarEtag"`
	AvatarSource       pgtype.Text        `json:"avatarSource"`
	LastSignInAt       pgtype.Timestamptz `json:"lastSignInAt"`
	MatchingIdentities string             `json:"matchingIdentities"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.Field,
		arg.Q,
		arg.Provider,
		arg.Match,
		arg.Value,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.WebauthnUserHandle,
			&i.OidcSubject,
			&i.Role,
			&i.Attributes,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.EmailVerified,
			&i.AvatarContentType,
			&i.AvatarEtag,
			&i.AvatarSource,
			&i.LastSignInAt,
			&i.MatchingIdentities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvatarSourcesByAccount = `-- name: ListAvatarSourcesByAccount :many
SELECT av.source, av.etag, COALESCE(i.display_name, '') AS idp_display_name
FROM account_avatar av
LEFT JOIN upstream_idp i ON i.id = av.idp_id
WHERE av.account_id = $1
`

type ListAvatarSourcesByAccountRow struct {
	Source         string      `json:"source"`
	Etag           pgtype.Text `json:"etag"`
	IdpDisplayName string      `json:"idpDisplayName"`
}

// LEFT JOIN so the 'user' row (NULL idp_id) is kept with an empty label; the
// join is by id (unconditional) so even a disabled upstream's inherited avatar
// still resolves its display name.
func (q *Queries) ListAvatarSourcesByAccount(ctx context.Context, accountID int32) ([]ListAvatarSourcesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listAvatarSourcesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvatarSourcesByAccountRow
	for rows.Next() {
		var i ListAvatarSourcesByAccountRow
		if err := rows.Scan(&i.Source, &i.Etag, &i.IdpDisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountDisabled = `-- name: SetAccountDisabled :one
UPDATE account SET disabled = $2, updated_at = now() WHERE id = $1 RETURNING id, username, display_name, webauthn_user_handle, oidc_subject, role, attributes, disabled, created_at, updated_at, email, email_verified, avatar_content_type, avatar_etag, avatar_source
`

type SetAccountDisabledParams struct {
	ID       int32 `json:"id"`
	Disabled bool  `json:"disabled"`
}

func (q *Queries) SetAccountDisabled(ctx context.Context, arg SetAccountDisabledParams) (Account, error) {
	row := q.db.QueryRow(ctx, setAccountDisabled, arg.ID, arg.Disabled)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.OidcSubject,
		&i.Role,
		&i.Attributes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSource,
	)
	return i, err
}

const setActiveAvatar = `-- name: SetActiveAvatar :exec
UPDATE account SET
  avatar_source       = $1::text,
  avatar_etag         = (SELECT etag         FROM account_avatar av WHERE av.account_id = $2 AND av.source = $1),
  avatar_content_type = (SELECT content_type FROM account_avatar av WHERE av.account_id = $2 AND av.source = $1),
  updated_at = now()
WHERE id = $2
`

type SetActiveAvatarParams struct {
	Source    string `json:"source"`
	AccountID int32  `json:"accountId"`
}

// source is forced non-null text (the column is nullable, but this query only
// ever sets a concrete sentinel) so callers cannot accidentally NULL the pointer.
func (q *Queries) SetActiveAvatar(ctx context.Context, arg SetActiveAvatarParams) error {
	_, err := q.db.Exec(ctx, setActiveAvatar, arg.Source, arg.AccountID)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account SET
  display_name = $2, role = $3, attributes = $4, disabled = $5,
  email = $6, email_verified = $7,
  updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, webauthn_user_handle, oidc_subject, role, attributes, disabled, created_at, updated_at, email, email_verified, avatar_content_type, avatar_etag, avatar_source
`

type UpdateAccountParams struct {
	ID            int32       `json:"id"`
	DisplayName   string      `json:"displayName"`
	Role          string      `json:"role"`
	Attributes    []byte      `json:"attributes"`
	Disabled      bool        `json:"disabled"`
	Email         pgtype.Text `json:"email"`
	EmailVerified bool        `json:"emailVerified"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.DisplayName,
		arg.Role,
		arg.Attributes,
		arg.Disabled,
		arg.Email,
		arg.EmailVerified,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.OidcSubject,
		&i.Role,
		&i.Attributes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerified,
		&i.AvatarContentType,
		&i.AvatarEtag,
		&i.AvatarSource,
	)
	return i, err
}

const updateAccountDisplayName = `-- name: UpdateAccountDisplayName :exec
UPDATE account SET display_name = $2, updated_at = now() WHERE id = $1
`

type UpdateAccountDisplayNameParams struct {
	ID          int32  `json:"id"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateAccountDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateAccountEmail = `-- name: UpdateAccountEmail :exec
UPDATE account SET email = $2, email_verified = $3, updated_at = now() WHERE id = $1
`

type UpdateAccountEmailParams struct {
	ID            int32       `json:"id"`
	Email         pgtype.Text `json:"email"`
	EmailVerified bool        `json:"emailVerified"`
}

// Refreshes an account's email from a verified upstream on re-login (federation
// claim drift), keeping it in lockstep with account_identity.upstream_email.
func (q *Queries) UpdateAccountEmail(ctx context.Context, arg UpdateAccountEmailParams) error {
	_, err := q.db.Exec(ctx, updateAccountEmail, arg.ID, arg.Email, arg.EmailVerified)
	return err
}

const upsertAvatarSource = `-- name: UpsertAvatarSource :exec
INSERT INTO account_avatar (account_id, source, bytes, content_type, etag, idp_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_id, source) DO UPDATE
  SET bytes = EXCLUDED.bytes, content_type = EXCLUDED.content_type, etag = EXCLUDED.etag, idp_id = EXCLUDED.idp_id
`

type UpsertAvatarSourceParams struct {
	AccountID   int32       `json:"accountId"`
	Source      string      `json:"source"`
	Bytes       []byte      `json:"bytes"`
	ContentType pgtype.Text `json:"contentType"`
	Etag        pgtype.Text `json:"etag"`
	IdpID       *int64      `json:"idpId"`
}

// idp_id records the source upstream for an inherited avatar (NULL for a user
// upload); source carries the upstream slug ("upstream:<slug>") so the
// (account_id, source) PK yields one row per (account, upstream).
func (q *Queries) UpsertAvatarSource(ctx context.Context, arg UpsertAvatarSourceParams) error {
	_, err := q.db.Exec(ctx, upsertAvatarSource,
		arg.AccountID,
		arg.Source,
		arg.Bytes,
		arg.ContentType,
		arg.Etag,
		arg.IdpID,
	)
	return err
}
