// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_throttle.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthThrottle = `-- name: GetAuthThrottle :one
SELECT account_id, factor, failed_attempts, window_start, locked_until FROM auth_throttle WHERE account_id = $1 AND factor = $2
`

type GetAuthThrottleParams struct {
	AccountID int32  `json:"accountId"`
	Factor    string `json:"factor"`
}

func (q *Queries) GetAuthThrottle(ctx context.Context, arg GetAuthThrottleParams) (AuthThrottle, error) {
	row := q.db.QueryRow(ctx, getAuthThrottle, arg.AccountID, arg.Factor)
	var i AuthThrottle
	err := row.Scan(
		&i.AccountID,
		&i.Factor,
		&i.FailedAttempts,
		&i.WindowStart,
		&i.LockedUntil,
	)
	return i, err
}

const resetAuthThrottle = `-- name: ResetAuthThrottle :exec
DELETE FROM auth_throttle WHERE account_id = $1 AND factor = $2
`

type ResetAuthThrottleParams struct {
	AccountID int32  `json:"accountId"`
	Factor    string `json:"factor"`
}

func (q *Queries) ResetAuthThrottle(ctx context.Context, arg ResetAuthThrottleParams) error {
	_, err := q.db.Exec(ctx, resetAuthThrottle, arg.AccountID, arg.Factor)
	return err
}

const upsertAuthThrottle = `-- name: UpsertAuthThrottle :one
INSERT INTO auth_throttle (account_id, factor, failed_attempts, window_start, locked_until)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, factor) DO UPDATE
SET failed_attempts = EXCLUDED.failed_attempts,
    window_start = EXCLUDED.window_start,
    locked_until = EXCLUDED.locked_until
RETURNING account_id, factor, failed_attempts, window_start, locked_until
`

type UpsertAuthThrottleParams struct {
	AccountID      int32              `json:"accountId"`
	Factor         string             `json:"factor"`
	FailedAttempts int32              `json:"failedAttempts"`
	WindowStart    pgtype.Timestamptz `json:"windowStart"`
	LockedUntil    pgtype.Timestamptz `json:"lockedUntil"`
}

func (q *Queries) UpsertAuthThrottle(ctx context.Context, arg UpsertAuthThrottleParams) (AuthThrottle, error) {
	row := q.db.QueryRow(ctx, upsertAuthThrottle,
		arg.AccountID,
		arg.Factor,
		arg.FailedAttempts,
		arg.WindowStart,
		arg.LockedUntil,
	)
	var i AuthThrottle
	err := row.Scan(
		&i.AccountID,
		&i.Factor,
		&i.FailedAttempts,
		&i.WindowStart,
		&i.LockedUntil,
	)
	return i, err
}
