// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential_event.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCredentialEvent = `-- name: InsertCredentialEvent :exec
INSERT INTO credential_event (account_id, factor, event, credential_ref, ip, user_agent, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertCredentialEventParams struct {
	AccountID     *int32      `json:"accountId"`
	Factor        string      `json:"factor"`
	Event         string      `json:"event"`
	CredentialRef pgtype.Int8 `json:"credentialRef"`
	Ip            *netip.Addr `json:"ip"`
	UserAgent     pgtype.Text `json:"userAgent"`
	Detail        []byte      `json:"detail"`
}

func (q *Queries) InsertCredentialEvent(ctx context.Context, arg InsertCredentialEventParams) error {
	_, err := q.db.Exec(ctx, insertCredentialEvent,
		arg.AccountID,
		arg.Factor,
		arg.Event,
		arg.CredentialRef,
		arg.Ip,
		arg.UserAgent,
		arg.Detail,
	)
	return err
}

const listCredentialEventsByAccount = `-- name: ListCredentialEventsByAccount :many
SELECT id, account_id, factor, event, credential_ref, ip, user_agent, detail, at FROM credential_event
WHERE account_id = $1
ORDER BY at DESC
LIMIT $2 OFFSET $3
`

type ListCredentialEventsByAccountParams struct {
	AccountID *int32 `json:"accountId"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListCredentialEventsByAccount(ctx context.Context, arg ListCredentialEventsByAccountParams) ([]CredentialEvent, error) {
	rows, err := q.db.Query(ctx, listCredentialEventsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialEvent
	for rows.Next() {
		var i CredentialEvent
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Factor,
			&i.Event,
			&i.CredentialRef,
			&i.Ip,
			&i.UserAgent,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialEventsByFactor = `-- name: ListCredentialEventsByFactor :many
SELECT id, account_id, factor, event, credential_ref, ip, user_agent, detail, at FROM credential_event
WHERE factor = $1 AND at > $2
ORDER BY at DESC
LIMIT $3
`

type ListCredentialEventsByFactorParams struct {
	Factor string             `json:"factor"`
	At     pgtype.Timestamptz `json:"at"`
	Limit  int32              `json:"limit"`
}

func (q *Queries) ListCredentialEventsByFactor(ctx context.Context, arg ListCredentialEventsByFactorParams) ([]CredentialEvent, error) {
	rows, err := q.db.Query(ctx, listCredentialEventsByFactor, arg.Factor, arg.At, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialEvent
	for rows.Next() {
		var i CredentialEvent
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Factor,
			&i.Event,
			&i.CredentialRef,
			&i.Ip,
			&i.UserAgent,
			&i.Detail,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
