// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diagnostic_event.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredDiagnosticEvents = `-- name: DeleteExpiredDiagnosticEvents :execrows
DELETE FROM diagnostic_event WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredDiagnosticEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDiagnosticEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDiagnosticEvent = `-- name: GetDiagnosticEvent :one
SELECT request_id, occurred_at, expires_at, account_id, method, route, operation, code, retryable, fields FROM diagnostic_event
WHERE request_id = $1 AND expires_at > now()
`

// Exact-ID lookup. Filters on expires_at > now() so expired rows are
// invisible (return no rows → 404) even before the prune reaper deletes them.
func (q *Queries) GetDiagnosticEvent(ctx context.Context, requestID string) (DiagnosticEvent, error) {
	row := q.db.QueryRow(ctx, getDiagnosticEvent, requestID)
	var i DiagnosticEvent
	err := row.Scan(
		&i.RequestID,
		&i.OccurredAt,
		&i.ExpiresAt,
		&i.AccountID,
		&i.Method,
		&i.Route,
		&i.Operation,
		&i.Code,
		&i.Retryable,
		&i.Fields,
	)
	return i, err
}

const insertDiagnosticEvent = `-- name: InsertDiagnosticEvent :exec
INSERT INTO diagnostic_event (request_id, occurred_at, expires_at, account_id, method, route, operation, code, retryable, fields)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (request_id) DO NOTHING
`

type InsertDiagnosticEventParams struct {
	RequestID  string             `json:"requestId"`
	OccurredAt pgtype.Timestamptz `json:"occurredAt"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	AccountID  *int32             `json:"accountId"`
	Method     string             `json:"method"`
	Route      string             `json:"route"`
	Operation  string             `json:"operation"`
	Code       string             `json:"code"`
	Retryable  bool               `json:"retryable"`
	Fields     []byte             `json:"fields"`
}

func (q *Queries) InsertDiagnosticEvent(ctx context.Context, arg InsertDiagnosticEventParams) error {
	_, err := q.db.Exec(ctx, insertDiagnosticEvent,
		arg.RequestID,
		arg.OccurredAt,
		arg.ExpiresAt,
		arg.AccountID,
		arg.Method,
		arg.Route,
		arg.Operation,
		arg.Code,
		arg.Retryable,
		arg.Fields,
	)
	return err
}
