// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEnrollment = `-- name: ConsumeEnrollment :one
UPDATE enrollment
SET consumed_at = now()
WHERE token = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING token, intent, target_account_id, template_username, template_display_name, template_role, template_attributes, expected_upstream_idp_slug, created_at, expires_at, consumed_at, federated_upstream_idp_id, federated_upstream_idp_slug, federated_upstream_iss, federated_upstream_sub, federated_display_name, federated_upstream_data, federated_avatar_url, recovery_source_upstream_idp_id
`

// Atomic single-use consume. Returns the row only if it was unconsumed and unexpired.
// Callers detect any "not consumable" branch via pgx.ErrNoRows.
func (q *Queries) ConsumeEnrollment(ctx context.Context, token string) (Enrollment, error) {
	row := q.db.QueryRow(ctx, consumeEnrollment, token)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.TemplateUsername,
		&i.TemplateDisplayName,
		&i.TemplateRole,
		&i.TemplateAttributes,
		&i.ExpectedUpstreamIdpSlug,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FederatedUpstreamIdpID,
		&i.FederatedUpstreamIdpSlug,
		&i.FederatedUpstreamIss,
		&i.FederatedUpstreamSub,
		&i.FederatedDisplayName,
		&i.FederatedUpstreamData,
		&i.FederatedAvatarUrl,
		&i.RecoverySourceUpstreamIdpID,
	)
	return i, err
}

const consumeInviteEnrollment = `-- name: ConsumeInviteEnrollment :one
UPDATE enrollment
SET consumed_at = now()
WHERE token = $1 AND intent = 'invite' AND consumed_at IS NULL AND expires_at > now()
RETURNING token, intent, target_account_id, template_username, template_display_name, template_role, template_attributes, expected_upstream_idp_slug, created_at, expires_at, consumed_at, federated_upstream_idp_id, federated_upstream_idp_slug, federated_upstream_iss, federated_upstream_sub, federated_display_name, federated_upstream_data, federated_avatar_url, recovery_source_upstream_idp_id
`

// Atomic single-use consume, intent-restricted to 'invite' AND unexpired. Used
// by the federation invite-redemption path (applyInviteOnly) so a bootstrap or
// reset token can never be marked consumed via the federation callback —
// defense-in-depth on top of the begin-time intent gate (audit OIDCFED-2).
// pgx.ErrNoRows surfaces on any not-consumable branch.
func (q *Queries) ConsumeInviteEnrollment(ctx context.Context, token string) (Enrollment, error) {
	row := q.db.QueryRow(ctx, consumeInviteEnrollment, token)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.TemplateUsername,
		&i.TemplateDisplayName,
		&i.TemplateRole,
		&i.TemplateAttributes,
		&i.ExpectedUpstreamIdpSlug,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FederatedUpstreamIdpID,
		&i.FederatedUpstreamIdpSlug,
		&i.FederatedUpstreamIss,
		&i.FederatedUpstreamSub,
		&i.FederatedDisplayName,
		&i.FederatedUpstreamData,
		&i.FederatedAvatarUrl,
		&i.RecoverySourceUpstreamIdpID,
	)
	return i, err
}

const getEnrollmentByToken = `-- name: GetEnrollmentByToken :one
SELECT token, intent, target_account_id, template_username, template_display_name, template_role, template_attributes, expected_upstream_idp_slug, created_at, expires_at, consumed_at, federated_upstream_idp_id, federated_upstream_idp_slug, federated_upstream_iss, federated_upstream_sub, federated_display_name, federated_upstream_data, federated_avatar_url, recovery_source_upstream_idp_id FROM enrollment WHERE token = $1
`

func (q *Queries) GetEnrollmentByToken(ctx context.Context, token string) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByToken, token)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.TemplateUsername,
		&i.TemplateDisplayName,
		&i.TemplateRole,
		&i.TemplateAttributes,
		&i.ExpectedUpstreamIdpSlug,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FederatedUpstreamIdpID,
		&i.FederatedUpstreamIdpSlug,
		&i.FederatedUpstreamIss,
		&i.FederatedUpstreamSub,
		&i.FederatedDisplayName,
		&i.FederatedUpstreamData,
		&i.FederatedAvatarUrl,
		&i.RecoverySourceUpstreamIdpID,
	)
	return i, err
}

const insertEnrollment = `-- name: InsertEnrollment :one
INSERT INTO enrollment (
  token, intent, target_account_id, expires_at,
  template_role, template_attributes, expected_upstream_idp_slug,
  template_username, template_display_name
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING token, intent, target_account_id, template_username, template_display_name, template_role, template_attributes, expected_upstream_idp_slug, created_at, expires_at, consumed_at, federated_upstream_idp_id, federated_upstream_idp_slug, federated_upstream_iss, federated_upstream_sub, federated_display_name, federated_upstream_data, federated_avatar_url, recovery_source_upstream_idp_id
`

type InsertEnrollmentParams struct {
	Token                   string             `json:"token"`
	Intent                  string             `json:"intent"`
	TargetAccountID         pgtype.Int4        `json:"targetAccountId"`
	ExpiresAt               pgtype.Timestamptz `json:"expiresAt"`
	TemplateRole            pgtype.Text        `json:"templateRole"`
	TemplateAttributes      []byte             `json:"templateAttributes"`
	ExpectedUpstreamIdpSlug pgtype.Text        `json:"expectedUpstreamIdpSlug"`
	TemplateUsername        pgtype.Text        `json:"templateUsername"`
	TemplateDisplayName     pgtype.Text        `json:"templateDisplayName"`
}

func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, insertEnrollment,
		arg.Token,
		arg.Intent,
		arg.TargetAccountID,
		arg.ExpiresAt,
		arg.TemplateRole,
		arg.TemplateAttributes,
		arg.ExpectedUpstreamIdpSlug,
		arg.TemplateUsername,
		arg.TemplateDisplayName,
	)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.TemplateUsername,
		&i.TemplateDisplayName,
		&i.TemplateRole,
		&i.TemplateAttributes,
		&i.ExpectedUpstreamIdpSlug,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FederatedUpstreamIdpID,
		&i.FederatedUpstreamIdpSlug,
		&i.FederatedUpstreamIss,
		&i.FederatedUpstreamSub,
		&i.FederatedDisplayName,
		&i.FederatedUpstreamData,
		&i.FederatedAvatarUrl,
		&i.RecoverySourceUpstreamIdpID,
	)
	return i, err
}

const insertFederatedRegistrationEnrollment = `-- name: InsertFederatedRegistrationEnrollment :one
INSERT INTO enrollment (
  token, intent, expires_at,
  federated_upstream_idp_id, federated_upstream_idp_slug,
  federated_upstream_iss, federated_upstream_sub,
  federated_display_name, federated_upstream_data, federated_avatar_url
)
VALUES (
  $1, 'federated_register', $2,
  $3, $4,
  $5, $6,
  $7, $8,
  $9
)
RETURNING token, intent, target_account_id, template_username, template_display_name, template_role, template_attributes, expected_upstream_idp_slug, created_at, expires_at, consumed_at, federated_upstream_idp_id, federated_upstream_idp_slug, federated_upstream_iss, federated_upstream_sub, federated_display_name, federated_upstream_data, federated_avatar_url, recovery_source_upstream_idp_id
`

type InsertFederatedRegistrationEnrollmentParams struct {
	Token                    string             `json:"token"`
	ExpiresAt                pgtype.Timestamptz `json:"expiresAt"`
	FederatedUpstreamIdpID   pgtype.Int8        `json:"federatedUpstreamIdpId"`
	FederatedUpstreamIdpSlug pgtype.Text        `json:"federatedUpstreamIdpSlug"`
	FederatedUpstreamIss     pgtype.Text        `json:"federatedUpstreamIss"`
	FederatedUpstreamSub     pgtype.Text        `json:"federatedUpstreamSub"`
	FederatedDisplayName     pgtype.Text        `json:"federatedDisplayName"`
	FederatedUpstreamData    []byte             `json:"federatedUpstreamData"`
	FederatedAvatarUrl       pgtype.Text        `json:"federatedAvatarUrl"`
}

func (q *Queries) InsertFederatedRegistrationEnrollment(ctx context.Context, arg InsertFederatedRegistrationEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, insertFederatedRegistrationEnrollment,
		arg.Token,
		arg.ExpiresAt,
		arg.FederatedUpstreamIdpID,
		arg.FederatedUpstreamIdpSlug,
		arg.FederatedUpstreamIss,
		arg.FederatedUpstreamSub,
		arg.FederatedDisplayName,
		arg.FederatedUpstreamData,
		arg.FederatedAvatarUrl,
	)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.TemplateUsername,
		&i.TemplateDisplayName,
		&i.TemplateRole,
		&i.TemplateAttributes,
		&i.ExpectedUpstreamIdpSlug,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FederatedUpstreamIdpID,
		&i.FederatedUpstreamIdpSlug,
		&i.FederatedUpstreamIss,
		&i.FederatedUpstreamSub,
		&i.FederatedDisplayName,
		&i.FederatedUpstreamData,
		&i.FederatedAvatarUrl,
		&i.RecoverySourceUpstreamIdpID,
	)
	return i, err
}

const insertProviderRecoveryEnrollment = `-- name: InsertProviderRecoveryEnrollment :one
INSERT INTO enrollment (
  token, intent, target_account_id, expires_at, recovery_source_upstream_idp_id
)
VALUES (
  $1, 'reset', $2,
  $3, $4
)
RETURNING token, intent, target_account_id, template_username, template_display_name, template_role, template_attributes, expected_upstream_idp_slug, created_at, expires_at, consumed_at, federated_upstream_idp_id, federated_upstream_idp_slug, federated_upstream_iss, federated_upstream_sub, federated_display_name, federated_upstream_data, federated_avatar_url, recovery_source_upstream_idp_id
`

type InsertProviderRecoveryEnrollmentParams struct {
	Token                       string             `json:"token"`
	TargetAccountID             pgtype.Int4        `json:"targetAccountId"`
	ExpiresAt                   pgtype.Timestamptz `json:"expiresAt"`
	RecoverySourceUpstreamIdpID pgtype.Int8        `json:"recoverySourceUpstreamIdpId"`
}

func (q *Queries) InsertProviderRecoveryEnrollment(ctx context.Context, arg InsertProviderRecoveryEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, insertProviderRecoveryEnrollment,
		arg.Token,
		arg.TargetAccountID,
		arg.ExpiresAt,
		arg.RecoverySourceUpstreamIdpID,
	)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.TemplateUsername,
		&i.TemplateDisplayName,
		&i.TemplateRole,
		&i.TemplateAttributes,
		&i.ExpectedUpstreamIdpSlug,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FederatedUpstreamIdpID,
		&i.FederatedUpstreamIdpSlug,
		&i.FederatedUpstreamIss,
		&i.FederatedUpstreamSub,
		&i.FederatedDisplayName,
		&i.FederatedUpstreamData,
		&i.FederatedAvatarUrl,
		&i.RecoverySourceUpstreamIdpID,
	)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT token, intent, target_account_id, template_username, template_display_name, template_role, template_attributes, expected_upstream_idp_slug, created_at, expires_at, consumed_at, federated_upstream_idp_id, federated_upstream_idp_slug, federated_upstream_iss, federated_upstream_sub, federated_display_name, federated_upstream_data, federated_avatar_url, recovery_source_upstream_idp_id FROM enrollment
WHERE intent = 'invite'
  AND consumed_at IS NULL
  AND expires_at > now()
  AND ($1::timestamptz IS NULL OR (created_at, token) < ($1, $2::text))
ORDER BY created_at DESC, token DESC
LIMIT $3
`

type ListPendingInvitationsParams struct {
	AfterCreatedAt pgtype.Timestamptz `json:"afterCreatedAt"`
	AfterToken     pgtype.Text        `json:"afterToken"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListPendingInvitations(ctx context.Context, arg ListPendingInvitationsParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations, arg.AfterCreatedAt, arg.AfterToken, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enrollment
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.Token,
			&i.Intent,
			&i.TargetAccountID,
			&i.TemplateUsername,
			&i.TemplateDisplayName,
			&i.TemplateRole,
			&i.TemplateAttributes,
			&i.ExpectedUpstreamIdpSlug,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.FederatedUpstreamIdpID,
			&i.FederatedUpstreamIdpSlug,
			&i.FederatedUpstreamIss,
			&i.FederatedUpstreamSub,
			&i.FederatedDisplayName,
			&i.FederatedUpstreamData,
			&i.FederatedAvatarUrl,
			&i.RecoverySourceUpstreamIdpID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE enrollment
SET consumed_at = now()
WHERE token = $1 AND intent = 'invite' AND consumed_at IS NULL
RETURNING token, intent, target_account_id, template_username, template_display_name, template_role, template_attributes, expected_upstream_idp_slug, created_at, expires_at, consumed_at, federated_upstream_idp_id, federated_upstream_idp_slug, federated_upstream_iss, federated_upstream_sub, federated_display_name, federated_upstream_data, federated_avatar_url, recovery_source_upstream_idp_id
`

// Same DB effect as ConsumeEnrollment but intent-restricted to 'invite' so an
// admin cannot accidentally use this to mark a bootstrap/reset token consumed.
// Returns the row only if it was unconsumed AND of intent=invite; otherwise
// pgx.ErrNoRows surfaces and the handler maps to invitation_not_found.
func (q *Queries) RevokeInvitation(ctx context.Context, token string) (Enrollment, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, token)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.TemplateUsername,
		&i.TemplateDisplayName,
		&i.TemplateRole,
		&i.TemplateAttributes,
		&i.ExpectedUpstreamIdpSlug,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FederatedUpstreamIdpID,
		&i.FederatedUpstreamIdpSlug,
		&i.FederatedUpstreamIss,
		&i.FederatedUpstreamSub,
		&i.FederatedDisplayName,
		&i.FederatedUpstreamData,
		&i.FederatedAvatarUrl,
		&i.RecoverySourceUpstreamIdpID,
	)
	return i, err
}
