// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entity_icon.sql

package db

import (
	"context"
)

const deleteEntityIcon = `-- name: DeleteEntityIcon :exec
DELETE FROM entity_icon WHERE owner_kind = $1 AND owner_id = $2
`

type DeleteEntityIconParams struct {
	OwnerKind string `json:"ownerKind"`
	OwnerID   string `json:"ownerId"`
}

func (q *Queries) DeleteEntityIcon(ctx context.Context, arg DeleteEntityIconParams) error {
	_, err := q.db.Exec(ctx, deleteEntityIcon, arg.OwnerKind, arg.OwnerID)
	return err
}

const getEntityIcon = `-- name: GetEntityIcon :one
SELECT png, etag FROM entity_icon WHERE owner_kind = $1 AND owner_id = $2
`

type GetEntityIconParams struct {
	OwnerKind string `json:"ownerKind"`
	OwnerID   string `json:"ownerId"`
}

type GetEntityIconRow struct {
	Png  []byte `json:"png"`
	Etag string `json:"etag"`
}

func (q *Queries) GetEntityIcon(ctx context.Context, arg GetEntityIconParams) (GetEntityIconRow, error) {
	row := q.db.QueryRow(ctx, getEntityIcon, arg.OwnerKind, arg.OwnerID)
	var i GetEntityIconRow
	err := row.Scan(&i.Png, &i.Etag)
	return i, err
}

const getEntityIconEtag = `-- name: GetEntityIconEtag :one
SELECT etag FROM entity_icon WHERE owner_kind = $1 AND owner_id = $2
`

type GetEntityIconEtagParams struct {
	OwnerKind string `json:"ownerKind"`
	OwnerID   string `json:"ownerId"`
}

func (q *Queries) GetEntityIconEtag(ctx context.Context, arg GetEntityIconEtagParams) (string, error) {
	row := q.db.QueryRow(ctx, getEntityIconEtag, arg.OwnerKind, arg.OwnerID)
	var etag string
	err := row.Scan(&etag)
	return etag, err
}

const listEntityIconEtags = `-- name: ListEntityIconEtags :many
SELECT owner_id, etag FROM entity_icon WHERE owner_kind = $1
`

type ListEntityIconEtagsRow struct {
	OwnerID string `json:"ownerId"`
	Etag    string `json:"etag"`
}

func (q *Queries) ListEntityIconEtags(ctx context.Context, ownerKind string) ([]ListEntityIconEtagsRow, error) {
	rows, err := q.db.Query(ctx, listEntityIconEtags, ownerKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntityIconEtagsRow
	for rows.Next() {
		var i ListEntityIconEtagsRow
		if err := rows.Scan(&i.OwnerID, &i.Etag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEntityIcon = `-- name: SetEntityIcon :exec
INSERT INTO entity_icon (owner_kind, owner_id, png, etag, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (owner_kind, owner_id)
DO UPDATE SET png = $3, etag = $4, updated_at = now()
`

type SetEntityIconParams struct {
	OwnerKind string `json:"ownerKind"`
	OwnerID   string `json:"ownerId"`
	Png       []byte `json:"png"`
	Etag      string `json:"etag"`
}

func (q *Queries) SetEntityIcon(ctx context.Context, arg SetEntityIconParams) error {
	_, err := q.db.Exec(ctx, setEntityIcon,
		arg.OwnerKind,
		arg.OwnerID,
		arg.Png,
		arg.Etag,
	)
	return err
}
