// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_appearance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUnsplashKey = `-- name: ClearUnsplashKey :exec
UPDATE instance_settings
SET unsplash_key_enc = NULL, unsplash_key_nonce = NULL, unsplash_key_version = NULL, updated_at = now()
WHERE id = 1
`

func (q *Queries) ClearUnsplashKey(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearUnsplashKey)
	return err
}

const countLoginBackgroundImages = `-- name: CountLoginBackgroundImages :one
SELECT count(*) FROM login_background_image
`

func (q *Queries) CountLoginBackgroundImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginBackgroundImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLoginBackgroundImage = `-- name: DeleteLoginBackgroundImage :execrows
DELETE FROM login_background_image WHERE id = $1
`

func (q *Queries) DeleteLoginBackgroundImage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLoginBackgroundImage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLoginAppearance = `-- name: GetLoginAppearance :one
SELECT login_appearance, unsplash_key_enc, unsplash_key_nonce, unsplash_key_version
FROM instance_settings WHERE id = 1
`

type GetLoginAppearanceRow struct {
	LoginAppearance    []byte      `json:"loginAppearance"`
	UnsplashKeyEnc     []byte      `json:"unsplashKeyEnc"`
	UnsplashKeyNonce   []byte      `json:"unsplashKeyNonce"`
	UnsplashKeyVersion pgtype.Int4 `json:"unsplashKeyVersion"`
}

func (q *Queries) GetLoginAppearance(ctx context.Context) (GetLoginAppearanceRow, error) {
	row := q.db.QueryRow(ctx, getLoginAppearance)
	var i GetLoginAppearanceRow
	err := row.Scan(
		&i.LoginAppearance,
		&i.UnsplashKeyEnc,
		&i.UnsplashKeyNonce,
		&i.UnsplashKeyVersion,
	)
	return i, err
}

const getLoginBackgroundImage = `-- name: GetLoginBackgroundImage :one
SELECT data, etag FROM login_background_image WHERE id = $1
`

type GetLoginBackgroundImageRow struct {
	Data []byte `json:"data"`
	Etag string `json:"etag"`
}

func (q *Queries) GetLoginBackgroundImage(ctx context.Context, id int64) (GetLoginBackgroundImageRow, error) {
	row := q.db.QueryRow(ctx, getLoginBackgroundImage, id)
	var i GetLoginBackgroundImageRow
	err := row.Scan(&i.Data, &i.Etag)
	return i, err
}

const insertLoginBackgroundImage = `-- name: InsertLoginBackgroundImage :one
INSERT INTO login_background_image (data, etag) VALUES ($1, $2) RETURNING id
`

type InsertLoginBackgroundImageParams struct {
	Data []byte `json:"data"`
	Etag string `json:"etag"`
}

func (q *Queries) InsertLoginBackgroundImage(ctx context.Context, arg InsertLoginBackgroundImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLoginBackgroundImage, arg.Data, arg.Etag)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLoginBackgroundImages = `-- name: ListLoginBackgroundImages :many
SELECT id, etag FROM login_background_image ORDER BY id
`

type ListLoginBackgroundImagesRow struct {
	ID   int64  `json:"id"`
	Etag string `json:"etag"`
}

func (q *Queries) ListLoginBackgroundImages(ctx context.Context) ([]ListLoginBackgroundImagesRow, error) {
	rows, err := q.db.Query(ctx, listLoginBackgroundImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoginBackgroundImagesRow
	for rows.Next() {
		var i ListLoginBackgroundImagesRow
		if err := rows.Scan(&i.ID, &i.Etag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInstanceSettings = `-- name: LockInstanceSettings :one
SELECT id FROM instance_settings WHERE id = 1 FOR UPDATE
`

func (q *Queries) LockInstanceSettings(ctx context.Context) (int16, error) {
	row := q.db.QueryRow(ctx, lockInstanceSettings)
	var id int16
	err := row.Scan(&id)
	return id, err
}

const setLoginAppearance = `-- name: SetLoginAppearance :exec
UPDATE instance_settings SET login_appearance = $1, updated_at = now() WHERE id = 1
`

func (q *Queries) SetLoginAppearance(ctx context.Context, loginAppearance []byte) error {
	_, err := q.db.Exec(ctx, setLoginAppearance, loginAppearance)
	return err
}

const setUnsplashKey = `-- name: SetUnsplashKey :exec
UPDATE instance_settings
SET unsplash_key_enc = $1, unsplash_key_nonce = $2, unsplash_key_version = $3, updated_at = now()
WHERE id = 1
`

type SetUnsplashKeyParams struct {
	UnsplashKeyEnc     []byte      `json:"unsplashKeyEnc"`
	UnsplashKeyNonce   []byte      `json:"unsplashKeyNonce"`
	UnsplashKeyVersion pgtype.Int4 `json:"unsplashKeyVersion"`
}

func (q *Queries) SetUnsplashKey(ctx context.Context, arg SetUnsplashKeyParams) error {
	_, err := q.db.Exec(ctx, setUnsplashKey, arg.UnsplashKeyEnc, arg.UnsplashKeyNonce, arg.UnsplashKeyVersion)
	return err
}
