// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"displayName"`
	WebauthnUserHandle []byte             `json:"webauthnUserHandle"`
	OidcSubject        pgtype.UUID        `json:"oidcSubject"`
	Role               string             `json:"role"`
	Attributes         []byte             `json:"attributes"`
	Disabled           bool               `json:"disabled"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	Email              pgtype.Text        `json:"email"`
	EmailVerified      bool               `json:"emailVerified"`
	AvatarContentType  pgtype.Text        `json:"avatarContentType"`
	AvatarEtag         pgtype.Text        `json:"avatarEtag"`
	AvatarSource       pgtype.Text        `json:"avatarSource"`
}

type AccountAvatar struct {
	AccountID   int32       `json:"accountId"`
	Bytes       []byte      `json:"bytes"`
	Source      string      `json:"source"`
	ContentType pgtype.Text `json:"contentType"`
	Etag        pgtype.Text `json:"etag"`
}

type AccountIdentity struct {
	ID            int64              `json:"id"`
	AccountID     int32              `json:"accountId"`
	UpstreamIdpID int64              `json:"upstreamIdpId"`
	UpstreamIss   string             `json:"upstreamIss"`
	UpstreamSub   string             `json:"upstreamSub"`
	UpstreamEmail pgtype.Text        `json:"upstreamEmail"`
	LinkedAt      pgtype.Timestamptz `json:"linkedAt"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmedAt"`
}

type AuthThrottle struct {
	AccountID      int32              `json:"accountId"`
	Factor         string             `json:"factor"`
	FailedAttempts int32              `json:"failedAttempts"`
	WindowStart    pgtype.Timestamptz `json:"windowStart"`
	LockedUntil    pgtype.Timestamptz `json:"lockedUntil"`
}

type CredentialEvent struct {
	ID            int64              `json:"id"`
	AccountID     *int32             `json:"accountId"`
	Factor        string             `json:"factor"`
	Event         string             `json:"event"`
	CredentialRef pgtype.Int8        `json:"credentialRef"`
	Ip            *netip.Addr        `json:"ip"`
	UserAgent     pgtype.Text        `json:"userAgent"`
	Detail        []byte             `json:"detail"`
	At            pgtype.Timestamptz `json:"at"`
}

type Enrollment struct {
	Token                   string             `json:"token"`
	Intent                  string             `json:"intent"`
	TargetAccountID         pgtype.Int4        `json:"targetAccountId"`
	TemplateUsername        pgtype.Text        `json:"templateUsername"`
	TemplateDisplayName     pgtype.Text        `json:"templateDisplayName"`
	TemplateRole            pgtype.Text        `json:"templateRole"`
	TemplateAttributes      []byte             `json:"templateAttributes"`
	ExpectedUpstreamIdpSlug pgtype.Text        `json:"expectedUpstreamIdpSlug"`
	CreatedAt               pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt               pgtype.Timestamptz `json:"expiresAt"`
	ConsumedAt              pgtype.Timestamptz `json:"consumedAt"`
}

type OidcClient struct {
	ClientID                    string             `json:"clientId"`
	DisplayName                 string             `json:"displayName"`
	ClientSecretHash            pgtype.Text        `json:"clientSecretHash"`
	RedirectUris                []string           `json:"redirectUris"`
	PostLogoutRedirectUris      []string           `json:"postLogoutRedirectUris"`
	AllowedScopes               []string           `json:"allowedScopes"`
	RequirePkce                 bool               `json:"requirePkce"`
	AllowedCodeChallengeMethods []string           `json:"allowedCodeChallengeMethods"`
	TokenEndpointAuthMethod     string             `json:"tokenEndpointAuthMethod"`
	SubjectType                 string             `json:"subjectType"`
	LogoUri                     pgtype.Text        `json:"logoUri"`
	TosUri                      pgtype.Text        `json:"tosUri"`
	PolicyUri                   pgtype.Text        `json:"policyUri"`
	Disabled                    bool               `json:"disabled"`
	RequireConsent              bool               `json:"requireConsent"`
	CreatedAt                   pgtype.Timestamptz `json:"createdAt"`
}

type OidcConsent struct {
	AccountID     int32              `json:"accountId"`
	ClientID      string             `json:"clientId"`
	GrantedScopes []string           `json:"grantedScopes"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type PasswordCredential struct {
	AccountID         int32              `json:"accountId"`
	Hash              string             `json:"hash"`
	PasswordChangedAt pgtype.Timestamptz `json:"passwordChangedAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type RecoveryCode struct {
	ID            int32              `json:"id"`
	AccountID     int32              `json:"accountId"`
	Hash          string             `json:"hash"`
	UsedAt        pgtype.Timestamptz `json:"usedAt"`
	UsedSessionID pgtype.Text        `json:"usedSessionId"`
	UsedIp        *netip.Addr        `json:"usedIp"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type RevokedJti struct {
	Jti       string             `json:"jti"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	Reason    pgtype.Text        `json:"reason"`
	RevokedAt pgtype.Timestamptz `json:"revokedAt"`
}

type SamlSession struct {
	ID           int64              `json:"id"`
	SessionID    string             `json:"sessionId"`
	SpID         int64              `json:"spId"`
	NameID       string             `json:"nameId"`
	SessionIndex string             `json:"sessionIndex"`
	NotOnOrAfter pgtype.Timestamptz `json:"notOnOrAfter"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type SamlSp struct {
	ID                        int64              `json:"id"`
	EntityID                  string             `json:"entityId"`
	DisplayName               string             `json:"displayName"`
	SpKind                    pgtype.Text        `json:"spKind"`
	NameIDFormat              string             `json:"nameIdFormat"`
	AttributeMap              []byte             `json:"attributeMap"`
	RequireSignedAuthnRequest bool               `json:"requireSignedAuthnRequest"`
	AllowIdpInitiated         bool               `json:"allowIdpInitiated"`
	SessionLifetime           pgtype.Interval    `json:"sessionLifetime"`
	MetadataXml               pgtype.Text        `json:"metadataXml"`
	MetadataValidUntil        pgtype.Timestamptz `json:"metadataValidUntil"`
	MetadataCacheDuration     pgtype.Interval    `json:"metadataCacheDuration"`
	MetadataFetchedAt         pgtype.Timestamptz `json:"metadataFetchedAt"`
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
}

type SamlSpAc struct {
	SpID      int64  `json:"spId"`
	Idx       int32  `json:"idx"`
	Binding   string `json:"binding"`
	Location  string `json:"location"`
	IsDefault bool   `json:"isDefault"`
}

type SamlSpKey struct {
	ID       int64              `json:"id"`
	SpID     int64              `json:"spId"`
	Use      string             `json:"use"`
	CertPem  string             `json:"certPem"`
	NotAfter pgtype.Timestamptz `json:"notAfter"`
	AddedAt  pgtype.Timestamptz `json:"addedAt"`
}

type SamlSubjectID struct {
	AccountID    int32              `json:"accountId"`
	SpID         int64              `json:"spId"`
	NameID       string             `json:"nameId"`
	NameIDFormat string             `json:"nameIdFormat"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type Session struct {
	ID            string             `json:"id"`
	AccountID     int32              `json:"accountId"`
	AuthTime      pgtype.Timestamptz `json:"authTime"`
	Amr           []string           `json:"amr"`
	Acr           pgtype.Text        `json:"acr"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	RevokedAt     pgtype.Timestamptz `json:"revokedAt"`
	UpstreamIdpID *int64             `json:"upstreamIdpId"`
}

type SigningKey struct {
	Kid              string             `json:"kid"`
	Algorithm        string             `json:"algorithm"`
	Use              string             `json:"use"`
	PublicJwk        []byte             `json:"publicJwk"`
	X509CertPem      pgtype.Text        `json:"x509CertPem"`
	PrivatePemEnc    []byte             `json:"privatePemEnc"`
	PrivatePemNonce  []byte             `json:"privatePemNonce"`
	KeyVersion       int32              `json:"keyVersion"`
	Status           string             `json:"status"`
	ActivatedAt      pgtype.Timestamptz `json:"activatedAt"`
	DecommissionedAt pgtype.Timestamptz `json:"decommissionedAt"`
	RetireAfter      pgtype.Timestamptz `json:"retireAfter"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type TotpCredential struct {
	AccountID   int32              `json:"accountId"`
	SecretEnc   []byte             `json:"secretEnc"`
	SecretNonce []byte             `json:"secretNonce"`
	KeyVersion  int32              `json:"keyVersion"`
	Period      int32              `json:"period"`
	Digits      int32              `json:"digits"`
	Algorithm   string             `json:"algorithm"`
	LastStep    int64              `json:"lastStep"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmedAt"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type UpstreamIdp struct {
	ID                   int64              `json:"id"`
	Slug                 string             `json:"slug"`
	DisplayName          string             `json:"displayName"`
	IssuerUrl            string             `json:"issuerUrl"`
	ClientID             string             `json:"clientId"`
	ClientSecretEnc      []byte             `json:"clientSecretEnc"`
	SecretNonce          []byte             `json:"secretNonce"`
	KeyVersion           int32              `json:"keyVersion"`
	Scopes               []string           `json:"scopes"`
	Mode                 string             `json:"mode"`
	AllowedDomains       []string           `json:"allowedDomains"`
	UsernameClaim        string             `json:"usernameClaim"`
	DisplayNameClaim     string             `json:"displayNameClaim"`
	EmailClaim           string             `json:"emailClaim"`
	Disabled             bool               `json:"disabled"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
	RequireVerifiedEmail bool               `json:"requireVerifiedEmail"`
	PictureClaim         string             `json:"pictureClaim"`
}

type WebauthnCredential struct {
	ID              int32              `json:"id"`
	AccountID       int32              `json:"accountId"`
	CredentialID    []byte             `json:"credentialId"`
	PublicKey       []byte             `json:"publicKey"`
	CoseAlg         int32              `json:"coseAlg"`
	UserHandle      []byte             `json:"userHandle"`
	SignCount       int64              `json:"signCount"`
	Transports      []string           `json:"transports"`
	Aaguid          []byte             `json:"aaguid"`
	AttestationType pgtype.Text        `json:"attestationType"`
	BackupEligible  pgtype.Bool        `json:"backupEligible"`
	BackupState     pgtype.Bool        `json:"backupState"`
	UvInitialized   bool               `json:"uvInitialized"`
	Nickname        pgtype.Text        `json:"nickname"`
	LastUsedAt      pgtype.Timestamptz `json:"lastUsedAt"`
	CloneWarningAt  pgtype.Timestamptz `json:"cloneWarningAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}
