// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   int32              `json:"id"`
	Username             string             `json:"username"`
	DisplayName          string             `json:"displayName"`
	WebauthnUserHandle   []byte             `json:"webauthnUserHandle"`
	Role                 string             `json:"role"`
	CanViewOwnUsage      bool               `json:"canViewOwnUsage"`
	CanManageOwnApiKeys  bool               `json:"canManageOwnApiKeys"`
	CanViewModels        bool               `json:"canViewModels"`
	CanViewOwnTraces     bool               `json:"canViewOwnTraces"`
	CanManageOwnProjects bool               `json:"canManageOwnProjects"`
	Disabled             bool               `json:"disabled"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt            pgtype.Timestamptz `json:"updatedAt"`
}

type Enrollment struct {
	Token                        string             `json:"token"`
	Intent                       string             `json:"intent"`
	TargetAccountID              pgtype.Int4        `json:"targetAccountId"`
	TemplateRole                 pgtype.Text        `json:"templateRole"`
	TemplateCanViewOwnUsage      pgtype.Bool        `json:"templateCanViewOwnUsage"`
	TemplateCanManageOwnApiKeys  pgtype.Bool        `json:"templateCanManageOwnApiKeys"`
	TemplateCanViewModels        pgtype.Bool        `json:"templateCanViewModels"`
	TemplateCanViewOwnTraces     pgtype.Bool        `json:"templateCanViewOwnTraces"`
	TemplateCanManageOwnProjects pgtype.Bool        `json:"templateCanManageOwnProjects"`
	TemplateUsername             pgtype.Text        `json:"templateUsername"`
	TemplateDisplayName          pgtype.Text        `json:"templateDisplayName"`
	CreatedAt                    pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt                    pgtype.Timestamptz `json:"expiresAt"`
	ConsumedAt                   pgtype.Timestamptz `json:"consumedAt"`
}

type OidcClient struct {
	ClientID         string             `json:"clientId"`
	ClientSecretHash pgtype.Text        `json:"clientSecretHash"`
	DisplayName      string             `json:"displayName"`
	RedirectUris     []string           `json:"redirectUris"`
	AllowedScopes    []string           `json:"allowedScopes"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type OidcSigningKey struct {
	Kid        string             `json:"kid"`
	Algorithm  string             `json:"algorithm"`
	PublicJwk  []byte             `json:"publicJwk"`
	PrivatePem []byte             `json:"privatePem"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	RetiredAt  pgtype.Timestamptz `json:"retiredAt"`
}

type WebauthnCredential struct {
	ID              int32              `json:"id"`
	AccountID       int32              `json:"accountId"`
	CredentialID    []byte             `json:"credentialId"`
	PublicKey       []byte             `json:"publicKey"`
	SignCount       int64              `json:"signCount"`
	Transports      []string           `json:"transports"`
	Aaguid          []byte             `json:"aaguid"`
	AttestationType string             `json:"attestationType"`
	BackupEligible  bool               `json:"backupEligible"`
	BackupState     bool               `json:"backupState"`
	Nickname        pgtype.Text        `json:"nickname"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	LastUsedAt      pgtype.Timestamptz `json:"lastUsedAt"`
}
