// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_consent.sql

package db

import (
	"context"
)

const deleteConsent = `-- name: DeleteConsent :exec
DELETE FROM oidc_consent WHERE account_id = $1 AND client_id = $2
`

type DeleteConsentParams struct {
	AccountID int32  `json:"accountId"`
	ClientID  string `json:"clientId"`
}

func (q *Queries) DeleteConsent(ctx context.Context, arg DeleteConsentParams) error {
	_, err := q.db.Exec(ctx, deleteConsent, arg.AccountID, arg.ClientID)
	return err
}

const getConsent = `-- name: GetConsent :one
SELECT granted_scopes FROM oidc_consent
WHERE account_id = $1 AND client_id = $2
`

type GetConsentParams struct {
	AccountID int32  `json:"accountId"`
	ClientID  string `json:"clientId"`
}

func (q *Queries) GetConsent(ctx context.Context, arg GetConsentParams) ([]string, error) {
	row := q.db.QueryRow(ctx, getConsent, arg.AccountID, arg.ClientID)
	var granted_scopes []string
	err := row.Scan(&granted_scopes)
	return granted_scopes, err
}

const upsertConsent = `-- name: UpsertConsent :exec
INSERT INTO oidc_consent (account_id, client_id, granted_scopes, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (account_id, client_id)
DO UPDATE SET granted_scopes = $3, updated_at = now()
`

type UpsertConsentParams struct {
	AccountID     int32    `json:"accountId"`
	ClientID      string   `json:"clientId"`
	GrantedScopes []string `json:"grantedScopes"`
}

func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) error {
	_, err := q.db.Exec(ctx, upsertConsent, arg.AccountID, arg.ClientID, arg.GrantedScopes)
	return err
}
