// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOIDCClient = `-- name: DeleteOIDCClient :execrows
DELETE FROM oidc_client WHERE client_id = $1
`

func (q *Queries) DeleteOIDCClient(ctx context.Context, clientID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOIDCClient, clientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const demoteActiveSigningKey = `-- name: DemoteActiveSigningKey :exec
UPDATE signing_key
SET status='decommissioning', active=false, decommissioned_at=now(), retire_after=$1
WHERE use='sig' AND status='active'
`

func (q *Queries) DemoteActiveSigningKey(ctx context.Context, retireAfter pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, demoteActiveSigningKey, retireAfter)
	return err
}

const getAccountByOIDCSubject = `-- name: GetAccountByOIDCSubject :one
SELECT id, username, display_name, webauthn_user_handle, oidc_subject, role, attributes, disabled, created_at, updated_at, email, email_verified FROM account WHERE oidc_subject = $1
`

func (q *Queries) GetAccountByOIDCSubject(ctx context.Context, oidcSubject pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByOIDCSubject, oidcSubject)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.OidcSubject,
		&i.Role,
		&i.Attributes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT kid, algorithm, use, public_jwk, x509_cert_pem, private_pem, active, not_before, created_at, retired_at, status, activated_at, decommissioned_at, retire_after FROM signing_key WHERE use = 'sig' AND status = 'active'
`

func (q *Queries) GetActiveSigningKey(ctx context.Context) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.Algorithm,
		&i.Use,
		&i.PublicJwk,
		&i.X509CertPem,
		&i.PrivatePem,
		&i.Active,
		&i.NotBefore,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.Status,
		&i.ActivatedAt,
		&i.DecommissionedAt,
		&i.RetireAfter,
	)
	return i, err
}

const getOIDCClient = `-- name: GetOIDCClient :one
SELECT client_id, display_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, allowed_scopes, require_pkce, allowed_code_challenge_methods, token_endpoint_auth_method, id_token_signed_response_alg, subject_type, application_type, default_max_age, require_auth_time, contacts, logo_uri, tos_uri, policy_uri, disabled, require_consent, created_at FROM oidc_client WHERE client_id = $1 AND disabled = false
`

func (q *Queries) GetOIDCClient(ctx context.Context, clientID string) (OidcClient, error) {
	row := q.db.QueryRow(ctx, getOIDCClient, clientID)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.DisplayName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.AllowedScopes,
		&i.RequirePkce,
		&i.AllowedCodeChallengeMethods,
		&i.TokenEndpointAuthMethod,
		&i.IDTokenSignedResponseAlg,
		&i.SubjectType,
		&i.ApplicationType,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.Contacts,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Disabled,
		&i.RequireConsent,
		&i.CreatedAt,
	)
	return i, err
}

const getOIDCClientAny = `-- name: GetOIDCClientAny :one
SELECT client_id, display_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, allowed_scopes, require_pkce, allowed_code_challenge_methods, token_endpoint_auth_method, id_token_signed_response_alg, subject_type, application_type, default_max_age, require_auth_time, contacts, logo_uri, tos_uri, policy_uri, disabled, require_consent, created_at FROM oidc_client WHERE client_id = $1
`

func (q *Queries) GetOIDCClientAny(ctx context.Context, clientID string) (OidcClient, error) {
	row := q.db.QueryRow(ctx, getOIDCClientAny, clientID)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.DisplayName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.AllowedScopes,
		&i.RequirePkce,
		&i.AllowedCodeChallengeMethods,
		&i.TokenEndpointAuthMethod,
		&i.IDTokenSignedResponseAlg,
		&i.SubjectType,
		&i.ApplicationType,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.Contacts,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Disabled,
		&i.RequireConsent,
		&i.CreatedAt,
	)
	return i, err
}

const getSigningKeyByKID = `-- name: GetSigningKeyByKID :one
SELECT kid, algorithm, use, public_jwk, x509_cert_pem, private_pem, active, not_before, created_at, retired_at, status, activated_at, decommissioned_at, retire_after FROM signing_key WHERE kid = $1
`

func (q *Queries) GetSigningKeyByKID(ctx context.Context, kid string) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getSigningKeyByKID, kid)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.Algorithm,
		&i.Use,
		&i.PublicJwk,
		&i.X509CertPem,
		&i.PrivatePem,
		&i.Active,
		&i.NotBefore,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.Status,
		&i.ActivatedAt,
		&i.DecommissionedAt,
		&i.RetireAfter,
	)
	return i, err
}

const insertOIDCClient = `-- name: InsertOIDCClient :one
INSERT INTO oidc_client (
  client_id, display_name, client_secret_hash, redirect_uris,
  post_logout_redirect_uris, allowed_scopes, require_pkce,
  allowed_code_challenge_methods, token_endpoint_auth_method,
  subject_type, application_type, require_consent
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
RETURNING client_id, display_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, allowed_scopes, require_pkce, allowed_code_challenge_methods, token_endpoint_auth_method, id_token_signed_response_alg, subject_type, application_type, default_max_age, require_auth_time, contacts, logo_uri, tos_uri, policy_uri, disabled, require_consent, created_at
`

type InsertOIDCClientParams struct {
	ClientID                    string      `json:"clientId"`
	DisplayName                 string      `json:"displayName"`
	ClientSecretHash            pgtype.Text `json:"clientSecretHash"`
	RedirectUris                []string    `json:"redirectUris"`
	PostLogoutRedirectUris      []string    `json:"postLogoutRedirectUris"`
	AllowedScopes               []string    `json:"allowedScopes"`
	RequirePkce                 bool        `json:"requirePkce"`
	AllowedCodeChallengeMethods []string    `json:"allowedCodeChallengeMethods"`
	TokenEndpointAuthMethod     string      `json:"tokenEndpointAuthMethod"`
	SubjectType                 string      `json:"subjectType"`
	ApplicationType             string      `json:"applicationType"`
	RequireConsent              bool        `json:"requireConsent"`
}

func (q *Queries) InsertOIDCClient(ctx context.Context, arg InsertOIDCClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, insertOIDCClient,
		arg.ClientID,
		arg.DisplayName,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.AllowedScopes,
		arg.RequirePkce,
		arg.AllowedCodeChallengeMethods,
		arg.TokenEndpointAuthMethod,
		arg.SubjectType,
		arg.ApplicationType,
		arg.RequireConsent,
	)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.DisplayName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.AllowedScopes,
		&i.RequirePkce,
		&i.AllowedCodeChallengeMethods,
		&i.TokenEndpointAuthMethod,
		&i.IDTokenSignedResponseAlg,
		&i.SubjectType,
		&i.ApplicationType,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.Contacts,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Disabled,
		&i.RequireConsent,
		&i.CreatedAt,
	)
	return i, err
}

const insertPendingSigningKey = `-- name: InsertPendingSigningKey :one
INSERT INTO signing_key (kid, algorithm, use, public_jwk, x509_cert_pem, private_pem, active, status, not_before)
VALUES ($1,$2,'sig',$3,$4,$5,false,'pending', now())
RETURNING kid, algorithm, use, public_jwk, x509_cert_pem, private_pem, active, not_before, created_at, retired_at, status, activated_at, decommissioned_at, retire_after
`

type InsertPendingSigningKeyParams struct {
	Kid         string      `json:"kid"`
	Algorithm   string      `json:"algorithm"`
	PublicJwk   []byte      `json:"publicJwk"`
	X509CertPem pgtype.Text `json:"x509CertPem"`
	PrivatePem  string      `json:"privatePem"`
}

func (q *Queries) InsertPendingSigningKey(ctx context.Context, arg InsertPendingSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, insertPendingSigningKey,
		arg.Kid,
		arg.Algorithm,
		arg.PublicJwk,
		arg.X509CertPem,
		arg.PrivatePem,
	)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.Algorithm,
		&i.Use,
		&i.PublicJwk,
		&i.X509CertPem,
		&i.PrivatePem,
		&i.Active,
		&i.NotBefore,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.Status,
		&i.ActivatedAt,
		&i.DecommissionedAt,
		&i.RetireAfter,
	)
	return i, err
}

const insertRevokedJTI = `-- name: InsertRevokedJTI :exec
INSERT INTO revoked_jti (jti, expires_at, reason) VALUES ($1,$2,$3)
ON CONFLICT (jti) DO NOTHING
`

type InsertRevokedJTIParams struct {
	Jti       string             `json:"jti"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	Reason    pgtype.Text        `json:"reason"`
}

func (q *Queries) InsertRevokedJTI(ctx context.Context, arg InsertRevokedJTIParams) error {
	_, err := q.db.Exec(ctx, insertRevokedJTI, arg.Jti, arg.ExpiresAt, arg.Reason)
	return err
}

const isJTIRevoked = `-- name: IsJTIRevoked :one
SELECT EXISTS (SELECT 1 FROM revoked_jti WHERE jti = $1)
`

func (q *Queries) IsJTIRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isJTIRevoked, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllSigningKeys = `-- name: ListAllSigningKeys :many
SELECT kid, algorithm, use, public_jwk, x509_cert_pem, private_pem, active, not_before, created_at, retired_at, status, activated_at, decommissioned_at, retire_after FROM signing_key WHERE use = 'sig' ORDER BY created_at DESC
`

func (q *Queries) ListAllSigningKeys(ctx context.Context) ([]SigningKey, error) {
	rows, err := q.db.Query(ctx, listAllSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningKey
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.Kid,
			&i.Algorithm,
			&i.Use,
			&i.PublicJwk,
			&i.X509CertPem,
			&i.PrivatePem,
			&i.Active,
			&i.NotBefore,
			&i.CreatedAt,
			&i.RetiredAt,
			&i.Status,
			&i.ActivatedAt,
			&i.DecommissionedAt,
			&i.RetireAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClients = `-- name: ListOIDCClients :many
SELECT client_id, display_name, redirect_uris, allowed_scopes,
       token_endpoint_auth_method, disabled, created_at
FROM oidc_client ORDER BY created_at DESC
`

type ListOIDCClientsRow struct {
	ClientID                string             `json:"clientId"`
	DisplayName             string             `json:"displayName"`
	RedirectUris            []string           `json:"redirectUris"`
	AllowedScopes           []string           `json:"allowedScopes"`
	TokenEndpointAuthMethod string             `json:"tokenEndpointAuthMethod"`
	Disabled                bool               `json:"disabled"`
	CreatedAt               pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) ListOIDCClients(ctx context.Context) ([]ListOIDCClientsRow, error) {
	rows, err := q.db.Query(ctx, listOIDCClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCClientsRow
	for rows.Next() {
		var i ListOIDCClientsRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.RedirectUris,
			&i.AllowedScopes,
			&i.TokenEndpointAuthMethod,
			&i.Disabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishableSigningKeys = `-- name: ListPublishableSigningKeys :many
SELECT kid, algorithm, use, public_jwk, x509_cert_pem, private_pem, active, not_before, created_at, retired_at, status, activated_at, decommissioned_at, retire_after FROM signing_key
WHERE use = 'sig' AND status IN ('pending','active','decommissioning')
ORDER BY created_at DESC
`

func (q *Queries) ListPublishableSigningKeys(ctx context.Context) ([]SigningKey, error) {
	rows, err := q.db.Query(ctx, listPublishableSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SigningKey
	for rows.Next() {
		var i SigningKey
		if err := rows.Scan(
			&i.Kid,
			&i.Algorithm,
			&i.Use,
			&i.PublicJwk,
			&i.X509CertPem,
			&i.PrivatePem,
			&i.Active,
			&i.NotBefore,
			&i.CreatedAt,
			&i.RetiredAt,
			&i.Status,
			&i.ActivatedAt,
			&i.DecommissionedAt,
			&i.RetireAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteSigningKey = `-- name: PromoteSigningKey :one
UPDATE signing_key
SET status='active', active=true, activated_at=now()
WHERE kid=$1 AND status='pending'
RETURNING kid, algorithm, use, public_jwk, x509_cert_pem, private_pem, active, not_before, created_at, retired_at, status, activated_at, decommissioned_at, retire_after
`

func (q *Queries) PromoteSigningKey(ctx context.Context, kid string) (SigningKey, error) {
	row := q.db.QueryRow(ctx, promoteSigningKey, kid)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.Algorithm,
		&i.Use,
		&i.PublicJwk,
		&i.X509CertPem,
		&i.PrivatePem,
		&i.Active,
		&i.NotBefore,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.Status,
		&i.ActivatedAt,
		&i.DecommissionedAt,
		&i.RetireAfter,
	)
	return i, err
}

const pruneExpiredRevokedJTI = `-- name: PruneExpiredRevokedJTI :exec
DELETE FROM revoked_jti WHERE expires_at < now()
`

func (q *Queries) PruneExpiredRevokedJTI(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneExpiredRevokedJTI)
	return err
}

const reconcileRetiredSigningKeys = `-- name: ReconcileRetiredSigningKeys :execrows
UPDATE signing_key SET status='retired'
WHERE use='sig' AND status='decommissioning'
  AND retire_after IS NOT NULL AND now() >= retire_after
`

func (q *Queries) ReconcileRetiredSigningKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileRetiredSigningKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireSigningKey = `-- name: RetireSigningKey :one
UPDATE signing_key
SET status='decommissioning', active=false,
    decommissioned_at=COALESCE(decommissioned_at, now()), retire_after=$2
WHERE kid=$1 AND status IN ('pending','decommissioning')
RETURNING kid, algorithm, use, public_jwk, x509_cert_pem, private_pem, active, not_before, created_at, retired_at, status, activated_at, decommissioned_at, retire_after
`

type RetireSigningKeyParams struct {
	Kid         string             `json:"kid"`
	RetireAfter pgtype.Timestamptz `json:"retireAfter"`
}

func (q *Queries) RetireSigningKey(ctx context.Context, arg RetireSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, retireSigningKey, arg.Kid, arg.RetireAfter)
	var i SigningKey
	err := row.Scan(
		&i.Kid,
		&i.Algorithm,
		&i.Use,
		&i.PublicJwk,
		&i.X509CertPem,
		&i.PrivatePem,
		&i.Active,
		&i.NotBefore,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.Status,
		&i.ActivatedAt,
		&i.DecommissionedAt,
		&i.RetireAfter,
	)
	return i, err
}

const updateOIDCClient = `-- name: UpdateOIDCClient :one
UPDATE oidc_client SET
  display_name = $2, redirect_uris = $3, post_logout_redirect_uris = $4,
  allowed_scopes = $5, require_consent = $6, disabled = $7
WHERE client_id = $1
RETURNING client_id, display_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, allowed_scopes, require_pkce, allowed_code_challenge_methods, token_endpoint_auth_method, id_token_signed_response_alg, subject_type, application_type, default_max_age, require_auth_time, contacts, logo_uri, tos_uri, policy_uri, disabled, require_consent, created_at
`

type UpdateOIDCClientParams struct {
	ClientID               string   `json:"clientId"`
	DisplayName            string   `json:"displayName"`
	RedirectUris           []string `json:"redirectUris"`
	PostLogoutRedirectUris []string `json:"postLogoutRedirectUris"`
	AllowedScopes          []string `json:"allowedScopes"`
	RequireConsent         bool     `json:"requireConsent"`
	Disabled               bool     `json:"disabled"`
}

func (q *Queries) UpdateOIDCClient(ctx context.Context, arg UpdateOIDCClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, updateOIDCClient,
		arg.ClientID,
		arg.DisplayName,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.AllowedScopes,
		arg.RequireConsent,
		arg.Disabled,
	)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.DisplayName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.AllowedScopes,
		&i.RequirePkce,
		&i.AllowedCodeChallengeMethods,
		&i.TokenEndpointAuthMethod,
		&i.IDTokenSignedResponseAlg,
		&i.SubjectType,
		&i.ApplicationType,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.Contacts,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Disabled,
		&i.RequireConsent,
		&i.CreatedAt,
	)
	return i, err
}

const updateOIDCClientSecret = `-- name: UpdateOIDCClientSecret :exec
UPDATE oidc_client SET client_secret_hash = $2 WHERE client_id = $1
`

type UpdateOIDCClientSecretParams struct {
	ClientID         string      `json:"clientId"`
	ClientSecretHash pgtype.Text `json:"clientSecretHash"`
}

func (q *Queries) UpdateOIDCClientSecret(ctx context.Context, arg UpdateOIDCClientSecretParams) error {
	_, err := q.db.Exec(ctx, updateOIDCClientSecret, arg.ClientID, arg.ClientSecretHash)
	return err
}
