// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateAllSigningKeys = `-- name: DeactivateAllSigningKeys :exec
UPDATE oidc_signing_key SET active = FALSE WHERE active = TRUE
`

func (q *Queries) DeactivateAllSigningKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllSigningKeys)
	return err
}

const deleteOIDCClient = `-- name: DeleteOIDCClient :exec
DELETE FROM oidc_client WHERE client_id = $1
`

func (q *Queries) DeleteOIDCClient(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, deleteOIDCClient, clientID)
	return err
}

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT kid, algorithm, public_jwk, private_pem, active, created_at, retired_at FROM oidc_signing_key WHERE active = TRUE LIMIT 1
`

func (q *Queries) GetActiveSigningKey(ctx context.Context) (OidcSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey)
	var i OidcSigningKey
	err := row.Scan(
		&i.Kid,
		&i.Algorithm,
		&i.PublicJwk,
		&i.PrivatePem,
		&i.Active,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getOIDCClient = `-- name: GetOIDCClient :one
SELECT client_id, client_secret_hash, display_name, redirect_uris, allowed_scopes, created_at FROM oidc_client WHERE client_id = $1
`

func (q *Queries) GetOIDCClient(ctx context.Context, clientID string) (OidcClient, error) {
	row := q.db.QueryRow(ctx, getOIDCClient, clientID)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientSecretHash,
		&i.DisplayName,
		&i.RedirectUris,
		&i.AllowedScopes,
		&i.CreatedAt,
	)
	return i, err
}

const insertOIDCClient = `-- name: InsertOIDCClient :one
INSERT INTO oidc_client (client_id, client_secret_hash, display_name, redirect_uris, allowed_scopes)
VALUES ($1, $2, $3, $4, $5)
RETURNING client_id, client_secret_hash, display_name, redirect_uris, allowed_scopes, created_at
`

type InsertOIDCClientParams struct {
	ClientID         string      `json:"clientId"`
	ClientSecretHash pgtype.Text `json:"clientSecretHash"`
	DisplayName      string      `json:"displayName"`
	RedirectUris     []string    `json:"redirectUris"`
	AllowedScopes    []string    `json:"allowedScopes"`
}

func (q *Queries) InsertOIDCClient(ctx context.Context, arg InsertOIDCClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, insertOIDCClient,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.DisplayName,
		arg.RedirectUris,
		arg.AllowedScopes,
	)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientSecretHash,
		&i.DisplayName,
		&i.RedirectUris,
		&i.AllowedScopes,
		&i.CreatedAt,
	)
	return i, err
}

const insertSigningKey = `-- name: InsertSigningKey :one
INSERT INTO oidc_signing_key (kid, algorithm, public_jwk, private_pem, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING kid, algorithm, public_jwk, private_pem, active, created_at, retired_at
`

type InsertSigningKeyParams struct {
	Kid        string `json:"kid"`
	Algorithm  string `json:"algorithm"`
	PublicJwk  []byte `json:"publicJwk"`
	PrivatePem []byte `json:"privatePem"`
	Active     bool   `json:"active"`
}

func (q *Queries) InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) (OidcSigningKey, error) {
	row := q.db.QueryRow(ctx, insertSigningKey,
		arg.Kid,
		arg.Algorithm,
		arg.PublicJwk,
		arg.PrivatePem,
		arg.Active,
	)
	var i OidcSigningKey
	err := row.Scan(
		&i.Kid,
		&i.Algorithm,
		&i.PublicJwk,
		&i.PrivatePem,
		&i.Active,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const listOIDCClients = `-- name: ListOIDCClients :many
SELECT client_id, client_secret_hash, display_name, redirect_uris, allowed_scopes, created_at FROM oidc_client ORDER BY display_name ASC
`

func (q *Queries) ListOIDCClients(ctx context.Context) ([]OidcClient, error) {
	rows, err := q.db.Query(ctx, listOIDCClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcClient
	for rows.Next() {
		var i OidcClient
		if err := rows.Scan(
			&i.ClientID,
			&i.ClientSecretHash,
			&i.DisplayName,
			&i.RedirectUris,
			&i.AllowedScopes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifyingSigningKeys = `-- name: ListVerifyingSigningKeys :many
SELECT kid, algorithm, public_jwk, private_pem, active, created_at, retired_at FROM oidc_signing_key
WHERE retired_at IS NULL OR retired_at > now()
ORDER BY created_at DESC
`

// Every non-retired key: the active signing key + any keys still inside
// their rollover window. JWKS endpoint serves the public_jwk of each.
func (q *Queries) ListVerifyingSigningKeys(ctx context.Context) ([]OidcSigningKey, error) {
	rows, err := q.db.Query(ctx, listVerifyingSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcSigningKey
	for rows.Next() {
		var i OidcSigningKey
		if err := rows.Scan(
			&i.Kid,
			&i.Algorithm,
			&i.PublicJwk,
			&i.PrivatePem,
			&i.Active,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireSigningKey = `-- name: RetireSigningKey :exec
UPDATE oidc_signing_key SET retired_at = $2 WHERE kid = $1
`

type RetireSigningKeyParams struct {
	Kid       string             `json:"kid"`
	RetiredAt pgtype.Timestamptz `json:"retiredAt"`
}

func (q *Queries) RetireSigningKey(ctx context.Context, arg RetireSigningKeyParams) error {
	_, err := q.db.Exec(ctx, retireSigningKey, arg.Kid, arg.RetiredAt)
	return err
}
