// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_credential.sql

package db

import (
	"context"
)

const deletePasswordCredential = `-- name: DeletePasswordCredential :exec
DELETE FROM password_credential WHERE account_id = $1
`

func (q *Queries) DeletePasswordCredential(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, deletePasswordCredential, accountID)
	return err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT account_id, hash, password_changed_at, updated_at FROM password_credential WHERE account_id = $1
`

func (q *Queries) GetPasswordCredential(ctx context.Context, accountID int32) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredential, accountID)
	var i PasswordCredential
	err := row.Scan(
		&i.AccountID,
		&i.Hash,
		&i.PasswordChangedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordHashOnly = `-- name: UpdatePasswordHashOnly :exec
UPDATE password_credential
SET hash = $2,
    updated_at = now()
WHERE account_id = $1
`

type UpdatePasswordHashOnlyParams struct {
	AccountID int32  `json:"accountId"`
	Hash      string `json:"hash"`
}

// Replace the stored hash WITHOUT touching password_changed_at — used by the
// transparent argon2id param-upgrade rehash on a successful Verify (T4.3a). The
// secret has not changed, so password_changed_at (which feeds password-age /
// forced-reauth policy) must not move; only the at-rest encoding did.
func (q *Queries) UpdatePasswordHashOnly(ctx context.Context, arg UpdatePasswordHashOnlyParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHashOnly, arg.AccountID, arg.Hash)
	return err
}

const upsertPasswordCredential = `-- name: UpsertPasswordCredential :exec
INSERT INTO password_credential (account_id, hash)
VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE
SET hash = EXCLUDED.hash,
    password_changed_at = now(),
    updated_at = now()
`

type UpsertPasswordCredentialParams struct {
	AccountID int32  `json:"accountId"`
	Hash      string `json:"hash"`
}

func (q *Queries) UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordCredential, arg.AccountID, arg.Hash)
	return err
}
