// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_access_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPATByID = `-- name: GetPATByID :one
SELECT id, account_id, name, token_hash, token_hint, created_at, expires_at, last_used_at, revoked_at, access FROM personal_access_token WHERE id = $1
`

func (q *Queries) GetPATByID(ctx context.Context, id int32) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPATByID, id)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Access,
	)
	return i, err
}

const getPATByTokenHash = `-- name: GetPATByTokenHash :one
SELECT id, account_id, name, token_hash, token_hint, created_at, expires_at, last_used_at, revoked_at, access FROM personal_access_token
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetPATByTokenHash(ctx context.Context, tokenHash []byte) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPATByTokenHash, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Access,
	)
	return i, err
}

const insertPAT = `-- name: InsertPAT :one
INSERT INTO personal_access_token (
  account_id, name, token_hash, token_hint, access, expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, name, token_hash, token_hint, created_at, expires_at, last_used_at, revoked_at, access
`

type InsertPATParams struct {
	AccountID int32              `json:"accountId"`
	Name      string             `json:"name"`
	TokenHash []byte             `json:"tokenHash"`
	TokenHint string             `json:"tokenHint"`
	Access    string             `json:"access"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) InsertPAT(ctx context.Context, arg InsertPATParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, insertPAT,
		arg.AccountID,
		arg.Name,
		arg.TokenHash,
		arg.TokenHint,
		arg.Access,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Access,
	)
	return i, err
}

const insertPATApp = `-- name: InsertPATApp :exec
INSERT INTO personal_access_token_app (pat_id, client_id) VALUES ($1, $2)
`

type InsertPATAppParams struct {
	PatID    int32  `json:"patId"`
	ClientID string `json:"clientId"`
}

func (q *Queries) InsertPATApp(ctx context.Context, arg InsertPATAppParams) error {
	_, err := q.db.Exec(ctx, insertPATApp, arg.PatID, arg.ClientID)
	return err
}

const listPATAppsByPATIDs = `-- name: ListPATAppsByPATIDs :many
SELECT a.pat_id, a.client_id, c.display_name
FROM personal_access_token_app a
JOIN oidc_client c ON c.client_id = a.client_id
WHERE a.pat_id = ANY($1::int[])
ORDER BY c.display_name, c.client_id
`

type ListPATAppsByPATIDsRow struct {
	PatID       int32  `json:"patId"`
	ClientID    string `json:"clientId"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) ListPATAppsByPATIDs(ctx context.Context, patIds []int32) ([]ListPATAppsByPATIDsRow, error) {
	rows, err := q.db.Query(ctx, listPATAppsByPATIDs, patIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPATAppsByPATIDsRow
	for rows.Next() {
		var i ListPATAppsByPATIDsRow
		if err := rows.Scan(&i.PatID, &i.ClientID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPATsByAccount = `-- name: ListPATsByAccount :many
SELECT id, account_id, name, token_hash, token_hint, created_at, expires_at, last_used_at, revoked_at, access FROM personal_access_token
WHERE account_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPATsByAccount(ctx context.Context, accountID int32) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listPATsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalAccessToken
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.TokenHash,
			&i.TokenHint,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.Access,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPATsByAccountPage = `-- name: ListPATsByAccountPage :many
SELECT id, account_id, name, token_hash, token_hint, created_at, expires_at, last_used_at, revoked_at, access FROM personal_access_token
WHERE account_id = $1 AND revoked_at IS NULL
  AND ($2::timestamptz IS NULL OR (created_at, id) < ($2, $3::integer))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListPATsByAccountPageParams struct {
	AccountID      int32              `json:"accountId"`
	AfterCreatedAt pgtype.Timestamptz `json:"afterCreatedAt"`
	AfterID        int32              `json:"afterId"`
	RowLimit       int32              `json:"rowLimit"`
}

// Keyset-paginated non-revoked PATs for an account, ordered by (created_at DESC, id DESC).
// NULL after_created_at starts a new page. LIMIT is limit+1 for next-page detection.
func (q *Queries) ListPATsByAccountPage(ctx context.Context, arg ListPATsByAccountPageParams) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listPATsByAccountPage,
		arg.AccountID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalAccessToken
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.TokenHash,
			&i.TokenHint,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.Access,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pATGrantsApp = `-- name: PATGrantsApp :one
SELECT EXISTS (
  SELECT 1 FROM personal_access_token_app
  WHERE pat_id = $1 AND client_id = $2
)
`

type PATGrantsAppParams struct {
	PatID    int32  `json:"patId"`
	ClientID string `json:"clientId"`
}

func (q *Queries) PATGrantsApp(ctx context.Context, arg PATGrantsAppParams) (bool, error) {
	row := q.db.QueryRow(ctx, pATGrantsApp, arg.PatID, arg.ClientID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokePAT = `-- name: RevokePAT :execrows
UPDATE personal_access_token
SET revoked_at = now()
WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL
`

type RevokePATParams struct {
	ID        int32 `json:"id"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) RevokePAT(ctx context.Context, arg RevokePATParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePAT, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePATByID = `-- name: RevokePATByID :execrows
UPDATE personal_access_token
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokePATByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, revokePATByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchPATLastUsed = `-- name: TouchPATLastUsed :exec
UPDATE personal_access_token
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchPATLastUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, touchPATLastUsed, id)
	return err
}
