// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_access_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPATByID = `-- name: GetPATByID :one
SELECT id, account_id, name, token_hash, token_hint, all_apps, app_grants, created_at, expires_at, last_used_at, revoked_at FROM personal_access_token WHERE id = $1
`

func (q *Queries) GetPATByID(ctx context.Context, id int32) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPATByID, id)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.AllApps,
		&i.AppGrants,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPATByTokenHash = `-- name: GetPATByTokenHash :one
SELECT id, account_id, name, token_hash, token_hint, all_apps, app_grants, created_at, expires_at, last_used_at, revoked_at FROM personal_access_token
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetPATByTokenHash(ctx context.Context, tokenHash []byte) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPATByTokenHash, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.AllApps,
		&i.AppGrants,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertPAT = `-- name: InsertPAT :one
INSERT INTO personal_access_token (
  account_id, name, token_hash, token_hint, all_apps, app_grants, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, name, token_hash, token_hint, all_apps, app_grants, created_at, expires_at, last_used_at, revoked_at
`

type InsertPATParams struct {
	AccountID int32              `json:"accountId"`
	Name      string             `json:"name"`
	TokenHash []byte             `json:"tokenHash"`
	TokenHint string             `json:"tokenHint"`
	AllApps   bool               `json:"allApps"`
	AppGrants []byte             `json:"appGrants"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) InsertPAT(ctx context.Context, arg InsertPATParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, insertPAT,
		arg.AccountID,
		arg.Name,
		arg.TokenHash,
		arg.TokenHint,
		arg.AllApps,
		arg.AppGrants,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.AllApps,
		&i.AppGrants,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listPATsByAccount = `-- name: ListPATsByAccount :many
SELECT id, account_id, name, token_hash, token_hint, all_apps, app_grants, created_at, expires_at, last_used_at, revoked_at FROM personal_access_token
WHERE account_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPATsByAccount(ctx context.Context, accountID int32) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listPATsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalAccessToken
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.TokenHash,
			&i.TokenHint,
			&i.AllApps,
			&i.AppGrants,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePAT = `-- name: RevokePAT :execrows
UPDATE personal_access_token
SET revoked_at = now()
WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL
`

type RevokePATParams struct {
	ID        int32 `json:"id"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) RevokePAT(ctx context.Context, arg RevokePATParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePAT, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePATByID = `-- name: RevokePATByID :execrows
UPDATE personal_access_token
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokePATByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, revokePATByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchPATLastUsed = `-- name: TouchPATLastUsed :exec
UPDATE personal_access_token
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchPATLastUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, touchPATLastUsed, id)
	return err
}
