// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	//
	// Atomic increment + lockout-from-just-incremented-count. The previous
	// read-then-UPSERT path lost increments under K-way concurrency (K callers
	// all read the same prior count, then last-write-wins clobbered to count+1)
	// and worse, picked the lockout duration off the racing snapshot rather than
	// the post-increment value. This single round-trip carries the full
	// exponential-backoff schedule as a bigint[] of microsecond durations; the
	// CASE clauses index into it using auth_throttle.failed_attempts + 1, which
	// Postgres evaluates against the just-incremented row.
	//
	// $3 layout: schedule[i] is the lockout duration (in microseconds) applied
	// on the i-th failure (1-indexed). 0 means "no lockout yet — still in the
	// free-attempt prefix". Indexing past the array clamps to the last entry,
	// matching the Go-side schedule-walk semantics.
	BumpAuthThrottle(ctx context.Context, arg BumpAuthThrottleParams) (BumpAuthThrottleRow, error)
	ClearActiveAvatar(ctx context.Context, arg ClearActiveAvatarParams) error
	ConfirmAccountIdentity(ctx context.Context, id int64) error
	ConfirmTOTPCredential(ctx context.Context, accountID int32) error
	// Atomic single-use consume. Returns the row only if it was unconsumed and unexpired.
	// Callers detect any "not consumable" branch via pgx.ErrNoRows.
	ConsumeEnrollment(ctx context.Context, token string) (Enrollment, error)
	// Atomic single-use consume, intent-restricted to 'invite' AND unexpired. Used
	// by the federation invite-redemption path (applyInviteOnly) so a bootstrap or
	// reset token can never be marked consumed via the federation callback —
	// defense-in-depth on top of the begin-time intent gate (audit OIDCFED-2).
	// pgx.ErrNoRows surfaces on any not-consumable branch.
	ConsumeInviteEnrollment(ctx context.Context, token string) (Enrollment, error)
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (RecoveryCode, error)
	CountActiveAdminsForUpdate(ctx context.Context) (int64, error)
	CountCredentialsByAccount(ctx context.Context, accountID int32) (int64, error)
	// Linked identities the account can actually sign in / step up with: the
	// upstream IdP must still exist and be enabled. (ListAccountIdentitiesByAccount
	// intentionally returns ALL links, incl. disabled-upstream, for display/unlink.)
	CountUsableSignInFederation(ctx context.Context, accountID int32) (int64, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (UserGroup, error)
	DeleteAccountByID(ctx context.Context, id int32) error
	// Returns the deleted row's id when one matched; pgx.ErrNoRows when the
	// (id, account_id) pair matches nothing (foreign identity, already-
	// deleted, or unknown id). Callers map ErrNoRows to a 404 + skip audit.
	DeleteAccountIdentity(ctx context.Context, arg DeleteAccountIdentityParams) (int64, error)
	DeleteAllCredentialsForAccount(ctx context.Context, accountID int32) error
	DeleteAllRecoveryCodesByAccount(ctx context.Context, accountID int32) error
	DeleteAvatarSource(ctx context.Context, arg DeleteAvatarSourceParams) error
	DeleteConsent(ctx context.Context, arg DeleteConsentParams) error
	// Owner-scoped delete: zero rows affected means the id doesn't match an owned
	// credential; handlers map that to credential_not_found.
	DeleteCredentialByID(ctx context.Context, arg DeleteCredentialByIDParams) (int64, error)
	DeleteEntityIcon(ctx context.Context, arg DeleteEntityIconParams) error
	DeleteExpiredSAMLSessions(ctx context.Context) (int64, error)
	DeleteGroup(ctx context.Context, id int32) (int64, error)
	DeleteOIDCClient(ctx context.Context, clientID string) (int64, error)
	DeletePasswordCredential(ctx context.Context, accountID int32) error
	DeleteSAMLConsent(ctx context.Context, arg DeleteSAMLConsentParams) error
	DeleteSAMLSP(ctx context.Context, id int64) (int64, error)
	DeleteSAMLSPACSByID(ctx context.Context, spID int64) error
	DeleteSAMLSPKeysByID(ctx context.Context, spID int64) error
	DeleteSAMLSessionsBySession(ctx context.Context, sessionID string) error
	DeleteTOTPCredential(ctx context.Context, accountID int32) error
	DeleteUpstreamIDP(ctx context.Context, id int64) error
	DemoteActiveSigningKey(ctx context.Context, retireAfter pgtype.Timestamptz) error
	GetAccountByID(ctx context.Context, id int32) (Account, error)
	GetAccountByIDForUpdate(ctx context.Context, id int32) (Account, error)
	GetAccountByOIDCSubject(ctx context.Context, oidcSubject pgtype.UUID) (Account, error)
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
	GetAccountByWebauthnUserHandle(ctx context.Context, webauthnUserHandle []byte) (Account, error)
	GetAccountIdentityByIssuerSub(ctx context.Context, arg GetAccountIdentityByIssuerSubParams) (AccountIdentity, error)
	GetActiveAvatarBySubject(ctx context.Context, oidcSubject pgtype.UUID) (GetActiveAvatarBySubjectRow, error)
	GetActiveSigningKey(ctx context.Context) (SigningKey, error)
	GetAuthThrottle(ctx context.Context, arg GetAuthThrottleParams) (AuthThrottle, error)
	GetAvatarSourceBySubject(ctx context.Context, arg GetAvatarSourceBySubjectParams) (GetAvatarSourceBySubjectRow, error)
	GetConsent(ctx context.Context, arg GetConsentParams) ([]string, error)
	GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error)
	GetEnrollmentByToken(ctx context.Context, token string) (Enrollment, error)
	GetEntityIcon(ctx context.Context, arg GetEntityIconParams) (GetEntityIconRow, error)
	GetEntityIconEtag(ctx context.Context, arg GetEntityIconEtagParams) (string, error)
	GetEntityIconMeta(ctx context.Context, arg GetEntityIconMetaParams) (GetEntityIconMetaRow, error)
	GetForwardAuthAppByID(ctx context.Context, clientID string) (GetForwardAuthAppByIDRow, error)
	GetForwardAuthClientByHost(ctx context.Context, forwardAuthHost pgtype.Text) (GetForwardAuthClientByHostRow, error)
	GetGroup(ctx context.Context, id int32) (UserGroup, error)
	GetGroupBySlug(ctx context.Context, slug string) (UserGroup, error)
	GetOIDCClient(ctx context.Context, clientID string) (OidcClient, error)
	GetOIDCClientAny(ctx context.Context, clientID string) (OidcClient, error)
	GetPasswordCredential(ctx context.Context, accountID int32) (PasswordCredential, error)
	GetSAMLSPByEntityID(ctx context.Context, entityID string) (SamlSp, error)
	GetSAMLSPByID(ctx context.Context, id int64) (SamlSp, error)
	GetSAMLSubjectID(ctx context.Context, arg GetSAMLSubjectIDParams) (SamlSubjectID, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSigningKeyByKID(ctx context.Context, kid string) (SigningKey, error)
	GetTOTPCredential(ctx context.Context, accountID int32) (TotpCredential, error)
	GetUpstreamIDPBySlug(ctx context.Context, slug string) (UpstreamIdp, error)
	GetUpstreamIDPBySlugAny(ctx context.Context, slug string) (UpstreamIdp, error)
	GrantOIDCClientAccessAccount(ctx context.Context, arg GrantOIDCClientAccessAccountParams) error
	GrantOIDCClientAccessGroup(ctx context.Context, arg GrantOIDCClientAccessGroupParams) error
	GrantSAMLSPAccessAccount(ctx context.Context, arg GrantSAMLSPAccessAccountParams) error
	GrantSAMLSPAccessGroup(ctx context.Context, arg GrantSAMLSPAccessGroupParams) error
	HasAnyActiveAdmin(ctx context.Context) (bool, error)
	HasSAMLConsent(ctx context.Context, arg HasSAMLConsentParams) (bool, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error)
	InsertAccountIdentity(ctx context.Context, arg InsertAccountIdentityParams) (AccountIdentity, error)
	InsertCredential(ctx context.Context, arg InsertCredentialParams) (WebauthnCredential, error)
	InsertCredentialEvent(ctx context.Context, arg InsertCredentialEventParams) error
	InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error)
	InsertOIDCClient(ctx context.Context, arg InsertOIDCClientParams) (OidcClient, error)
	InsertPendingSigningKey(ctx context.Context, arg InsertPendingSigningKeyParams) (SigningKey, error)
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) (RecoveryCode, error)
	InsertRevokedJTI(ctx context.Context, arg InsertRevokedJTIParams) error
	InsertSAMLSP(ctx context.Context, arg InsertSAMLSPParams) (SamlSp, error)
	InsertSAMLSPACS(ctx context.Context, arg InsertSAMLSPACSParams) error
	InsertSAMLSPKey(ctx context.Context, arg InsertSAMLSPKeyParams) error
	InsertSAMLSession(ctx context.Context, arg InsertSAMLSessionParams) (SamlSession, error)
	InsertSAMLSubjectID(ctx context.Context, arg InsertSAMLSubjectIDParams) (SamlSubjectID, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error)
	InsertTOTPCredential(ctx context.Context, arg InsertTOTPCredentialParams) (TotpCredential, error)
	InsertUpstreamIDP(ctx context.Context, arg InsertUpstreamIDPParams) (UpstreamIdp, error)
	IsAccountAuthorizedForOIDCClient(ctx context.Context, arg IsAccountAuthorizedForOIDCClientParams) (pgtype.Bool, error)
	IsAccountAuthorizedForSAMLSP(ctx context.Context, arg IsAccountAuthorizedForSAMLSPParams) (pgtype.Bool, error)
	IsJTIRevoked(ctx context.Context, jti string) (bool, error)
	ListAccountIdentitiesByAccount(ctx context.Context, accountID int32) ([]ListAccountIdentitiesByAccountRow, error)
	ListAccounts(ctx context.Context) ([]ListAccountsRow, error)
	ListAllSigningKeys(ctx context.Context) ([]SigningKey, error)
	ListAllUpstreamIDPs(ctx context.Context) ([]UpstreamIdp, error)
	ListAuthorizedForwardAuthAppsForAccount(ctx context.Context, accountID pgtype.Int4) ([]ListAuthorizedForwardAuthAppsForAccountRow, error)
	ListAuthorizedOIDCClientsForAccount(ctx context.Context, accountID pgtype.Int4) ([]ListAuthorizedOIDCClientsForAccountRow, error)
	ListAuthorizedSAMLSPsForAccount(ctx context.Context, accountID pgtype.Int4) ([]ListAuthorizedSAMLSPsForAccountRow, error)
	// LEFT JOIN so the 'user' row (NULL idp_id) is kept with an empty label; the
	// join is by id (unconditional) so even a disabled upstream's inherited avatar
	// still resolves its display name.
	ListAvatarSourcesByAccount(ctx context.Context, accountID int32) ([]ListAvatarSourcesByAccountRow, error)
	ListConsentsByAccount(ctx context.Context, accountID int32) ([]ListConsentsByAccountRow, error)
	ListCredentialEvents(ctx context.Context, arg ListCredentialEventsParams) ([]CredentialEvent, error)
	ListCredentialEventsByAccount(ctx context.Context, arg ListCredentialEventsByAccountParams) ([]CredentialEvent, error)
	ListCredentialEventsByFactor(ctx context.Context, arg ListCredentialEventsByFactorParams) ([]CredentialEvent, error)
	ListCredentialsByAccount(ctx context.Context, accountID int32) ([]WebauthnCredential, error)
	ListEntityIconEtags(ctx context.Context, ownerKind string) ([]ListEntityIconEtagsRow, error)
	ListExposedGroupSlugsByAccount(ctx context.Context, accountID int32) ([]string, error)
	ListForwardAuthClients(ctx context.Context) ([]ListForwardAuthClientsRow, error)
	ListGroupMembers(ctx context.Context, groupID int32) ([]ListGroupMembersRow, error)
	ListGroups(ctx context.Context) ([]ListGroupsRow, error)
	ListGroupsForAccount(ctx context.Context, accountID int32) ([]UserGroup, error)
	ListNonForwardAuthOIDCClients(ctx context.Context) ([]ListNonForwardAuthOIDCClientsRow, error)
	ListOIDCClientAccessAccounts(ctx context.Context, clientID string) ([]ListOIDCClientAccessAccountsRow, error)
	ListOIDCClientAccessGroups(ctx context.Context, clientID string) ([]ListOIDCClientAccessGroupsRow, error)
	ListOIDCClients(ctx context.Context) ([]ListOIDCClientsRow, error)
	ListPendingInvitations(ctx context.Context) ([]Enrollment, error)
	ListPublishableSigningKeys(ctx context.Context) ([]SigningKey, error)
	ListRecoveryCodesByAccount(ctx context.Context, accountID int32) ([]RecoveryCode, error)
	ListSAMLConsentsByAccount(ctx context.Context, accountID int32) ([]ListSAMLConsentsByAccountRow, error)
	ListSAMLSPACSEndpoints(ctx context.Context, spID int64) ([]SamlSpAc, error)
	ListSAMLSPAccessAccounts(ctx context.Context, samlSpID int64) ([]ListSAMLSPAccessAccountsRow, error)
	ListSAMLSPAccessGroups(ctx context.Context, samlSpID int64) ([]ListSAMLSPAccessGroupsRow, error)
	ListSAMLSPKeys(ctx context.Context, arg ListSAMLSPKeysParams) ([]SamlSpKey, error)
	ListSAMLSPs(ctx context.Context) ([]SamlSp, error)
	ListSAMLSessionsByNameID(ctx context.Context, arg ListSAMLSessionsByNameIDParams) ([]SamlSession, error)
	ListSAMLSessionsBySession(ctx context.Context, sessionID string) ([]SamlSession, error)
	ListSessionsByAccount(ctx context.Context, accountID int32) ([]Session, error)
	ListUpstreamIDPs(ctx context.Context) ([]UpstreamIdp, error)
	PromoteSigningKey(ctx context.Context, kid string) (SigningKey, error)
	PruneExpiredRevokedJTI(ctx context.Context) error
	ReconcileRetiredSigningKeys(ctx context.Context) (int64, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error)
	ResetAuthThrottle(ctx context.Context, arg ResetAuthThrottleParams) error
	RetireSigningKey(ctx context.Context, arg RetireSigningKeyParams) (SigningKey, error)
	RevokeAllSessionsByAccount(ctx context.Context, accountID int32) error
	// Same DB effect as ConsumeEnrollment but intent-restricted to 'invite' so an
	// admin cannot accidentally use this to mark a bootstrap/reset token consumed.
	// Returns the row only if it was unconsumed AND of intent=invite; otherwise
	// pgx.ErrNoRows surfaces and the handler maps to invitation_not_found.
	RevokeInvitation(ctx context.Context, token string) (Enrollment, error)
	RevokeOIDCClientAccessAccount(ctx context.Context, arg RevokeOIDCClientAccessAccountParams) (int64, error)
	RevokeOIDCClientAccessGroup(ctx context.Context, arg RevokeOIDCClientAccessGroupParams) (int64, error)
	RevokeSAMLSPAccessAccount(ctx context.Context, arg RevokeSAMLSPAccessAccountParams) (int64, error)
	RevokeSAMLSPAccessGroup(ctx context.Context, arg RevokeSAMLSPAccessGroupParams) (int64, error)
	RevokeSession(ctx context.Context, id string) error
	SetAccountDisabled(ctx context.Context, arg SetAccountDisabledParams) (Account, error)
	// source is forced non-null text (the column is nullable, but this query only
	// ever sets a concrete sentinel) so callers cannot accidentally NULL the pointer.
	SetActiveAvatar(ctx context.Context, arg SetActiveAvatarParams) error
	SetCredentialCloneWarning(ctx context.Context, id int32) error
	SetEntityIcon(ctx context.Context, arg SetEntityIconParams) error
	SetEntityIconAccent(ctx context.Context, arg SetEntityIconAccentParams) error
	SetForwardAuthConfig(ctx context.Context, arg SetForwardAuthConfigParams) error
	SetOIDCClientAccessRestricted(ctx context.Context, arg SetOIDCClientAccessRestrictedParams) (OidcClient, error)
	SetOIDCClientDisabled(ctx context.Context, arg SetOIDCClientDisabledParams) (OidcClient, error)
	SetOIDCClientLaunchURL(ctx context.Context, arg SetOIDCClientLaunchURLParams) error
	SetSAMLSPAccessRestricted(ctx context.Context, arg SetSAMLSPAccessRestrictedParams) (SamlSp, error)
	SetSAMLSPDisabled(ctx context.Context, arg SetSAMLSPDisabledParams) (SamlSp, error)
	SetUpstreamIDPDisabled(ctx context.Context, arg SetUpstreamIDPDisabledParams) (UpstreamIdp, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error
	// Refreshes an account's email from a verified upstream on re-login (federation
	// claim drift), keeping it in lockstep with account_identity.upstream_email.
	UpdateAccountEmail(ctx context.Context, arg UpdateAccountEmailParams) error
	UpdateAccountIdentityEmail(ctx context.Context, arg UpdateAccountIdentityEmailParams) error
	UpdateCredentialUsage(ctx context.Context, arg UpdateCredentialUsageParams) error
	UpdateForwardAuthApp(ctx context.Context, arg UpdateForwardAuthAppParams) (UpdateForwardAuthAppRow, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UserGroup, error)
	// Owner-scoped update: only the account's own credential row is updated.
	// Zero rows affected means the id doesn't match an owned credential; the
	// handler then surfaces credential_not_found.
	UpdateMyCredentialNickname(ctx context.Context, arg UpdateMyCredentialNicknameParams) (int64, error)
	UpdateOIDCClient(ctx context.Context, arg UpdateOIDCClientParams) (OidcClient, error)
	UpdateOIDCClientSecret(ctx context.Context, arg UpdateOIDCClientSecretParams) error
	// Replace the stored hash WITHOUT touching password_changed_at — used by the
	// transparent argon2id param-upgrade rehash on a successful Verify (T4.3a). The
	// secret has not changed, so password_changed_at (which feeds password-age /
	// forced-reauth policy) must not move; only the at-rest encoding did.
	UpdatePasswordHashOnly(ctx context.Context, arg UpdatePasswordHashOnlyParams) error
	UpdateSAMLSP(ctx context.Context, arg UpdateSAMLSPParams) (SamlSp, error)
	// RFC 6238 §5.2: this UPDATE is the atomic gate that prevents a parallel
	// replay of the same code from issuing two sessions. The Go-side
	// `matchedStep <= row.LastStep` check short-circuits the common (serial)
	// replay; this WHERE guarantees that under K-way concurrency only one
	// caller's RETURNING row populates. The remaining racers see pgx.ErrNoRows
	// and the Verify path translates that to ErrTOTPReplay.
	UpdateTOTPLastStep(ctx context.Context, arg UpdateTOTPLastStepParams) (int64, error)
	UpdateUpstreamIDP(ctx context.Context, arg UpdateUpstreamIDPParams) error
	UpdateUpstreamIDPConfig(ctx context.Context, arg UpdateUpstreamIDPConfigParams) (UpstreamIdp, error)
	UpdateUpstreamIDPSecret(ctx context.Context, arg UpdateUpstreamIDPSecretParams) error
	// idp_id records the source upstream for an inherited avatar (NULL for a user
	// upload); source carries the upstream slug ("upstream:<slug>") so the
	// (account_id, source) PK yields one row per (account, upstream).
	UpsertAvatarSource(ctx context.Context, arg UpsertAvatarSourceParams) error
	UpsertConsent(ctx context.Context, arg UpsertConsentParams) error
	UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error
	UpsertSAMLConsent(ctx context.Context, arg UpsertSAMLConsentParams) error
}

var _ Querier = (*Queries)(nil)
