// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	//
	// Atomic increment + lockout-from-just-incremented-count. The previous
	// read-then-UPSERT path lost increments under K-way concurrency (K callers
	// all read the same prior count, then last-write-wins clobbered to count+1)
	// and worse, picked the lockout duration off the racing snapshot rather than
	// the post-increment value. This single round-trip carries the full
	// exponential-backoff schedule as a bigint[] of microsecond durations; the
	// CASE clauses index into it using auth_throttle.failed_attempts + 1, which
	// Postgres evaluates against the just-incremented row.
	//
	// $3 layout: schedule[i] is the lockout duration (in microseconds) applied
	// on the i-th failure (1-indexed). 0 means "no lockout yet — still in the
	// free-attempt prefix". Indexing past the array clamps to the last entry,
	// matching the Go-side schedule-walk semantics.
	BumpAuthThrottle(ctx context.Context, arg BumpAuthThrottleParams) (BumpAuthThrottleRow, error)
	ConfirmTOTPCredential(ctx context.Context, accountID int32) error
	// Atomic single-use consume. Returns the row only if it was unconsumed and unexpired.
	// Callers detect any "not consumable" branch via pgx.ErrNoRows.
	ConsumeEnrollment(ctx context.Context, token string) (Enrollment, error)
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (RecoveryCode, error)
	CountActiveAdminsForUpdate(ctx context.Context) (int64, error)
	CountCredentialsByAccount(ctx context.Context, accountID int32) (int64, error)
	DeactivateSigningKeys(ctx context.Context) error
	DeleteAccountByID(ctx context.Context, id int32) error
	// Returns the deleted row's id when one matched; pgx.ErrNoRows when the
	// (id, account_id) pair matches nothing (foreign identity, already-
	// deleted, or unknown id). Callers map ErrNoRows to a 404 + skip audit.
	DeleteAccountIdentity(ctx context.Context, arg DeleteAccountIdentityParams) (int64, error)
	DeleteAllCredentialsForAccount(ctx context.Context, accountID int32) error
	DeleteAllRecoveryCodesByAccount(ctx context.Context, accountID int32) error
	DeleteConsent(ctx context.Context, arg DeleteConsentParams) error
	// Owner-scoped delete: zero rows affected means the id doesn't match an owned
	// credential; handlers map that to credential_not_found.
	DeleteCredentialByID(ctx context.Context, arg DeleteCredentialByIDParams) (int64, error)
	DeleteExpiredSAMLSessions(ctx context.Context) (int64, error)
	DeletePasswordCredential(ctx context.Context, accountID int32) error
	DeleteSAMLSessionsBySession(ctx context.Context, sessionID string) error
	DeleteTOTPCredential(ctx context.Context, accountID int32) error
	DeleteUpstreamIDP(ctx context.Context, id int64) error
	GetAccountByID(ctx context.Context, id int32) (Account, error)
	GetAccountByIDForUpdate(ctx context.Context, id int32) (Account, error)
	GetAccountByOIDCSubject(ctx context.Context, oidcSubject pgtype.UUID) (Account, error)
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
	GetAccountByWebauthnUserHandle(ctx context.Context, webauthnUserHandle []byte) (Account, error)
	GetAccountIdentityByIssuerSub(ctx context.Context, arg GetAccountIdentityByIssuerSubParams) (AccountIdentity, error)
	GetActiveSigningKey(ctx context.Context) (SigningKey, error)
	GetAuthThrottle(ctx context.Context, arg GetAuthThrottleParams) (AuthThrottle, error)
	GetConsent(ctx context.Context, arg GetConsentParams) ([]string, error)
	GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error)
	GetEnrollmentByToken(ctx context.Context, token string) (Enrollment, error)
	GetOIDCClient(ctx context.Context, clientID string) (OidcClient, error)
	GetPasswordCredential(ctx context.Context, accountID int32) (PasswordCredential, error)
	GetSAMLSPByEntityID(ctx context.Context, entityID string) (SamlSp, error)
	GetSAMLSPByID(ctx context.Context, id int64) (SamlSp, error)
	GetSAMLSubjectID(ctx context.Context, arg GetSAMLSubjectIDParams) (SamlSubjectID, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetTOTPCredential(ctx context.Context, accountID int32) (TotpCredential, error)
	GetUpstreamIDPBySlug(ctx context.Context, slug string) (UpstreamIdp, error)
	HasAnyActiveAdmin(ctx context.Context) (bool, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error)
	InsertAccountIdentity(ctx context.Context, arg InsertAccountIdentityParams) (AccountIdentity, error)
	InsertCredential(ctx context.Context, arg InsertCredentialParams) (WebauthnCredential, error)
	InsertCredentialEvent(ctx context.Context, arg InsertCredentialEventParams) error
	InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error)
	InsertOIDCClient(ctx context.Context, arg InsertOIDCClientParams) (OidcClient, error)
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) (RecoveryCode, error)
	InsertRevokedJTI(ctx context.Context, arg InsertRevokedJTIParams) error
	InsertSAMLSP(ctx context.Context, arg InsertSAMLSPParams) (SamlSp, error)
	InsertSAMLSPACS(ctx context.Context, arg InsertSAMLSPACSParams) error
	InsertSAMLSPKey(ctx context.Context, arg InsertSAMLSPKeyParams) error
	InsertSAMLSession(ctx context.Context, arg InsertSAMLSessionParams) (SamlSession, error)
	InsertSAMLSubjectID(ctx context.Context, arg InsertSAMLSubjectIDParams) (SamlSubjectID, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error)
	InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) (SigningKey, error)
	InsertTOTPCredential(ctx context.Context, arg InsertTOTPCredentialParams) (TotpCredential, error)
	InsertUpstreamIDP(ctx context.Context, arg InsertUpstreamIDPParams) (UpstreamIdp, error)
	IsJTIRevoked(ctx context.Context, jti string) (bool, error)
	ListAccountIdentitiesByAccount(ctx context.Context, accountID int32) ([]ListAccountIdentitiesByAccountRow, error)
	ListAccounts(ctx context.Context) ([]ListAccountsRow, error)
	ListActiveSigningKeys(ctx context.Context) ([]SigningKey, error)
	ListCredentialEventsByAccount(ctx context.Context, arg ListCredentialEventsByAccountParams) ([]CredentialEvent, error)
	ListCredentialEventsByFactor(ctx context.Context, arg ListCredentialEventsByFactorParams) ([]CredentialEvent, error)
	ListCredentialsByAccount(ctx context.Context, accountID int32) ([]WebauthnCredential, error)
	ListOIDCClients(ctx context.Context) ([]ListOIDCClientsRow, error)
	ListPendingInvitations(ctx context.Context) ([]Enrollment, error)
	ListRecoveryCodesByAccount(ctx context.Context, accountID int32) ([]RecoveryCode, error)
	ListSAMLSPACSEndpoints(ctx context.Context, spID int64) ([]SamlSpAc, error)
	ListSAMLSPKeys(ctx context.Context, arg ListSAMLSPKeysParams) ([]SamlSpKey, error)
	ListSAMLSPs(ctx context.Context) ([]SamlSp, error)
	ListSAMLSessionsByNameID(ctx context.Context, arg ListSAMLSessionsByNameIDParams) ([]SamlSession, error)
	ListSAMLSessionsBySession(ctx context.Context, sessionID string) ([]SamlSession, error)
	ListSessionsByAccount(ctx context.Context, accountID int32) ([]Session, error)
	ListUpstreamIDPs(ctx context.Context) ([]UpstreamIdp, error)
	PruneExpiredRevokedJTI(ctx context.Context) error
	ResetAuthThrottle(ctx context.Context, arg ResetAuthThrottleParams) error
	RetireSigningKey(ctx context.Context, kid string) error
	RevokeAllSessionsByAccount(ctx context.Context, accountID int32) error
	// Same DB effect as ConsumeEnrollment but intent-restricted to 'invite' so an
	// admin cannot accidentally use this to mark a bootstrap/reset token consumed.
	// Returns the row only if it was unconsumed AND of intent=invite; otherwise
	// pgx.ErrNoRows surfaces and the handler maps to invitation_not_found.
	RevokeInvitation(ctx context.Context, token string) (Enrollment, error)
	RevokeSession(ctx context.Context, id string) error
	SetCredentialCloneWarning(ctx context.Context, id int32) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error
	UpdateAccountIdentityEmail(ctx context.Context, arg UpdateAccountIdentityEmailParams) error
	UpdateCredentialUsage(ctx context.Context, arg UpdateCredentialUsageParams) error
	// Owner-scoped update: only the account's own credential row is updated.
	// Zero rows affected means the id doesn't match an owned credential; the
	// handler then surfaces credential_not_found.
	UpdateMyCredentialNickname(ctx context.Context, arg UpdateMyCredentialNicknameParams) (int64, error)
	// RFC 6238 §5.2: this UPDATE is the atomic gate that prevents a parallel
	// replay of the same code from issuing two sessions. The Go-side
	// `matchedStep <= row.LastStep` check short-circuits the common (serial)
	// replay; this WHERE guarantees that under K-way concurrency only one
	// caller's RETURNING row populates. The remaining racers see pgx.ErrNoRows
	// and the Verify path translates that to ErrTOTPReplay.
	UpdateTOTPLastStep(ctx context.Context, arg UpdateTOTPLastStepParams) (int64, error)
	UpdateUpstreamIDP(ctx context.Context, arg UpdateUpstreamIDPParams) error
	UpsertConsent(ctx context.Context, arg UpsertConsentParams) error
	UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error
}

var _ Querier = (*Queries)(nil)
