// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Atomic single-use consume. Returns the row only if it was unconsumed and unexpired.
	// Callers detect any "not consumable" branch via pgx.ErrNoRows.
	ConsumeEnrollment(ctx context.Context, token string) (Enrollment, error)
	CountActiveAdminsForUpdate(ctx context.Context) (int64, error)
	CountCredentialsByAccount(ctx context.Context, accountID int32) (int64, error)
	DeactivateAllSigningKeys(ctx context.Context) error
	DeleteAccountByID(ctx context.Context, id int32) error
	DeleteAllCredentialsForAccount(ctx context.Context, accountID int32) error
	// Owner-scoped delete: zero rows affected means the id doesn't match an owned
	// credential; handlers map that to credential_not_found.
	DeleteCredentialByID(ctx context.Context, arg DeleteCredentialByIDParams) (int64, error)
	DeleteOIDCClient(ctx context.Context, clientID string) error
	GetAccountByID(ctx context.Context, id int32) (Account, error)
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
	GetAccountByWebauthnUserHandle(ctx context.Context, webauthnUserHandle []byte) (Account, error)
	GetActiveSigningKey(ctx context.Context) (OidcSigningKey, error)
	GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error)
	GetEnrollmentByToken(ctx context.Context, token string) (Enrollment, error)
	GetOIDCClient(ctx context.Context, clientID string) (OidcClient, error)
	HasAnyActiveAdmin(ctx context.Context) (bool, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error)
	InsertCredential(ctx context.Context, arg InsertCredentialParams) (WebauthnCredential, error)
	// template_username ($11) and template_display_name ($12) are always NULL
	// as of P5.03 — the invite flow no longer pre-populates username/displayName.
	InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error)
	InsertOIDCClient(ctx context.Context, arg InsertOIDCClientParams) (OidcClient, error)
	InsertSigningKey(ctx context.Context, arg InsertSigningKeyParams) (OidcSigningKey, error)
	ListAccounts(ctx context.Context) ([]ListAccountsRow, error)
	ListCredentialsByAccount(ctx context.Context, accountID int32) ([]WebauthnCredential, error)
	ListOIDCClients(ctx context.Context) ([]OidcClient, error)
	ListPendingInvitations(ctx context.Context) ([]Enrollment, error)
	// Every non-retired key: the active signing key + any keys still inside
	// their rollover window. JWKS endpoint serves the public_jwk of each.
	ListVerifyingSigningKeys(ctx context.Context) ([]OidcSigningKey, error)
	RetireSigningKey(ctx context.Context, arg RetireSigningKeyParams) error
	// Same DB effect as ConsumeEnrollment but intent-restricted to 'invite' so an
	// admin cannot accidentally use this to mark a bootstrap/reset token consumed.
	// Returns the row only if it was unconsumed AND of intent=invite; otherwise
	// pgx.ErrNoRows surfaces and the handler maps to invitation_not_found.
	RevokeInvitation(ctx context.Context, token string) (Enrollment, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCredentialUsage(ctx context.Context, arg UpdateCredentialUsageParams) error
	// Owner-scoped update: only the account's own credential row is updated.
	// Zero rows affected means the id doesn't match an owned credential; the
	// handler then surfaces credential_not_found.
	UpdateMyCredentialNickname(ctx context.Context, arg UpdateMyCredentialNicknameParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
