// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_member (group_id, account_id)
VALUES ($1, $2)
ON CONFLICT (group_id, account_id) DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID   int32 `json:"groupId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.AccountID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO user_group (slug, display_name, description, exposed_to_downstream)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, display_name, description, exposed_to_downstream, created_at, updated_at
`

type CreateGroupParams struct {
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM user_group WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, slug, display_name, description, exposed_to_downstream, created_at, updated_at FROM user_group WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id int32) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupBySlug = `-- name: GetGroupBySlug :one
SELECT id, slug, display_name, description, exposed_to_downstream, created_at, updated_at FROM user_group WHERE slug = $1
`

func (q *Queries) GetGroupBySlug(ctx context.Context, slug string) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getGroupBySlug, slug)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantOIDCClientAccessAccount = `-- name: GrantOIDCClientAccessAccount :exec
INSERT INTO oidc_client_access (client_id, account_id) VALUES ($1, $2)
ON CONFLICT (client_id, account_id) WHERE account_id IS NOT NULL DO NOTHING
`

type GrantOIDCClientAccessAccountParams struct {
	ClientID  string      `json:"clientId"`
	AccountID pgtype.Int4 `json:"accountId"`
}

func (q *Queries) GrantOIDCClientAccessAccount(ctx context.Context, arg GrantOIDCClientAccessAccountParams) error {
	_, err := q.db.Exec(ctx, grantOIDCClientAccessAccount, arg.ClientID, arg.AccountID)
	return err
}

const grantOIDCClientAccessGroup = `-- name: GrantOIDCClientAccessGroup :exec
INSERT INTO oidc_client_access (client_id, group_id) VALUES ($1, $2)
ON CONFLICT (client_id, group_id) WHERE group_id IS NOT NULL DO NOTHING
`

type GrantOIDCClientAccessGroupParams struct {
	ClientID string      `json:"clientId"`
	GroupID  pgtype.Int4 `json:"groupId"`
}

func (q *Queries) GrantOIDCClientAccessGroup(ctx context.Context, arg GrantOIDCClientAccessGroupParams) error {
	_, err := q.db.Exec(ctx, grantOIDCClientAccessGroup, arg.ClientID, arg.GroupID)
	return err
}

const grantSAMLSPAccessAccount = `-- name: GrantSAMLSPAccessAccount :exec
INSERT INTO saml_sp_access (saml_sp_id, account_id) VALUES ($1, $2)
ON CONFLICT (saml_sp_id, account_id) WHERE account_id IS NOT NULL DO NOTHING
`

type GrantSAMLSPAccessAccountParams struct {
	SamlSpID  int64       `json:"samlSpId"`
	AccountID pgtype.Int4 `json:"accountId"`
}

func (q *Queries) GrantSAMLSPAccessAccount(ctx context.Context, arg GrantSAMLSPAccessAccountParams) error {
	_, err := q.db.Exec(ctx, grantSAMLSPAccessAccount, arg.SamlSpID, arg.AccountID)
	return err
}

const grantSAMLSPAccessGroup = `-- name: GrantSAMLSPAccessGroup :exec
INSERT INTO saml_sp_access (saml_sp_id, group_id) VALUES ($1, $2)
ON CONFLICT (saml_sp_id, group_id) WHERE group_id IS NOT NULL DO NOTHING
`

type GrantSAMLSPAccessGroupParams struct {
	SamlSpID int64       `json:"samlSpId"`
	GroupID  pgtype.Int4 `json:"groupId"`
}

func (q *Queries) GrantSAMLSPAccessGroup(ctx context.Context, arg GrantSAMLSPAccessGroupParams) error {
	_, err := q.db.Exec(ctx, grantSAMLSPAccessGroup, arg.SamlSpID, arg.GroupID)
	return err
}

const isAccountAuthorizedForOIDCClient = `-- name: IsAccountAuthorizedForOIDCClient :one
SELECT
  NOT c.access_restricted
  OR EXISTS (SELECT 1 FROM oidc_client_access a
             WHERE a.client_id = c.client_id AND a.account_id = $1)
  OR EXISTS (SELECT 1 FROM oidc_client_access a
             JOIN group_member m ON m.group_id = a.group_id
             WHERE a.client_id = c.client_id AND m.account_id = $1)
FROM oidc_client c
WHERE c.client_id = $2
`

type IsAccountAuthorizedForOIDCClientParams struct {
	AccountID pgtype.Int4 `json:"accountId"`
	ClientID  string      `json:"clientId"`
}

func (q *Queries) IsAccountAuthorizedForOIDCClient(ctx context.Context, arg IsAccountAuthorizedForOIDCClientParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isAccountAuthorizedForOIDCClient, arg.AccountID, arg.ClientID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isAccountAuthorizedForSAMLSP = `-- name: IsAccountAuthorizedForSAMLSP :one
SELECT
  NOT s.access_restricted
  OR EXISTS (SELECT 1 FROM saml_sp_access a
             WHERE a.saml_sp_id = s.id AND a.account_id = $1)
  OR EXISTS (SELECT 1 FROM saml_sp_access a
             JOIN group_member m ON m.group_id = a.group_id
             WHERE a.saml_sp_id = s.id AND m.account_id = $1)
FROM saml_sp s
WHERE s.id = $2
`

type IsAccountAuthorizedForSAMLSPParams struct {
	AccountID pgtype.Int4 `json:"accountId"`
	SpID      int64       `json:"spId"`
}

func (q *Queries) IsAccountAuthorizedForSAMLSP(ctx context.Context, arg IsAccountAuthorizedForSAMLSPParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isAccountAuthorizedForSAMLSP, arg.AccountID, arg.SpID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAuthorizedForwardAuthAppsForAccount = `-- name: ListAuthorizedForwardAuthAppsForAccount :many
SELECT c.client_id, c.display_name, c.forward_auth_host, c.forward_auth_scopes
FROM oidc_client c
WHERE c.disabled = false
  AND c.forward_auth_enabled = true
  AND c.forward_auth_host IS NOT NULL
  AND (
    NOT c.access_restricted
    OR EXISTS (SELECT 1 FROM oidc_client_access a
               WHERE a.client_id = c.client_id AND a.account_id = $1)
    OR EXISTS (SELECT 1 FROM oidc_client_access a
               JOIN group_member m ON m.group_id = a.group_id
               WHERE a.client_id = c.client_id AND m.account_id = $1)
  )
ORDER BY c.display_name
`

type ListAuthorizedForwardAuthAppsForAccountRow struct {
	ClientID          string      `json:"clientId"`
	DisplayName       string      `json:"displayName"`
	ForwardAuthHost   pgtype.Text `json:"forwardAuthHost"`
	ForwardAuthScopes []byte      `json:"forwardAuthScopes"`
}

func (q *Queries) ListAuthorizedForwardAuthAppsForAccount(ctx context.Context, accountID pgtype.Int4) ([]ListAuthorizedForwardAuthAppsForAccountRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizedForwardAuthAppsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizedForwardAuthAppsForAccountRow
	for rows.Next() {
		var i ListAuthorizedForwardAuthAppsForAccountRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.ForwardAuthHost,
			&i.ForwardAuthScopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorizedOIDCClientsForAccount = `-- name: ListAuthorizedOIDCClientsForAccount :many
SELECT c.client_id, c.display_name, c.launch_url, c.redirect_uris
FROM oidc_client c
WHERE c.disabled = false
  AND c.forward_auth_enabled = false
  AND (
    NOT c.access_restricted
    OR EXISTS (SELECT 1 FROM oidc_client_access a
               WHERE a.client_id = c.client_id AND a.account_id = $1)
    OR EXISTS (SELECT 1 FROM oidc_client_access a
               JOIN group_member m ON m.group_id = a.group_id
               WHERE a.client_id = c.client_id AND m.account_id = $1)
  )
ORDER BY c.display_name
`

type ListAuthorizedOIDCClientsForAccountRow struct {
	ClientID     string      `json:"clientId"`
	DisplayName  string      `json:"displayName"`
	LaunchUrl    pgtype.Text `json:"launchUrl"`
	RedirectUris []string    `json:"redirectUris"`
}

func (q *Queries) ListAuthorizedOIDCClientsForAccount(ctx context.Context, accountID pgtype.Int4) ([]ListAuthorizedOIDCClientsForAccountRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizedOIDCClientsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizedOIDCClientsForAccountRow
	for rows.Next() {
		var i ListAuthorizedOIDCClientsForAccountRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.LaunchUrl,
			&i.RedirectUris,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorizedSAMLSPsForAccount = `-- name: ListAuthorizedSAMLSPsForAccount :many
SELECT s.id, s.entity_id, s.display_name
FROM saml_sp s
WHERE s.disabled = false
  AND s.allow_idp_initiated = true
  AND (
    NOT s.access_restricted
    OR EXISTS (SELECT 1 FROM saml_sp_access a
               WHERE a.saml_sp_id = s.id AND a.account_id = $1)
    OR EXISTS (SELECT 1 FROM saml_sp_access a
               JOIN group_member m ON m.group_id = a.group_id
               WHERE a.saml_sp_id = s.id AND m.account_id = $1)
  )
ORDER BY s.display_name
`

type ListAuthorizedSAMLSPsForAccountRow struct {
	ID          int64  `json:"id"`
	EntityID    string `json:"entityId"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) ListAuthorizedSAMLSPsForAccount(ctx context.Context, accountID pgtype.Int4) ([]ListAuthorizedSAMLSPsForAccountRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizedSAMLSPsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizedSAMLSPsForAccountRow
	for rows.Next() {
		var i ListAuthorizedSAMLSPsForAccountRow
		if err := rows.Scan(&i.ID, &i.EntityID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExposedGroupSlugsByAccount = `-- name: ListExposedGroupSlugsByAccount :many
SELECT g.slug
FROM group_member m
JOIN user_group g ON g.id = m.group_id
WHERE m.account_id = $1 AND g.exposed_to_downstream
ORDER BY g.slug
`

func (q *Queries) ListExposedGroupSlugsByAccount(ctx context.Context, accountID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listExposedGroupSlugsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT a.id, a.username, a.display_name
FROM group_member m
JOIN account a ON a.id = m.account_id
WHERE m.group_id = $1
ORDER BY a.username
`

type ListGroupMembersRow struct {
	ID          int32  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID int32) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembersPage = `-- name: ListGroupMembersPage :many
SELECT a.id, a.username, a.display_name
FROM group_member m
JOIN account a ON a.id = m.account_id
WHERE m.group_id = $1
  AND ($2::text IS NULL OR (a.username, a.id) > ($2, $3::int4))
ORDER BY a.username ASC, a.id ASC
LIMIT $4
`

type ListGroupMembersPageParams struct {
	GroupID        int32  `json:"groupId"`
	AfterUsername  string `json:"afterUsername"`
	AfterAccountID int32  `json:"afterAccountId"`
	RowLimit       int32  `json:"rowLimit"`
}

type ListGroupMembersPageRow struct {
	ID          int32  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
}

// Keyset-paginated group members, ordered by (username ASC, account_id ASC).
// NULL after_username starts a new page. LIMIT is limit+1 for next-page detection.
func (q *Queries) ListGroupMembersPage(ctx context.Context, arg ListGroupMembersPageParams) ([]ListGroupMembersPageRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembersPage,
		arg.GroupID,
		arg.AfterUsername,
		arg.AfterAccountID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersPageRow
	for rows.Next() {
		var i ListGroupMembersPageRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.created_at, g.updated_at, (SELECT count(*) FROM group_member m WHERE m.group_id = g.id) AS member_count
FROM user_group g
WHERE ($1::timestamptz IS NULL OR (g.created_at, g.id) < ($1, $2::int4))
ORDER BY g.created_at DESC, g.id DESC
LIMIT $3
`

type ListGroupsParams struct {
	AfterCreatedAt pgtype.Timestamptz `json:"afterCreatedAt"`
	AfterID        pgtype.Int4        `json:"afterId"`
	Limit          int32              `json:"limit"`
}

type ListGroupsRow struct {
	ID                  int32              `json:"id"`
	Slug                string             `json:"slug"`
	DisplayName         string             `json:"displayName"`
	Description         pgtype.Text        `json:"description"`
	ExposedToDownstream bool               `json:"exposedToDownstream"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
	MemberCount         int64              `json:"memberCount"`
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.AfterCreatedAt, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForAccount = `-- name: ListGroupsForAccount :many
SELECT g.id, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.created_at, g.updated_at
FROM group_member m
JOIN user_group g ON g.id = m.group_id
WHERE m.account_id = $1
ORDER BY g.display_name
`

func (q *Queries) ListGroupsForAccount(ctx context.Context, accountID int32) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForAccountPage = `-- name: ListGroupsForAccountPage :many
SELECT g.id, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.created_at, g.updated_at
FROM group_member m
JOIN user_group g ON g.id = m.group_id
WHERE m.account_id = $1
  AND ($2::text IS NULL OR (g.display_name, g.id) > ($2, $3::int4))
ORDER BY g.display_name ASC, g.id ASC
LIMIT $4
`

type ListGroupsForAccountPageParams struct {
	AccountID        int32  `json:"accountId"`
	AfterDisplayName string `json:"afterDisplayName"`
	AfterGroupID     int32  `json:"afterGroupId"`
	RowLimit         int32  `json:"rowLimit"`
}

// Keyset-paginated groups for an account, ordered by (display_name ASC, id ASC).
// NULL after_display_name starts a new page. LIMIT is limit+1 for next-page detection.
func (q *Queries) ListGroupsForAccountPage(ctx context.Context, arg ListGroupsForAccountPageParams) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listGroupsForAccountPage,
		arg.AccountID,
		arg.AfterDisplayName,
		arg.AfterGroupID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientAccessAccounts = `-- name: ListOIDCClientAccessAccounts :many
SELECT acc.id, acc.username, acc.display_name
FROM oidc_client_access a JOIN account acc ON acc.id = a.account_id
WHERE a.client_id = $1 ORDER BY acc.username
`

type ListOIDCClientAccessAccountsRow struct {
	ID          int32  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) ListOIDCClientAccessAccounts(ctx context.Context, clientID string) ([]ListOIDCClientAccessAccountsRow, error) {
	rows, err := q.db.Query(ctx, listOIDCClientAccessAccounts, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCClientAccessAccountsRow
	for rows.Next() {
		var i ListOIDCClientAccessAccountsRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientAccessAccountsPage = `-- name: ListOIDCClientAccessAccountsPage :many
SELECT acc.id, acc.username, acc.display_name
FROM oidc_client_access a JOIN account acc ON acc.id = a.account_id
WHERE a.client_id = $1
  AND ($2::text IS NULL OR (acc.username, acc.id) > ($2, $3::int4))
ORDER BY acc.username ASC, acc.id ASC
LIMIT $4
`

type ListOIDCClientAccessAccountsPageParams struct {
	ClientID       string `json:"clientId"`
	AfterUsername  string `json:"afterUsername"`
	AfterAccountID int32  `json:"afterAccountId"`
	RowLimit       int32  `json:"rowLimit"`
}

type ListOIDCClientAccessAccountsPageRow struct {
	ID          int32  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
}

// Keyset-paginated access accounts for an OIDC client, ordered by (username ASC, id ASC).
func (q *Queries) ListOIDCClientAccessAccountsPage(ctx context.Context, arg ListOIDCClientAccessAccountsPageParams) ([]ListOIDCClientAccessAccountsPageRow, error) {
	rows, err := q.db.Query(ctx, listOIDCClientAccessAccountsPage,
		arg.ClientID,
		arg.AfterUsername,
		arg.AfterAccountID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCClientAccessAccountsPageRow
	for rows.Next() {
		var i ListOIDCClientAccessAccountsPageRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientAccessGroups = `-- name: ListOIDCClientAccessGroups :many
SELECT g.id, g.slug, g.display_name
FROM oidc_client_access a JOIN user_group g ON g.id = a.group_id
WHERE a.client_id = $1 ORDER BY g.display_name
`

type ListOIDCClientAccessGroupsRow struct {
	ID          int32  `json:"id"`
	Slug        string `json:"slug"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) ListOIDCClientAccessGroups(ctx context.Context, clientID string) ([]ListOIDCClientAccessGroupsRow, error) {
	rows, err := q.db.Query(ctx, listOIDCClientAccessGroups, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCClientAccessGroupsRow
	for rows.Next() {
		var i ListOIDCClientAccessGroupsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientAccessGroupsPage = `-- name: ListOIDCClientAccessGroupsPage :many
SELECT g.id, g.slug, g.display_name
FROM oidc_client_access a JOIN user_group g ON g.id = a.group_id
WHERE a.client_id = $1
  AND ($2::text IS NULL OR (g.display_name, g.id) > ($2, $3::int4))
ORDER BY g.display_name ASC, g.id ASC
LIMIT $4
`

type ListOIDCClientAccessGroupsPageParams struct {
	ClientID         string `json:"clientId"`
	AfterDisplayName string `json:"afterDisplayName"`
	AfterGroupID     int32  `json:"afterGroupId"`
	RowLimit         int32  `json:"rowLimit"`
}

type ListOIDCClientAccessGroupsPageRow struct {
	ID          int32  `json:"id"`
	Slug        string `json:"slug"`
	DisplayName string `json:"displayName"`
}

// Keyset-paginated access groups for an OIDC client, ordered by (display_name ASC, id ASC).
func (q *Queries) ListOIDCClientAccessGroupsPage(ctx context.Context, arg ListOIDCClientAccessGroupsPageParams) ([]ListOIDCClientAccessGroupsPageRow, error) {
	rows, err := q.db.Query(ctx, listOIDCClientAccessGroupsPage,
		arg.ClientID,
		arg.AfterDisplayName,
		arg.AfterGroupID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCClientAccessGroupsPageRow
	for rows.Next() {
		var i ListOIDCClientAccessGroupsPageRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPAccessAccounts = `-- name: ListSAMLSPAccessAccounts :many
SELECT acc.id, acc.username, acc.display_name
FROM saml_sp_access a JOIN account acc ON acc.id = a.account_id
WHERE a.saml_sp_id = $1 ORDER BY acc.username
`

type ListSAMLSPAccessAccountsRow struct {
	ID          int32  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) ListSAMLSPAccessAccounts(ctx context.Context, samlSpID int64) ([]ListSAMLSPAccessAccountsRow, error) {
	rows, err := q.db.Query(ctx, listSAMLSPAccessAccounts, samlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLSPAccessAccountsRow
	for rows.Next() {
		var i ListSAMLSPAccessAccountsRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPAccessAccountsPage = `-- name: ListSAMLSPAccessAccountsPage :many
SELECT acc.id, acc.username, acc.display_name
FROM saml_sp_access a JOIN account acc ON acc.id = a.account_id
WHERE a.saml_sp_id = $1
  AND ($2::text IS NULL OR (acc.username, acc.id) > ($2, $3::int4))
ORDER BY acc.username ASC, acc.id ASC
LIMIT $4
`

type ListSAMLSPAccessAccountsPageParams struct {
	SamlSpID       int64  `json:"samlSpId"`
	AfterUsername  string `json:"afterUsername"`
	AfterAccountID int32  `json:"afterAccountId"`
	RowLimit       int32  `json:"rowLimit"`
}

type ListSAMLSPAccessAccountsPageRow struct {
	ID          int32  `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
}

// Keyset-paginated access accounts for a SAML SP, ordered by (username ASC, id ASC).
func (q *Queries) ListSAMLSPAccessAccountsPage(ctx context.Context, arg ListSAMLSPAccessAccountsPageParams) ([]ListSAMLSPAccessAccountsPageRow, error) {
	rows, err := q.db.Query(ctx, listSAMLSPAccessAccountsPage,
		arg.SamlSpID,
		arg.AfterUsername,
		arg.AfterAccountID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLSPAccessAccountsPageRow
	for rows.Next() {
		var i ListSAMLSPAccessAccountsPageRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPAccessGroups = `-- name: ListSAMLSPAccessGroups :many
SELECT g.id, g.slug, g.display_name
FROM saml_sp_access a JOIN user_group g ON g.id = a.group_id
WHERE a.saml_sp_id = $1 ORDER BY g.display_name
`

type ListSAMLSPAccessGroupsRow struct {
	ID          int32  `json:"id"`
	Slug        string `json:"slug"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) ListSAMLSPAccessGroups(ctx context.Context, samlSpID int64) ([]ListSAMLSPAccessGroupsRow, error) {
	rows, err := q.db.Query(ctx, listSAMLSPAccessGroups, samlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLSPAccessGroupsRow
	for rows.Next() {
		var i ListSAMLSPAccessGroupsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPAccessGroupsPage = `-- name: ListSAMLSPAccessGroupsPage :many
SELECT g.id, g.slug, g.display_name
FROM saml_sp_access a JOIN user_group g ON g.id = a.group_id
WHERE a.saml_sp_id = $1
  AND ($2::text IS NULL OR (g.display_name, g.id) > ($2, $3::int4))
ORDER BY g.display_name ASC, g.id ASC
LIMIT $4
`

type ListSAMLSPAccessGroupsPageParams struct {
	SamlSpID         int64  `json:"samlSpId"`
	AfterDisplayName string `json:"afterDisplayName"`
	AfterGroupID     int32  `json:"afterGroupId"`
	RowLimit         int32  `json:"rowLimit"`
}

type ListSAMLSPAccessGroupsPageRow struct {
	ID          int32  `json:"id"`
	Slug        string `json:"slug"`
	DisplayName string `json:"displayName"`
}

// Keyset-paginated access groups for a SAML SP, ordered by (display_name ASC, id ASC).
func (q *Queries) ListSAMLSPAccessGroupsPage(ctx context.Context, arg ListSAMLSPAccessGroupsPageParams) ([]ListSAMLSPAccessGroupsPageRow, error) {
	rows, err := q.db.Query(ctx, listSAMLSPAccessGroupsPage,
		arg.SamlSpID,
		arg.AfterDisplayName,
		arg.AfterGroupID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLSPAccessGroupsPageRow
	for rows.Next() {
		var i ListSAMLSPAccessGroupsPageRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM group_member WHERE group_id = $1 AND account_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID   int32 `json:"groupId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOIDCClientAccessAccount = `-- name: RevokeOIDCClientAccessAccount :execrows
DELETE FROM oidc_client_access WHERE client_id = $1 AND account_id = $2
`

type RevokeOIDCClientAccessAccountParams struct {
	ClientID  string      `json:"clientId"`
	AccountID pgtype.Int4 `json:"accountId"`
}

func (q *Queries) RevokeOIDCClientAccessAccount(ctx context.Context, arg RevokeOIDCClientAccessAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOIDCClientAccessAccount, arg.ClientID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOIDCClientAccessGroup = `-- name: RevokeOIDCClientAccessGroup :execrows
DELETE FROM oidc_client_access WHERE client_id = $1 AND group_id = $2
`

type RevokeOIDCClientAccessGroupParams struct {
	ClientID string      `json:"clientId"`
	GroupID  pgtype.Int4 `json:"groupId"`
}

func (q *Queries) RevokeOIDCClientAccessGroup(ctx context.Context, arg RevokeOIDCClientAccessGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOIDCClientAccessGroup, arg.ClientID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSAMLSPAccessAccount = `-- name: RevokeSAMLSPAccessAccount :execrows
DELETE FROM saml_sp_access WHERE saml_sp_id = $1 AND account_id = $2
`

type RevokeSAMLSPAccessAccountParams struct {
	SamlSpID  int64       `json:"samlSpId"`
	AccountID pgtype.Int4 `json:"accountId"`
}

func (q *Queries) RevokeSAMLSPAccessAccount(ctx context.Context, arg RevokeSAMLSPAccessAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSAMLSPAccessAccount, arg.SamlSpID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSAMLSPAccessGroup = `-- name: RevokeSAMLSPAccessGroup :execrows
DELETE FROM saml_sp_access WHERE saml_sp_id = $1 AND group_id = $2
`

type RevokeSAMLSPAccessGroupParams struct {
	SamlSpID int64       `json:"samlSpId"`
	GroupID  pgtype.Int4 `json:"groupId"`
}

func (q *Queries) RevokeSAMLSPAccessGroup(ctx context.Context, arg RevokeSAMLSPAccessGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSAMLSPAccessGroup, arg.SamlSpID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOIDCClientAccessRestricted = `-- name: SetOIDCClientAccessRestricted :one
UPDATE oidc_client SET access_restricted = $2 WHERE client_id = $1 RETURNING client_id, display_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, allowed_scopes, require_pkce, allowed_code_challenge_methods, token_endpoint_auth_method, subject_type, logo_uri, tos_uri, policy_uri, disabled, require_consent, created_at, access_restricted, forward_auth_enabled, forward_auth_host, forward_auth_scopes, launch_url
`

type SetOIDCClientAccessRestrictedParams struct {
	ClientID         string `json:"clientId"`
	AccessRestricted bool   `json:"accessRestricted"`
}

func (q *Queries) SetOIDCClientAccessRestricted(ctx context.Context, arg SetOIDCClientAccessRestrictedParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, setOIDCClientAccessRestricted, arg.ClientID, arg.AccessRestricted)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.DisplayName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.AllowedScopes,
		&i.RequirePkce,
		&i.AllowedCodeChallengeMethods,
		&i.TokenEndpointAuthMethod,
		&i.SubjectType,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Disabled,
		&i.RequireConsent,
		&i.CreatedAt,
		&i.AccessRestricted,
		&i.ForwardAuthEnabled,
		&i.ForwardAuthHost,
		&i.ForwardAuthScopes,
		&i.LaunchUrl,
	)
	return i, err
}

const setSAMLSPAccessRestricted = `-- name: SetSAMLSPAccessRestricted :one
UPDATE saml_sp SET access_restricted = $2 WHERE id = $1 RETURNING id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled, access_restricted
`

type SetSAMLSPAccessRestrictedParams struct {
	ID               int64 `json:"id"`
	AccessRestricted bool  `json:"accessRestricted"`
}

func (q *Queries) SetSAMLSPAccessRestricted(ctx context.Context, arg SetSAMLSPAccessRestrictedParams) (SamlSp, error) {
	row := q.db.QueryRow(ctx, setSAMLSPAccessRestricted, arg.ID, arg.AccessRestricted)
	var i SamlSp
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.DisplayName,
		&i.SpKind,
		&i.NameIDFormat,
		&i.AttributeMap,
		&i.RequireSignedAuthnRequest,
		&i.AllowIdpInitiated,
		&i.SessionLifetime,
		&i.MetadataXml,
		&i.MetadataValidUntil,
		&i.MetadataCacheDuration,
		&i.MetadataFetchedAt,
		&i.CreatedAt,
		&i.Disabled,
		&i.AccessRestricted,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE user_group
SET slug = $2, display_name = $3, description = $4, exposed_to_downstream = $5, updated_at = now()
WHERE id = $1
RETURNING id, slug, display_name, description, exposed_to_downstream, created_at, updated_at
`

type UpdateGroupParams struct {
	ID                  int32       `json:"id"`
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
