// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignOIDCClientManager = `-- name: AssignOIDCClientManager :exec
INSERT INTO oidc_client_manager (client_id, account_id, created_by)
VALUES ($1, $2, $3)
ON CONFLICT (client_id, account_id) DO NOTHING
`

type AssignOIDCClientManagerParams struct {
	ClientID  string      `json:"clientId"`
	AccountID int32       `json:"accountId"`
	CreatedBy pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) AssignOIDCClientManager(ctx context.Context, arg AssignOIDCClientManagerParams) error {
	_, err := q.db.Exec(ctx, assignOIDCClientManager, arg.ClientID, arg.AccountID, arg.CreatedBy)
	return err
}

const assignSAMLSPManager = `-- name: AssignSAMLSPManager :exec
INSERT INTO saml_sp_manager (saml_sp_id, account_id, created_by)
VALUES ($1, $2, $3)
ON CONFLICT (saml_sp_id, account_id) DO NOTHING
`

type AssignSAMLSPManagerParams struct {
	SamlSpID  int64       `json:"samlSpId"`
	AccountID int32       `json:"accountId"`
	CreatedBy pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) AssignSAMLSPManager(ctx context.Context, arg AssignSAMLSPManagerParams) error {
	_, err := q.db.Exec(ctx, assignSAMLSPManager, arg.SamlSpID, arg.AccountID, arg.CreatedBy)
	return err
}

const clearManualDecision = `-- name: ClearManualDecision :execrows
DELETE FROM group_manual_decision
WHERE group_id = $1
  AND account_id = $2
`

type ClearManualDecisionParams struct {
	GroupID   int32 `json:"groupId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) ClearManualDecision(ctx context.Context, arg ClearManualDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearManualDecision, arg.GroupID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOIDCAppGroup = `-- name: CreateOIDCAppGroup :one
INSERT INTO user_group (
  kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id
)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7::text
)
RETURNING id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
`

type CreateOIDCAppGroupParams struct {
	Kind                string      `json:"kind"`
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
	Rule                []byte      `json:"rule"`
	OidcClientID        string      `json:"oidcClientId"`
}

func (q *Queries) CreateOIDCAppGroup(ctx context.Context, arg CreateOIDCAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createOIDCAppGroup,
		arg.Kind,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
		arg.Rule,
		arg.OidcClientID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.OidcClientID,
		&i.SamlSpID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSAMLAppGroup = `-- name: CreateSAMLAppGroup :one
INSERT INTO user_group (
  kind, slug, display_name, description, exposed_to_downstream, rule, saml_sp_id
)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7::bigint
)
RETURNING id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
`

type CreateSAMLAppGroupParams struct {
	Kind                string      `json:"kind"`
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
	Rule                []byte      `json:"rule"`
	SamlSpID            int64       `json:"samlSpId"`
}

func (q *Queries) CreateSAMLAppGroup(ctx context.Context, arg CreateSAMLAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createSAMLAppGroup,
		arg.Kind,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
		arg.Rule,
		arg.SamlSpID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.OidcClientID,
		&i.SamlSpID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteManagerAssignmentsForAccount = `-- name: DeleteManagerAssignmentsForAccount :exec
WITH deleted_oidc AS (
  DELETE FROM oidc_client_manager
  WHERE oidc_client_manager.account_id = $1
  RETURNING account_id
)
DELETE FROM saml_sp_manager
WHERE saml_sp_manager.account_id = $1
`

func (q *Queries) DeleteManagerAssignmentsForAccount(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, deleteManagerAssignmentsForAccount, accountID)
	return err
}

const deleteOIDCAppGroup = `-- name: DeleteOIDCAppGroup :execrows
DELETE FROM user_group
WHERE id = $1
  AND oidc_client_id = $2::text
`

type DeleteOIDCAppGroupParams struct {
	GroupID      int32  `json:"groupId"`
	OidcClientID string `json:"oidcClientId"`
}

func (q *Queries) DeleteOIDCAppGroup(ctx context.Context, arg DeleteOIDCAppGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOIDCAppGroup, arg.GroupID, arg.OidcClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSAMLAppGroup = `-- name: DeleteSAMLAppGroup :execrows
DELETE FROM user_group
WHERE id = $1
  AND saml_sp_id = $2::bigint
`

type DeleteSAMLAppGroupParams struct {
	GroupID  int32 `json:"groupId"`
	SamlSpID int64 `json:"samlSpId"`
}

func (q *Queries) DeleteSAMLAppGroup(ctx context.Context, arg DeleteSAMLAppGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSAMLAppGroup, arg.GroupID, arg.SamlSpID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountAccessFacts = `-- name: GetAccountAccessFacts :one
SELECT
  a.id,
  a.username,
  a.display_name,
  a.disabled,
  EXISTS (
    SELECT 1 FROM webauthn_credential w WHERE w.account_id = a.id
  ) AS has_passkey,
  EXISTS (
    SELECT 1
    FROM password_credential p
    WHERE p.account_id = a.id
      AND EXISTS (
        SELECT 1
        FROM totp_credential t
        WHERE t.account_id = a.id AND t.confirmed_at IS NOT NULL
      )
  ) AS has_password_totp,
  EXISTS (
    SELECT 1
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
      AND ip.protocol <> 'vrchat'
  ) AS has_federation,
  ARRAY(
    SELECT DISTINCT ip.slug
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
    ORDER BY ip.slug
  )::text[] AS confirmed_provider_slugs,
  ARRAY(
    SELECT DISTINCT ip.protocol
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
    ORDER BY ip.protocol
  )::text[] AS confirmed_protocols,
  EXISTS (
    SELECT 1 FROM account_avatar av WHERE av.account_id = a.id
  ) AS has_any_avatar,
  EXISTS (
    SELECT 1
    FROM account_avatar av
    WHERE av.account_id = a.id AND av.source = 'user'
  ) AS has_user_avatar
FROM account a
WHERE a.id = $1
`

type GetAccountAccessFactsRow struct {
	ID                     int32    `json:"id"`
	Username               string   `json:"username"`
	DisplayName            string   `json:"displayName"`
	Disabled               bool     `json:"disabled"`
	HasPasskey             bool     `json:"hasPasskey"`
	HasPasswordTotp        bool     `json:"hasPasswordTotp"`
	HasFederation          bool     `json:"hasFederation"`
	ConfirmedProviderSlugs []string `json:"confirmedProviderSlugs"`
	ConfirmedProtocols     []string `json:"confirmedProtocols"`
	HasAnyAvatar           bool     `json:"hasAnyAvatar"`
	HasUserAvatar          bool     `json:"hasUserAvatar"`
}

func (q *Queries) GetAccountAccessFacts(ctx context.Context, accountID int32) (GetAccountAccessFactsRow, error) {
	row := q.db.QueryRow(ctx, getAccountAccessFacts, accountID)
	var i GetAccountAccessFactsRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Disabled,
		&i.HasPasskey,
		&i.HasPasswordTotp,
		&i.HasFederation,
		&i.ConfirmedProviderSlugs,
		&i.ConfirmedProtocols,
		&i.HasAnyAvatar,
		&i.HasUserAvatar,
	)
	return i, err
}

const getManualDecisionForOIDCApp = `-- name: GetManualDecisionForOIDCApp :one
SELECT d.group_id, d.group_kind, d.account_id, d.effect, d.created_at, d.updated_at, d.created_by
FROM group_manual_decision d
JOIN user_group g ON g.id = d.group_id AND g.kind = d.group_kind
WHERE g.oidc_client_id = $1::text
  AND g.kind = 'manual'
  AND d.account_id = $2
`

type GetManualDecisionForOIDCAppParams struct {
	OidcClientID string `json:"oidcClientId"`
	AccountID    int32  `json:"accountId"`
}

func (q *Queries) GetManualDecisionForOIDCApp(ctx context.Context, arg GetManualDecisionForOIDCAppParams) (GroupManualDecision, error) {
	row := q.db.QueryRow(ctx, getManualDecisionForOIDCApp, arg.OidcClientID, arg.AccountID)
	var i GroupManualDecision
	err := row.Scan(
		&i.GroupID,
		&i.GroupKind,
		&i.AccountID,
		&i.Effect,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getManualDecisionForSAMLApp = `-- name: GetManualDecisionForSAMLApp :one
SELECT d.group_id, d.group_kind, d.account_id, d.effect, d.created_at, d.updated_at, d.created_by
FROM group_manual_decision d
JOIN user_group g ON g.id = d.group_id AND g.kind = d.group_kind
WHERE g.saml_sp_id = $1::bigint
  AND g.kind = 'manual'
  AND d.account_id = $2
`

type GetManualDecisionForSAMLAppParams struct {
	SamlSpID  int64 `json:"samlSpId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) GetManualDecisionForSAMLApp(ctx context.Context, arg GetManualDecisionForSAMLAppParams) (GroupManualDecision, error) {
	row := q.db.QueryRow(ctx, getManualDecisionForSAMLApp, arg.SamlSpID, arg.AccountID)
	var i GroupManualDecision
	err := row.Scan(
		&i.GroupID,
		&i.GroupKind,
		&i.AccountID,
		&i.Effect,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getOIDCAppGroup = `-- name: GetOIDCAppGroup :one
SELECT id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
FROM user_group
WHERE id = $1
  AND oidc_client_id = $2::text
`

type GetOIDCAppGroupParams struct {
	GroupID      int32  `json:"groupId"`
	OidcClientID string `json:"oidcClientId"`
}

func (q *Queries) GetOIDCAppGroup(ctx context.Context, arg GetOIDCAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getOIDCAppGroup, arg.GroupID, arg.OidcClientID)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.OidcClientID,
		&i.SamlSpID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSAMLAppGroup = `-- name: GetSAMLAppGroup :one
SELECT id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
FROM user_group
WHERE id = $1
  AND saml_sp_id = $2::bigint
`

type GetSAMLAppGroupParams struct {
	GroupID  int32 `json:"groupId"`
	SamlSpID int64 `json:"samlSpId"`
}

func (q *Queries) GetSAMLAppGroup(ctx context.Context, arg GetSAMLAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getSAMLAppGroup, arg.GroupID, arg.SamlSpID)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.OidcClientID,
		&i.SamlSpID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isOIDCClientManager = `-- name: IsOIDCClientManager :one
SELECT EXISTS (
  SELECT 1
  FROM oidc_client_manager
  WHERE client_id = $1
    AND account_id = $2
)
`

type IsOIDCClientManagerParams struct {
	ClientID  string `json:"clientId"`
	AccountID int32  `json:"accountId"`
}

func (q *Queries) IsOIDCClientManager(ctx context.Context, arg IsOIDCClientManagerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOIDCClientManager, arg.ClientID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isSAMLSPManager = `-- name: IsSAMLSPManager :one
SELECT EXISTS (
  SELECT 1
  FROM saml_sp_manager
  WHERE saml_sp_id = $1
    AND account_id = $2
)
`

type IsSAMLSPManagerParams struct {
	SamlSpID  int64 `json:"samlSpId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) IsSAMLSPManager(ctx context.Context, arg IsSAMLSPManagerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSAMLSPManager, arg.SamlSpID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveAccountAccessFactsPage = `-- name: ListActiveAccountAccessFactsPage :many
SELECT
  a.id,
  a.username,
  a.display_name,
  a.disabled,
  EXISTS (
    SELECT 1 FROM webauthn_credential w WHERE w.account_id = a.id
  ) AS has_passkey,
  EXISTS (
    SELECT 1
    FROM password_credential p
    WHERE p.account_id = a.id
      AND EXISTS (
        SELECT 1
        FROM totp_credential t
        WHERE t.account_id = a.id AND t.confirmed_at IS NOT NULL
      )
  ) AS has_password_totp,
  EXISTS (
    SELECT 1
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
      AND ip.protocol <> 'vrchat'
  ) AS has_federation,
  ARRAY(
    SELECT DISTINCT ip.slug
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
    ORDER BY ip.slug
  )::text[] AS confirmed_provider_slugs,
  ARRAY(
    SELECT DISTINCT ip.protocol
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
    ORDER BY ip.protocol
  )::text[] AS confirmed_protocols,
  EXISTS (
    SELECT 1 FROM account_avatar av WHERE av.account_id = a.id
  ) AS has_any_avatar,
  EXISTS (
    SELECT 1
    FROM account_avatar av
    WHERE av.account_id = a.id AND av.source = 'user'
  ) AS has_user_avatar
FROM account a
WHERE NOT a.disabled
  AND (
    $1::text IS NULL
    OR (a.username, a.id) > ($1, $2::int4)
  )
ORDER BY a.username ASC, a.id ASC
LIMIT $3
`

type ListActiveAccountAccessFactsPageParams struct {
	AfterUsername  pgtype.Text `json:"afterUsername"`
	AfterAccountID pgtype.Int4 `json:"afterAccountId"`
	RowLimit       int32       `json:"rowLimit"`
}

type ListActiveAccountAccessFactsPageRow struct {
	ID                     int32    `json:"id"`
	Username               string   `json:"username"`
	DisplayName            string   `json:"displayName"`
	Disabled               bool     `json:"disabled"`
	HasPasskey             bool     `json:"hasPasskey"`
	HasPasswordTotp        bool     `json:"hasPasswordTotp"`
	HasFederation          bool     `json:"hasFederation"`
	ConfirmedProviderSlugs []string `json:"confirmedProviderSlugs"`
	ConfirmedProtocols     []string `json:"confirmedProtocols"`
	HasAnyAvatar           bool     `json:"hasAnyAvatar"`
	HasUserAvatar          bool     `json:"hasUserAvatar"`
}

func (q *Queries) ListActiveAccountAccessFactsPage(ctx context.Context, arg ListActiveAccountAccessFactsPageParams) ([]ListActiveAccountAccessFactsPageRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccountAccessFactsPage, arg.AfterUsername, arg.AfterAccountID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAccountAccessFactsPageRow
	for rows.Next() {
		var i ListActiveAccountAccessFactsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Disabled,
			&i.HasPasskey,
			&i.HasPasswordTotp,
			&i.HasFederation,
			&i.ConfirmedProviderSlugs,
			&i.ConfirmedProtocols,
			&i.HasAnyAvatar,
			&i.HasUserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForwardAuthAccessCandidates = `-- name: ListForwardAuthAccessCandidates :many
SELECT
  client_id,
  display_name,
  forward_auth_host,
  forward_auth_scopes,
  access_restricted
FROM oidc_client
WHERE NOT disabled
  AND forward_auth_enabled
  AND forward_auth_host IS NOT NULL
ORDER BY display_name ASC, client_id ASC
`

type ListForwardAuthAccessCandidatesRow struct {
	ClientID          string      `json:"clientId"`
	DisplayName       string      `json:"displayName"`
	ForwardAuthHost   pgtype.Text `json:"forwardAuthHost"`
	ForwardAuthScopes []byte      `json:"forwardAuthScopes"`
	AccessRestricted  bool        `json:"accessRestricted"`
}

func (q *Queries) ListForwardAuthAccessCandidates(ctx context.Context) ([]ListForwardAuthAccessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listForwardAuthAccessCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForwardAuthAccessCandidatesRow
	for rows.Next() {
		var i ListForwardAuthAccessCandidatesRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.ForwardAuthHost,
			&i.ForwardAuthScopes,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDecisionsPage = `-- name: ListManualDecisionsPage :many
SELECT
  d.group_id,
  d.account_id,
  d.effect,
  d.created_at,
  d.updated_at,
  d.created_by,
  a.username,
  a.display_name,
  a.disabled
FROM group_manual_decision d
JOIN account a ON a.id = d.account_id
WHERE d.group_id = $1
  AND (
    $2::text IS NULL
    OR (a.username, a.id) > ($2, $3::int4)
  )
ORDER BY a.username ASC, a.id ASC
LIMIT $4
`

type ListManualDecisionsPageParams struct {
	GroupID        int32       `json:"groupId"`
	AfterUsername  pgtype.Text `json:"afterUsername"`
	AfterAccountID pgtype.Int4 `json:"afterAccountId"`
	RowLimit       int32       `json:"rowLimit"`
}

type ListManualDecisionsPageRow struct {
	GroupID     int32              `json:"groupId"`
	AccountID   int32              `json:"accountId"`
	Effect      string             `json:"effect"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	CreatedBy   pgtype.Int4        `json:"createdBy"`
	Username    string             `json:"username"`
	DisplayName string             `json:"displayName"`
	Disabled    bool               `json:"disabled"`
}

func (q *Queries) ListManualDecisionsPage(ctx context.Context, arg ListManualDecisionsPageParams) ([]ListManualDecisionsPageRow, error) {
	rows, err := q.db.Query(ctx, listManualDecisionsPage,
		arg.GroupID,
		arg.AfterUsername,
		arg.AfterAccountID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManualDecisionsPageRow
	for rows.Next() {
		var i ListManualDecisionsPageRow
		if err := rows.Scan(
			&i.GroupID,
			&i.AccountID,
			&i.Effect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Username,
			&i.DisplayName,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCAccessCandidates = `-- name: ListOIDCAccessCandidates :many
SELECT
  client_id,
  display_name,
  launch_url,
  redirect_uris,
  access_restricted
FROM oidc_client
WHERE NOT disabled
  AND NOT forward_auth_enabled
ORDER BY display_name ASC, client_id ASC
`

type ListOIDCAccessCandidatesRow struct {
	ClientID         string      `json:"clientId"`
	DisplayName      string      `json:"displayName"`
	LaunchUrl        pgtype.Text `json:"launchUrl"`
	RedirectUris     []string    `json:"redirectUris"`
	AccessRestricted bool        `json:"accessRestricted"`
}

func (q *Queries) ListOIDCAccessCandidates(ctx context.Context) ([]ListOIDCAccessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listOIDCAccessCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCAccessCandidatesRow
	for rows.Next() {
		var i ListOIDCAccessCandidatesRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.LaunchUrl,
			&i.RedirectUris,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCAppGroups = `-- name: ListOIDCAppGroups :many
SELECT id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
FROM user_group
WHERE oidc_client_id = $1::text
ORDER BY display_name ASC, id ASC
`

func (q *Queries) ListOIDCAppGroups(ctx context.Context, oidcClientID string) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listOIDCAppGroups, oidcClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.OidcClientID,
			&i.SamlSpID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCAppRuleGroups = `-- name: ListOIDCAppRuleGroups :many
SELECT id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
FROM user_group
WHERE oidc_client_id = $1::text
  AND kind = 'rule'
ORDER BY id ASC
`

func (q *Queries) ListOIDCAppRuleGroups(ctx context.Context, oidcClientID string) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listOIDCAppRuleGroups, oidcClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.OidcClientID,
			&i.SamlSpID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientManagers = `-- name: ListOIDCClientManagers :many
SELECT
  m.client_id,
  m.account_id,
  m.created_at,
  m.created_by,
  a.username,
  a.display_name,
  a.role,
  a.disabled
FROM oidc_client_manager m
JOIN account a ON a.id = m.account_id
WHERE m.client_id = $1
ORDER BY a.username ASC, a.id ASC
`

type ListOIDCClientManagersRow struct {
	ClientID    string             `json:"clientId"`
	AccountID   int32              `json:"accountId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	CreatedBy   pgtype.Int4        `json:"createdBy"`
	Username    string             `json:"username"`
	DisplayName string             `json:"displayName"`
	Role        string             `json:"role"`
	Disabled    bool               `json:"disabled"`
}

func (q *Queries) ListOIDCClientManagers(ctx context.Context, clientID string) ([]ListOIDCClientManagersRow, error) {
	rows, err := q.db.Query(ctx, listOIDCClientManagers, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCClientManagersRow
	for rows.Next() {
		var i ListOIDCClientManagersRow
		if err := rows.Scan(
			&i.ClientID,
			&i.AccountID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLAccessCandidates = `-- name: ListSAMLAccessCandidates :many
SELECT
  id,
  entity_id,
  display_name,
  access_restricted
FROM saml_sp
WHERE NOT disabled
  AND allow_idp_initiated
ORDER BY display_name ASC, id ASC
`

type ListSAMLAccessCandidatesRow struct {
	ID               int64  `json:"id"`
	EntityID         string `json:"entityId"`
	DisplayName      string `json:"displayName"`
	AccessRestricted bool   `json:"accessRestricted"`
}

func (q *Queries) ListSAMLAccessCandidates(ctx context.Context) ([]ListSAMLAccessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSAMLAccessCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLAccessCandidatesRow
	for rows.Next() {
		var i ListSAMLAccessCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.DisplayName,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLAppGroups = `-- name: ListSAMLAppGroups :many
SELECT id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
FROM user_group
WHERE saml_sp_id = $1::bigint
ORDER BY display_name ASC, id ASC
`

func (q *Queries) ListSAMLAppGroups(ctx context.Context, samlSpID int64) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listSAMLAppGroups, samlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.OidcClientID,
			&i.SamlSpID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLAppRuleGroups = `-- name: ListSAMLAppRuleGroups :many
SELECT id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
FROM user_group
WHERE saml_sp_id = $1::bigint
  AND kind = 'rule'
ORDER BY id ASC
`

func (q *Queries) ListSAMLAppRuleGroups(ctx context.Context, samlSpID int64) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listSAMLAppRuleGroups, samlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.OidcClientID,
			&i.SamlSpID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPManagers = `-- name: ListSAMLSPManagers :many
SELECT
  m.saml_sp_id,
  m.account_id,
  m.created_at,
  m.created_by,
  a.username,
  a.display_name,
  a.role,
  a.disabled
FROM saml_sp_manager m
JOIN account a ON a.id = m.account_id
WHERE m.saml_sp_id = $1
ORDER BY a.username ASC, a.id ASC
`

type ListSAMLSPManagersRow struct {
	SamlSpID    int64              `json:"samlSpId"`
	AccountID   int32              `json:"accountId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	CreatedBy   pgtype.Int4        `json:"createdBy"`
	Username    string             `json:"username"`
	DisplayName string             `json:"displayName"`
	Role        string             `json:"role"`
	Disabled    bool               `json:"disabled"`
}

func (q *Queries) ListSAMLSPManagers(ctx context.Context, samlSpID int64) ([]ListSAMLSPManagersRow, error) {
	rows, err := q.db.Query(ctx, listSAMLSPManagers, samlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLSPManagersRow
	for rows.Next() {
		var i ListSAMLSPManagersRow
		if err := rows.Scan(
			&i.SamlSpID,
			&i.AccountID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOIDCClientManager = `-- name: RemoveOIDCClientManager :execrows
DELETE FROM oidc_client_manager
WHERE client_id = $1
  AND account_id = $2
`

type RemoveOIDCClientManagerParams struct {
	ClientID  string `json:"clientId"`
	AccountID int32  `json:"accountId"`
}

func (q *Queries) RemoveOIDCClientManager(ctx context.Context, arg RemoveOIDCClientManagerParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeOIDCClientManager, arg.ClientID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeSAMLSPManager = `-- name: RemoveSAMLSPManager :execrows
DELETE FROM saml_sp_manager
WHERE saml_sp_id = $1
  AND account_id = $2
`

type RemoveSAMLSPManagerParams struct {
	SamlSpID  int64 `json:"samlSpId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) RemoveSAMLSPManager(ctx context.Context, arg RemoveSAMLSPManagerParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSAMLSPManager, arg.SamlSpID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOIDCClientAccessRestricted = `-- name: SetOIDCClientAccessRestricted :one
UPDATE oidc_client
SET access_restricted = $1
WHERE client_id = $2
RETURNING client_id, display_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, allowed_scopes, require_pkce, allowed_code_challenge_methods, token_endpoint_auth_method, subject_type, logo_uri, tos_uri, policy_uri, disabled, require_consent, created_at, access_restricted, forward_auth_enabled, forward_auth_host, forward_auth_scopes, launch_url
`

type SetOIDCClientAccessRestrictedParams struct {
	AccessRestricted bool   `json:"accessRestricted"`
	ClientID         string `json:"clientId"`
}

func (q *Queries) SetOIDCClientAccessRestricted(ctx context.Context, arg SetOIDCClientAccessRestrictedParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, setOIDCClientAccessRestricted, arg.AccessRestricted, arg.ClientID)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.DisplayName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.AllowedScopes,
		&i.RequirePkce,
		&i.AllowedCodeChallengeMethods,
		&i.TokenEndpointAuthMethod,
		&i.SubjectType,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Disabled,
		&i.RequireConsent,
		&i.CreatedAt,
		&i.AccessRestricted,
		&i.ForwardAuthEnabled,
		&i.ForwardAuthHost,
		&i.ForwardAuthScopes,
		&i.LaunchUrl,
	)
	return i, err
}

const setSAMLSPAccessRestricted = `-- name: SetSAMLSPAccessRestricted :one
UPDATE saml_sp
SET access_restricted = $1
WHERE id = $2
RETURNING id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled, access_restricted
`

type SetSAMLSPAccessRestrictedParams struct {
	AccessRestricted bool  `json:"accessRestricted"`
	SamlSpID         int64 `json:"samlSpId"`
}

func (q *Queries) SetSAMLSPAccessRestricted(ctx context.Context, arg SetSAMLSPAccessRestrictedParams) (SamlSp, error) {
	row := q.db.QueryRow(ctx, setSAMLSPAccessRestricted, arg.AccessRestricted, arg.SamlSpID)
	var i SamlSp
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.DisplayName,
		&i.SpKind,
		&i.NameIDFormat,
		&i.AttributeMap,
		&i.RequireSignedAuthnRequest,
		&i.AllowIdpInitiated,
		&i.SessionLifetime,
		&i.MetadataXml,
		&i.MetadataValidUntil,
		&i.MetadataCacheDuration,
		&i.MetadataFetchedAt,
		&i.CreatedAt,
		&i.Disabled,
		&i.AccessRestricted,
	)
	return i, err
}

const updateAppGroup = `-- name: UpdateAppGroup :one
UPDATE user_group
SET slug = $1,
    display_name = $2,
    description = $3,
    exposed_to_downstream = $4,
    rule = $5,
    updated_at = now()
WHERE id = $6
  AND num_nonnulls(
    $7::text,
    $8::bigint
  ) = 1
  AND (
    user_group.oidc_client_id = $7::text
    OR user_group.saml_sp_id = $8::bigint
  )
RETURNING id, kind, slug, display_name, description, exposed_to_downstream, rule, oidc_client_id, saml_sp_id, created_at, updated_at
`

type UpdateAppGroupParams struct {
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
	Rule                []byte      `json:"rule"`
	GroupID             int32       `json:"groupId"`
	OidcClientID        pgtype.Text `json:"oidcClientId"`
	SamlSpID            pgtype.Int8 `json:"samlSpId"`
}

func (q *Queries) UpdateAppGroup(ctx context.Context, arg UpdateAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, updateAppGroup,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
		arg.Rule,
		arg.GroupID,
		arg.OidcClientID,
		arg.SamlSpID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.OidcClientID,
		&i.SamlSpID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertManualDecision = `-- name: UpsertManualDecision :one
INSERT INTO group_manual_decision (group_id, account_id, effect, created_by)
VALUES (
  $1, $2, $3, $4
)
ON CONFLICT (group_id, account_id) DO UPDATE
SET effect = EXCLUDED.effect,
    updated_at = now()
RETURNING group_id, group_kind, account_id, effect, created_at, updated_at, created_by
`

type UpsertManualDecisionParams struct {
	GroupID   int32       `json:"groupId"`
	AccountID int32       `json:"accountId"`
	Effect    string      `json:"effect"`
	CreatedBy pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) UpsertManualDecision(ctx context.Context, arg UpsertManualDecisionParams) (GroupManualDecision, error) {
	row := q.db.QueryRow(ctx, upsertManualDecision,
		arg.GroupID,
		arg.AccountID,
		arg.Effect,
		arg.CreatedBy,
	)
	var i GroupManualDecision
	err := row.Scan(
		&i.GroupID,
		&i.GroupKind,
		&i.AccountID,
		&i.Effect,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
