// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignOIDCClientManager = `-- name: AssignOIDCClientManager :exec
INSERT INTO oidc_client_manager (client_id, account_id, created_by)
VALUES ($1, $2, $3)
ON CONFLICT (client_id, account_id) DO NOTHING
`

type AssignOIDCClientManagerParams struct {
	ClientID  string      `json:"clientId"`
	AccountID int32       `json:"accountId"`
	CreatedBy pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) AssignOIDCClientManager(ctx context.Context, arg AssignOIDCClientManagerParams) error {
	_, err := q.db.Exec(ctx, assignOIDCClientManager, arg.ClientID, arg.AccountID, arg.CreatedBy)
	return err
}

const assignSAMLSPManager = `-- name: AssignSAMLSPManager :exec
INSERT INTO saml_sp_manager (saml_sp_id, account_id, created_by)
VALUES ($1, $2, $3)
ON CONFLICT (saml_sp_id, account_id) DO NOTHING
`

type AssignSAMLSPManagerParams struct {
	SamlSpID  int64       `json:"samlSpId"`
	AccountID int32       `json:"accountId"`
	CreatedBy pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) AssignSAMLSPManager(ctx context.Context, arg AssignSAMLSPManagerParams) error {
	_, err := q.db.Exec(ctx, assignSAMLSPManager, arg.SamlSpID, arg.AccountID, arg.CreatedBy)
	return err
}

const clearManualDecision = `-- name: ClearManualDecision :execrows
DELETE FROM group_manual_decision
WHERE group_id = $1
  AND account_id = $2
`

type ClearManualDecisionParams struct {
	GroupID   int32 `json:"groupId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) ClearManualDecision(ctx context.Context, arg ClearManualDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearManualDecision, arg.GroupID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGlobalGroup = `-- name: CreateGlobalGroup :one
INSERT INTO user_group (kind, slug, display_name, description, exposed_to_downstream, rule)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, kind, slug, display_name, description, exposed_to_downstream, rule, created_at, updated_at
`

type CreateGlobalGroupParams struct {
	Kind                string      `json:"kind"`
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
	Rule                []byte      `json:"rule"`
}

func (q *Queries) CreateGlobalGroup(ctx context.Context, arg CreateGlobalGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createGlobalGroup,
		arg.Kind,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
		arg.Rule,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOIDCAppGroup = `-- name: CreateOIDCAppGroup :one
WITH created AS (
  INSERT INTO user_group (kind, slug, display_name, description, exposed_to_downstream, rule)
  VALUES ($1, $2, $3, $4,
          $5, $6)
  RETURNING id, kind, slug, display_name, description, exposed_to_downstream, rule, created_at, updated_at
), linked AS (
  INSERT INTO oidc_client_group (client_id, group_id)
  SELECT $7::text, id FROM created
)
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at FROM user_group g JOIN created c ON c.id = g.id
`

type CreateOIDCAppGroupParams struct {
	Kind                string      `json:"kind"`
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
	Rule                []byte      `json:"rule"`
	OidcClientID        string      `json:"oidcClientId"`
}

func (q *Queries) CreateOIDCAppGroup(ctx context.Context, arg CreateOIDCAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createOIDCAppGroup,
		arg.Kind,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
		arg.Rule,
		arg.OidcClientID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSAMLAppGroup = `-- name: CreateSAMLAppGroup :one
WITH created AS (
  INSERT INTO user_group (kind, slug, display_name, description, exposed_to_downstream, rule)
  VALUES ($1, $2, $3, $4,
          $5, $6)
  RETURNING id, kind, slug, display_name, description, exposed_to_downstream, rule, created_at, updated_at
), linked AS (
  INSERT INTO saml_sp_group (saml_sp_id, group_id)
  SELECT $7::bigint, id FROM created
)
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at FROM user_group g JOIN created c ON c.id = g.id
`

type CreateSAMLAppGroupParams struct {
	Kind                string      `json:"kind"`
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
	Rule                []byte      `json:"rule"`
	SamlSpID            int64       `json:"samlSpId"`
}

func (q *Queries) CreateSAMLAppGroup(ctx context.Context, arg CreateSAMLAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createSAMLAppGroup,
		arg.Kind,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
		arg.Rule,
		arg.SamlSpID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGlobalGroup = `-- name: DeleteGlobalGroup :execrows
DELETE FROM user_group WHERE id = $1
`

func (q *Queries) DeleteGlobalGroup(ctx context.Context, groupID int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGlobalGroup, groupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOIDCAppGroup = `-- name: DeleteOIDCAppGroup :execrows
DELETE FROM oidc_client_group
WHERE group_id = $1 AND client_id = $2::text
`

type DeleteOIDCAppGroupParams struct {
	GroupID      int32  `json:"groupId"`
	OidcClientID string `json:"oidcClientId"`
}

func (q *Queries) DeleteOIDCAppGroup(ctx context.Context, arg DeleteOIDCAppGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOIDCAppGroup, arg.GroupID, arg.OidcClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSAMLAppGroup = `-- name: DeleteSAMLAppGroup :execrows
DELETE FROM saml_sp_group
WHERE group_id = $1 AND saml_sp_id = $2::bigint
`

type DeleteSAMLAppGroupParams struct {
	GroupID  int32 `json:"groupId"`
	SamlSpID int64 `json:"samlSpId"`
}

func (q *Queries) DeleteSAMLAppGroup(ctx context.Context, arg DeleteSAMLAppGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSAMLAppGroup, arg.GroupID, arg.SamlSpID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountAccessFacts = `-- name: GetAccountAccessFacts :one
SELECT
  a.id,
  a.username,
  a.display_name,
  a.disabled,
  EXISTS (
    SELECT 1 FROM webauthn_credential w WHERE w.account_id = a.id
  ) AS has_passkey,
  EXISTS (
    SELECT 1
    FROM password_credential p
    WHERE p.account_id = a.id
      AND EXISTS (
        SELECT 1
        FROM totp_credential t
        WHERE t.account_id = a.id AND t.confirmed_at IS NOT NULL
      )
  ) AS has_password_totp,
  EXISTS (
    SELECT 1
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
      AND ip.protocol <> 'vrchat'
  ) AS has_federation,
  ARRAY(
    SELECT DISTINCT ip.slug
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
    ORDER BY ip.slug
  )::text[] AS confirmed_provider_slugs,
  ARRAY(
    SELECT DISTINCT ip.protocol
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
    ORDER BY ip.protocol
  )::text[] AS confirmed_protocols,
  EXISTS (
    SELECT 1 FROM account_avatar av WHERE av.account_id = a.id
  ) AS has_any_avatar,
  EXISTS (
    SELECT 1
    FROM account_avatar av
    WHERE av.account_id = a.id AND av.source = 'user'
  ) AS has_user_avatar
FROM account a
WHERE a.id = $1
`

type GetAccountAccessFactsRow struct {
	ID                     int32    `json:"id"`
	Username               string   `json:"username"`
	DisplayName            string   `json:"displayName"`
	Disabled               bool     `json:"disabled"`
	HasPasskey             bool     `json:"hasPasskey"`
	HasPasswordTotp        bool     `json:"hasPasswordTotp"`
	HasFederation          bool     `json:"hasFederation"`
	ConfirmedProviderSlugs []string `json:"confirmedProviderSlugs"`
	ConfirmedProtocols     []string `json:"confirmedProtocols"`
	HasAnyAvatar           bool     `json:"hasAnyAvatar"`
	HasUserAvatar          bool     `json:"hasUserAvatar"`
}

func (q *Queries) GetAccountAccessFacts(ctx context.Context, accountID int32) (GetAccountAccessFactsRow, error) {
	row := q.db.QueryRow(ctx, getAccountAccessFacts, accountID)
	var i GetAccountAccessFactsRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Disabled,
		&i.HasPasskey,
		&i.HasPasswordTotp,
		&i.HasFederation,
		&i.ConfirmedProviderSlugs,
		&i.ConfirmedProtocols,
		&i.HasAnyAvatar,
		&i.HasUserAvatar,
	)
	return i, err
}

const getGlobalGroup = `-- name: GetGlobalGroup :one
SELECT id, kind, slug, display_name, description, exposed_to_downstream, rule, created_at, updated_at FROM user_group WHERE id = $1
`

func (q *Queries) GetGlobalGroup(ctx context.Context, groupID int32) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getGlobalGroup, groupID)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOIDCAppGroup = `-- name: GetOIDCAppGroup :one
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at
FROM user_group g
WHERE g.id = $1
  AND EXISTS (SELECT 1 FROM oidc_client_group og
              WHERE og.group_id = g.id AND og.client_id = $2::text)
`

type GetOIDCAppGroupParams struct {
	GroupID      int32  `json:"groupId"`
	OidcClientID string `json:"oidcClientId"`
}

func (q *Queries) GetOIDCAppGroup(ctx context.Context, arg GetOIDCAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getOIDCAppGroup, arg.GroupID, arg.OidcClientID)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSAMLAppGroup = `-- name: GetSAMLAppGroup :one
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at
FROM user_group g
WHERE g.id = $1
  AND EXISTS (SELECT 1 FROM saml_sp_group sg
              WHERE sg.group_id = g.id AND sg.saml_sp_id = $2::bigint)
`

type GetSAMLAppGroupParams struct {
	GroupID  int32 `json:"groupId"`
	SamlSpID int64 `json:"samlSpId"`
}

func (q *Queries) GetSAMLAppGroup(ctx context.Context, arg GetSAMLAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getSAMLAppGroup, arg.GroupID, arg.SamlSpID)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isOIDCClientManager = `-- name: IsOIDCClientManager :one
SELECT EXISTS (
  SELECT 1
  FROM oidc_client_manager
  WHERE client_id = $1
    AND account_id = $2
)
`

type IsOIDCClientManagerParams struct {
	ClientID  string `json:"clientId"`
	AccountID int32  `json:"accountId"`
}

func (q *Queries) IsOIDCClientManager(ctx context.Context, arg IsOIDCClientManagerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOIDCClientManager, arg.ClientID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isSAMLSPManager = `-- name: IsSAMLSPManager :one
SELECT EXISTS (
  SELECT 1
  FROM saml_sp_manager
  WHERE saml_sp_id = $1
    AND account_id = $2
)
`

type IsSAMLSPManagerParams struct {
	SamlSpID  int64 `json:"samlSpId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) IsSAMLSPManager(ctx context.Context, arg IsSAMLSPManagerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSAMLSPManager, arg.SamlSpID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveAccountAccessFacts = `-- name: ListActiveAccountAccessFacts :many
SELECT
  a.id,
  a.username,
  a.display_name,
  a.disabled,
  EXISTS (
    SELECT 1 FROM webauthn_credential w WHERE w.account_id = a.id
  ) AS has_passkey,
  EXISTS (
    SELECT 1
    FROM password_credential p
    WHERE p.account_id = a.id
      AND EXISTS (
        SELECT 1
        FROM totp_credential t
        WHERE t.account_id = a.id AND t.confirmed_at IS NOT NULL
      )
  ) AS has_password_totp,
  EXISTS (
    SELECT 1
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
      AND ip.protocol <> 'vrchat'
  ) AS has_federation,
  ARRAY(
    SELECT DISTINCT ip.slug
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
    ORDER BY ip.slug
  )::text[] AS confirmed_provider_slugs,
  ARRAY(
    SELECT DISTINCT ip.protocol
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
    ORDER BY ip.protocol
  )::text[] AS confirmed_protocols,
  EXISTS (
    SELECT 1 FROM account_avatar av WHERE av.account_id = a.id
  ) AS has_any_avatar,
  EXISTS (
    SELECT 1
    FROM account_avatar av
    WHERE av.account_id = a.id AND av.source = 'user'
  ) AS has_user_avatar
FROM account a
WHERE NOT a.disabled
ORDER BY a.username ASC, a.id ASC
`

type ListActiveAccountAccessFactsRow struct {
	ID                     int32    `json:"id"`
	Username               string   `json:"username"`
	DisplayName            string   `json:"displayName"`
	Disabled               bool     `json:"disabled"`
	HasPasskey             bool     `json:"hasPasskey"`
	HasPasswordTotp        bool     `json:"hasPasswordTotp"`
	HasFederation          bool     `json:"hasFederation"`
	ConfirmedProviderSlugs []string `json:"confirmedProviderSlugs"`
	ConfirmedProtocols     []string `json:"confirmedProtocols"`
	HasAnyAvatar           bool     `json:"hasAnyAvatar"`
	HasUserAvatar          bool     `json:"hasUserAvatar"`
}

func (q *Queries) ListActiveAccountAccessFacts(ctx context.Context) ([]ListActiveAccountAccessFactsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccountAccessFacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAccountAccessFactsRow
	for rows.Next() {
		var i ListActiveAccountAccessFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Disabled,
			&i.HasPasskey,
			&i.HasPasswordTotp,
			&i.HasFederation,
			&i.ConfirmedProviderSlugs,
			&i.ConfirmedProtocols,
			&i.HasAnyAvatar,
			&i.HasUserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAccountAccessFactsPage = `-- name: ListActiveAccountAccessFactsPage :many
SELECT
  a.id,
  a.username,
  a.display_name,
  a.disabled,
  EXISTS (
    SELECT 1 FROM webauthn_credential w WHERE w.account_id = a.id
  ) AS has_passkey,
  EXISTS (
    SELECT 1
    FROM password_credential p
    WHERE p.account_id = a.id
      AND EXISTS (
        SELECT 1
        FROM totp_credential t
        WHERE t.account_id = a.id AND t.confirmed_at IS NOT NULL
      )
  ) AS has_password_totp,
  EXISTS (
    SELECT 1
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
      AND NOT ip.disabled
      AND ip.protocol <> 'vrchat'
  ) AS has_federation,
  ARRAY(
    SELECT DISTINCT ip.slug
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
    ORDER BY ip.slug
  )::text[] AS confirmed_provider_slugs,
  ARRAY(
    SELECT DISTINCT ip.protocol
    FROM account_identity ai
    JOIN upstream_idp ip ON ip.id = ai.upstream_idp_id
    WHERE ai.account_id = a.id
      AND ai.confirmed_at IS NOT NULL
    ORDER BY ip.protocol
  )::text[] AS confirmed_protocols,
  EXISTS (
    SELECT 1 FROM account_avatar av WHERE av.account_id = a.id
  ) AS has_any_avatar,
  EXISTS (
    SELECT 1
    FROM account_avatar av
    WHERE av.account_id = a.id AND av.source = 'user'
  ) AS has_user_avatar
FROM account a
WHERE NOT a.disabled
  AND (
    $1::text IS NULL
    OR (a.username, a.id) > ($1, $2::int4)
  )
ORDER BY a.username ASC, a.id ASC
LIMIT $3
`

type ListActiveAccountAccessFactsPageParams struct {
	AfterUsername  pgtype.Text `json:"afterUsername"`
	AfterAccountID pgtype.Int4 `json:"afterAccountId"`
	RowLimit       int32       `json:"rowLimit"`
}

type ListActiveAccountAccessFactsPageRow struct {
	ID                     int32    `json:"id"`
	Username               string   `json:"username"`
	DisplayName            string   `json:"displayName"`
	Disabled               bool     `json:"disabled"`
	HasPasskey             bool     `json:"hasPasskey"`
	HasPasswordTotp        bool     `json:"hasPasswordTotp"`
	HasFederation          bool     `json:"hasFederation"`
	ConfirmedProviderSlugs []string `json:"confirmedProviderSlugs"`
	ConfirmedProtocols     []string `json:"confirmedProtocols"`
	HasAnyAvatar           bool     `json:"hasAnyAvatar"`
	HasUserAvatar          bool     `json:"hasUserAvatar"`
}

func (q *Queries) ListActiveAccountAccessFactsPage(ctx context.Context, arg ListActiveAccountAccessFactsPageParams) ([]ListActiveAccountAccessFactsPageRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccountAccessFactsPage, arg.AfterUsername, arg.AfterAccountID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAccountAccessFactsPageRow
	for rows.Next() {
		var i ListActiveAccountAccessFactsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Disabled,
			&i.HasPasskey,
			&i.HasPasswordTotp,
			&i.HasFederation,
			&i.ConfirmedProviderSlugs,
			&i.ConfirmedProtocols,
			&i.HasAnyAvatar,
			&i.HasUserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForwardAuthAccessCandidates = `-- name: ListForwardAuthAccessCandidates :many
SELECT
  client_id,
  display_name,
  forward_auth_host,
  forward_auth_scopes,
  access_restricted
FROM oidc_client
WHERE NOT disabled
  AND forward_auth_enabled
  AND forward_auth_host IS NOT NULL
ORDER BY display_name ASC, client_id ASC
`

type ListForwardAuthAccessCandidatesRow struct {
	ClientID          string      `json:"clientId"`
	DisplayName       string      `json:"displayName"`
	ForwardAuthHost   pgtype.Text `json:"forwardAuthHost"`
	ForwardAuthScopes []byte      `json:"forwardAuthScopes"`
	AccessRestricted  bool        `json:"accessRestricted"`
}

func (q *Queries) ListForwardAuthAccessCandidates(ctx context.Context) ([]ListForwardAuthAccessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listForwardAuthAccessCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForwardAuthAccessCandidatesRow
	for rows.Next() {
		var i ListForwardAuthAccessCandidatesRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.ForwardAuthHost,
			&i.ForwardAuthScopes,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForwardAuthManagementCandidates = `-- name: ListForwardAuthManagementCandidates :many
SELECT
  client_id,
  display_name,
  forward_auth_host,
  forward_auth_scopes,
  access_restricted
FROM oidc_client
WHERE forward_auth_enabled
ORDER BY display_name ASC, client_id ASC
`

type ListForwardAuthManagementCandidatesRow struct {
	ClientID          string      `json:"clientId"`
	DisplayName       string      `json:"displayName"`
	ForwardAuthHost   pgtype.Text `json:"forwardAuthHost"`
	ForwardAuthScopes []byte      `json:"forwardAuthScopes"`
	AccessRestricted  bool        `json:"accessRestricted"`
}

func (q *Queries) ListForwardAuthManagementCandidates(ctx context.Context) ([]ListForwardAuthManagementCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listForwardAuthManagementCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForwardAuthManagementCandidatesRow
	for rows.Next() {
		var i ListForwardAuthManagementCandidatesRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.ForwardAuthHost,
			&i.ForwardAuthScopes,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalGroupApplications = `-- name: ListGlobalGroupApplications :many
SELECT kind, app_id, display_name
FROM (
  SELECT
    CASE WHEN c.forward_auth_enabled THEN 'forward_auth' ELSE 'oidc' END::text AS kind,
    c.client_id::text AS app_id,
    c.display_name
  FROM oidc_client_group link
  JOIN oidc_client c ON c.client_id = link.client_id
  WHERE link.group_id = $1

  UNION ALL

  SELECT 'saml'::text AS kind, sp.id::text AS app_id, sp.display_name
  FROM saml_sp_group link
  JOIN saml_sp sp ON sp.id = link.saml_sp_id
  WHERE link.group_id = $1
) applications
ORDER BY kind ASC, display_name ASC, app_id ASC
`

type ListGlobalGroupApplicationsRow struct {
	Kind        string `json:"kind"`
	AppID       string `json:"appId"`
	DisplayName string `json:"displayName"`
}

func (q *Queries) ListGlobalGroupApplications(ctx context.Context, groupID int32) ([]ListGlobalGroupApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listGlobalGroupApplications, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGlobalGroupApplicationsRow
	for rows.Next() {
		var i ListGlobalGroupApplicationsRow
		if err := rows.Scan(&i.Kind, &i.AppID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalGroups = `-- name: ListGlobalGroups :many
SELECT id, kind, slug, display_name, description, exposed_to_downstream, rule, created_at, updated_at FROM user_group
ORDER BY display_name ASC, id ASC
`

func (q *Queries) ListGlobalGroups(ctx context.Context) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listGlobalGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDecisionsForOIDCApp = `-- name: ListManualDecisionsForOIDCApp :many
SELECT d.group_id, d.group_kind, d.account_id, d.effect, d.created_at, d.updated_at, d.created_by
FROM group_manual_decision d
JOIN user_group g ON g.id = d.group_id AND g.kind = d.group_kind
JOIN oidc_client_group og ON og.group_id = g.id
WHERE og.client_id = $1::text
  AND g.kind = 'manual'
  AND d.account_id = $2
`

type ListManualDecisionsForOIDCAppParams struct {
	OidcClientID string `json:"oidcClientId"`
	AccountID    int32  `json:"accountId"`
}

func (q *Queries) ListManualDecisionsForOIDCApp(ctx context.Context, arg ListManualDecisionsForOIDCAppParams) ([]GroupManualDecision, error) {
	rows, err := q.db.Query(ctx, listManualDecisionsForOIDCApp, arg.OidcClientID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupManualDecision
	for rows.Next() {
		var i GroupManualDecision
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupKind,
			&i.AccountID,
			&i.Effect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDecisionsForSAMLApp = `-- name: ListManualDecisionsForSAMLApp :many
SELECT d.group_id, d.group_kind, d.account_id, d.effect, d.created_at, d.updated_at, d.created_by
FROM group_manual_decision d
JOIN user_group g ON g.id = d.group_id AND g.kind = d.group_kind
JOIN saml_sp_group sg ON sg.group_id = g.id
WHERE sg.saml_sp_id = $1::bigint
  AND g.kind = 'manual'
  AND d.account_id = $2
`

type ListManualDecisionsForSAMLAppParams struct {
	SamlSpID  int64 `json:"samlSpId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) ListManualDecisionsForSAMLApp(ctx context.Context, arg ListManualDecisionsForSAMLAppParams) ([]GroupManualDecision, error) {
	rows, err := q.db.Query(ctx, listManualDecisionsForSAMLApp, arg.SamlSpID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupManualDecision
	for rows.Next() {
		var i GroupManualDecision
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupKind,
			&i.AccountID,
			&i.Effect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDecisionsPage = `-- name: ListManualDecisionsPage :many
SELECT
  d.group_id,
  d.account_id,
  d.effect,
  d.created_at,
  d.updated_at,
  d.created_by,
  a.username,
  a.display_name,
  a.disabled
FROM group_manual_decision d
JOIN account a ON a.id = d.account_id
WHERE d.group_id = $1
  AND (
    $2::text IS NULL
    OR (a.username, a.id) > ($2, $3::int4)
  )
ORDER BY a.username ASC, a.id ASC
LIMIT $4
`

type ListManualDecisionsPageParams struct {
	GroupID        int32       `json:"groupId"`
	AfterUsername  pgtype.Text `json:"afterUsername"`
	AfterAccountID pgtype.Int4 `json:"afterAccountId"`
	RowLimit       int32       `json:"rowLimit"`
}

type ListManualDecisionsPageRow struct {
	GroupID     int32              `json:"groupId"`
	AccountID   int32              `json:"accountId"`
	Effect      string             `json:"effect"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	CreatedBy   pgtype.Int4        `json:"createdBy"`
	Username    string             `json:"username"`
	DisplayName string             `json:"displayName"`
	Disabled    bool               `json:"disabled"`
}

func (q *Queries) ListManualDecisionsPage(ctx context.Context, arg ListManualDecisionsPageParams) ([]ListManualDecisionsPageRow, error) {
	rows, err := q.db.Query(ctx, listManualDecisionsPage,
		arg.GroupID,
		arg.AfterUsername,
		arg.AfterAccountID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManualDecisionsPageRow
	for rows.Next() {
		var i ListManualDecisionsPageRow
		if err := rows.Scan(
			&i.GroupID,
			&i.AccountID,
			&i.Effect,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Username,
			&i.DisplayName,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCAccessCandidates = `-- name: ListOIDCAccessCandidates :many
SELECT
  client_id,
  display_name,
  launch_url,
  redirect_uris,
  require_consent,
  access_restricted
FROM oidc_client
WHERE NOT disabled
  AND NOT forward_auth_enabled
ORDER BY display_name ASC, client_id ASC
`

type ListOIDCAccessCandidatesRow struct {
	ClientID         string      `json:"clientId"`
	DisplayName      string      `json:"displayName"`
	LaunchUrl        pgtype.Text `json:"launchUrl"`
	RedirectUris     []string    `json:"redirectUris"`
	RequireConsent   bool        `json:"requireConsent"`
	AccessRestricted bool        `json:"accessRestricted"`
}

func (q *Queries) ListOIDCAccessCandidates(ctx context.Context) ([]ListOIDCAccessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listOIDCAccessCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCAccessCandidatesRow
	for rows.Next() {
		var i ListOIDCAccessCandidatesRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.LaunchUrl,
			&i.RedirectUris,
			&i.RequireConsent,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCAppGroups = `-- name: ListOIDCAppGroups :many
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at
FROM user_group g
JOIN oidc_client_group og ON og.group_id = g.id
WHERE og.client_id = $1::text
ORDER BY g.display_name ASC, g.id ASC
`

func (q *Queries) ListOIDCAppGroups(ctx context.Context, oidcClientID string) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listOIDCAppGroups, oidcClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCAppRuleGroups = `-- name: ListOIDCAppRuleGroups :many
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at
FROM user_group g
JOIN oidc_client_group og ON og.group_id = g.id
WHERE og.client_id = $1::text
  AND g.kind = 'rule'
ORDER BY g.id ASC
`

func (q *Queries) ListOIDCAppRuleGroups(ctx context.Context, oidcClientID string) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listOIDCAppRuleGroups, oidcClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientManagers = `-- name: ListOIDCClientManagers :many
SELECT
  m.client_id,
  m.account_id,
  m.created_at,
  m.created_by,
  a.username,
  a.display_name,
  a.role,
  a.disabled
FROM oidc_client_manager m
JOIN account a ON a.id = m.account_id
WHERE m.client_id = $1
ORDER BY a.username ASC, a.id ASC
`

type ListOIDCClientManagersRow struct {
	ClientID    string             `json:"clientId"`
	AccountID   int32              `json:"accountId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	CreatedBy   pgtype.Int4        `json:"createdBy"`
	Username    string             `json:"username"`
	DisplayName string             `json:"displayName"`
	Role        string             `json:"role"`
	Disabled    bool               `json:"disabled"`
}

func (q *Queries) ListOIDCClientManagers(ctx context.Context, clientID string) ([]ListOIDCClientManagersRow, error) {
	rows, err := q.db.Query(ctx, listOIDCClientManagers, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCClientManagersRow
	for rows.Next() {
		var i ListOIDCClientManagersRow
		if err := rows.Scan(
			&i.ClientID,
			&i.AccountID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCManagementCandidates = `-- name: ListOIDCManagementCandidates :many
SELECT
  client_id,
  display_name,
  launch_url,
  redirect_uris,
  access_restricted
FROM oidc_client
WHERE NOT forward_auth_enabled
ORDER BY display_name ASC, client_id ASC
`

type ListOIDCManagementCandidatesRow struct {
	ClientID         string      `json:"clientId"`
	DisplayName      string      `json:"displayName"`
	LaunchUrl        pgtype.Text `json:"launchUrl"`
	RedirectUris     []string    `json:"redirectUris"`
	AccessRestricted bool        `json:"accessRestricted"`
}

// Management candidates deliberately do not reuse the launchpad candidate
// queries above: an assigned manager must be able to inspect and change policy
// for disabled, not-yet-launchable, and non-IdP-initiated applications.
func (q *Queries) ListOIDCManagementCandidates(ctx context.Context) ([]ListOIDCManagementCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listOIDCManagementCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCManagementCandidatesRow
	for rows.Next() {
		var i ListOIDCManagementCandidatesRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.LaunchUrl,
			&i.RedirectUris,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLAccessCandidates = `-- name: ListSAMLAccessCandidates :many
SELECT
  id,
  entity_id,
  display_name,
  access_restricted
FROM saml_sp
WHERE NOT disabled
  AND allow_idp_initiated
ORDER BY display_name ASC, id ASC
`

type ListSAMLAccessCandidatesRow struct {
	ID               int64  `json:"id"`
	EntityID         string `json:"entityId"`
	DisplayName      string `json:"displayName"`
	AccessRestricted bool   `json:"accessRestricted"`
}

func (q *Queries) ListSAMLAccessCandidates(ctx context.Context) ([]ListSAMLAccessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSAMLAccessCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLAccessCandidatesRow
	for rows.Next() {
		var i ListSAMLAccessCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.DisplayName,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLAppGroups = `-- name: ListSAMLAppGroups :many
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at
FROM user_group g
JOIN saml_sp_group sg ON sg.group_id = g.id
WHERE sg.saml_sp_id = $1::bigint
ORDER BY g.display_name ASC, g.id ASC
`

func (q *Queries) ListSAMLAppGroups(ctx context.Context, samlSpID int64) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listSAMLAppGroups, samlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLAppRuleGroups = `-- name: ListSAMLAppRuleGroups :many
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at
FROM user_group g
JOIN saml_sp_group sg ON sg.group_id = g.id
WHERE sg.saml_sp_id = $1::bigint
  AND g.kind = 'rule'
ORDER BY g.id ASC
`

func (q *Queries) ListSAMLAppRuleGroups(ctx context.Context, samlSpID int64) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listSAMLAppRuleGroups, samlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLManagementCandidates = `-- name: ListSAMLManagementCandidates :many
SELECT
  id,
  entity_id,
  display_name,
  access_restricted
FROM saml_sp
ORDER BY display_name ASC, id ASC
`

type ListSAMLManagementCandidatesRow struct {
	ID               int64  `json:"id"`
	EntityID         string `json:"entityId"`
	DisplayName      string `json:"displayName"`
	AccessRestricted bool   `json:"accessRestricted"`
}

func (q *Queries) ListSAMLManagementCandidates(ctx context.Context) ([]ListSAMLManagementCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSAMLManagementCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLManagementCandidatesRow
	for rows.Next() {
		var i ListSAMLManagementCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.DisplayName,
			&i.AccessRestricted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPManagers = `-- name: ListSAMLSPManagers :many
SELECT
  m.saml_sp_id,
  m.account_id,
  m.created_at,
  m.created_by,
  a.username,
  a.display_name,
  a.role,
  a.disabled
FROM saml_sp_manager m
JOIN account a ON a.id = m.account_id
WHERE m.saml_sp_id = $1
ORDER BY a.username ASC, a.id ASC
`

type ListSAMLSPManagersRow struct {
	SamlSpID    int64              `json:"samlSpId"`
	AccountID   int32              `json:"accountId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	CreatedBy   pgtype.Int4        `json:"createdBy"`
	Username    string             `json:"username"`
	DisplayName string             `json:"displayName"`
	Role        string             `json:"role"`
	Disabled    bool               `json:"disabled"`
}

func (q *Queries) ListSAMLSPManagers(ctx context.Context, samlSpID int64) ([]ListSAMLSPManagersRow, error) {
	rows, err := q.db.Query(ctx, listSAMLSPManagers, samlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLSPManagersRow
	for rows.Next() {
		var i ListSAMLSPManagersRow
		if err := rows.Scan(
			&i.SamlSpID,
			&i.AccountID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOIDCClientManager = `-- name: RemoveOIDCClientManager :execrows
DELETE FROM oidc_client_manager
WHERE client_id = $1
  AND account_id = $2
`

type RemoveOIDCClientManagerParams struct {
	ClientID  string `json:"clientId"`
	AccountID int32  `json:"accountId"`
}

func (q *Queries) RemoveOIDCClientManager(ctx context.Context, arg RemoveOIDCClientManagerParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeOIDCClientManager, arg.ClientID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeSAMLSPManager = `-- name: RemoveSAMLSPManager :execrows
DELETE FROM saml_sp_manager
WHERE saml_sp_id = $1
  AND account_id = $2
`

type RemoveSAMLSPManagerParams struct {
	SamlSpID  int64 `json:"samlSpId"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) RemoveSAMLSPManager(ctx context.Context, arg RemoveSAMLSPManagerParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSAMLSPManager, arg.SamlSpID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceOIDCAppGroups = `-- name: ReplaceOIDCAppGroups :many
WITH locked AS (
  SELECT client_id FROM oidc_client
  WHERE client_id = $2::text
  FOR UPDATE
), deleted AS (
  DELETE FROM oidc_client_group og
  USING locked l
  WHERE og.client_id = l.client_id
    AND NOT (og.group_id = ANY($1::int[]))
  RETURNING og.group_id
), inserted AS (
  INSERT INTO oidc_client_group (client_id, group_id)
  SELECT l.client_id, requested.group_id
  FROM locked l
  CROSS JOIN unnest($1::int[]) AS requested(group_id)
  ON CONFLICT (client_id, group_id) DO NOTHING
  RETURNING group_id
)
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at FROM user_group g, locked l
WHERE g.id = ANY($1::int[])
ORDER BY g.display_name ASC, g.id ASC
`

type ReplaceOIDCAppGroupsParams struct {
	GroupIds     []int32 `json:"groupIds"`
	OidcClientID string  `json:"oidcClientId"`
}

func (q *Queries) ReplaceOIDCAppGroups(ctx context.Context, arg ReplaceOIDCAppGroupsParams) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, replaceOIDCAppGroups, arg.GroupIds, arg.OidcClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSAMLAppGroups = `-- name: ReplaceSAMLAppGroups :many
WITH locked AS (
  SELECT id FROM saml_sp
  WHERE id = $2::bigint
  FOR UPDATE
), deleted AS (
  DELETE FROM saml_sp_group sg
  USING locked l
  WHERE sg.saml_sp_id = l.id
    AND NOT (sg.group_id = ANY($1::int[]))
  RETURNING sg.group_id
), inserted AS (
  INSERT INTO saml_sp_group (saml_sp_id, group_id)
  SELECT l.id, requested.group_id
  FROM locked l
  CROSS JOIN unnest($1::int[]) AS requested(group_id)
  ON CONFLICT (saml_sp_id, group_id) DO NOTHING
  RETURNING group_id
)
SELECT g.id, g.kind, g.slug, g.display_name, g.description, g.exposed_to_downstream, g.rule, g.created_at, g.updated_at FROM user_group g, locked l
WHERE g.id = ANY($1::int[])
ORDER BY g.display_name ASC, g.id ASC
`

type ReplaceSAMLAppGroupsParams struct {
	GroupIds []int32 `json:"groupIds"`
	SamlSpID int64   `json:"samlSpId"`
}

func (q *Queries) ReplaceSAMLAppGroups(ctx context.Context, arg ReplaceSAMLAppGroupsParams) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, replaceSAMLAppGroups, arg.GroupIds, arg.SamlSpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ExposedToDownstream,
			&i.Rule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOIDCClientAccessRestricted = `-- name: SetOIDCClientAccessRestricted :one
UPDATE oidc_client
SET access_restricted = $1
WHERE client_id = $2
RETURNING client_id, display_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, allowed_scopes, require_pkce, allowed_code_challenge_methods, client_auth_method, subject_type, logo_uri, tos_uri, policy_uri, disabled, require_consent, created_at, access_restricted, forward_auth_enabled, forward_auth_host, forward_auth_scopes, launch_url, principal_source, claim_aliases
`

type SetOIDCClientAccessRestrictedParams struct {
	AccessRestricted bool   `json:"accessRestricted"`
	ClientID         string `json:"clientId"`
}

func (q *Queries) SetOIDCClientAccessRestricted(ctx context.Context, arg SetOIDCClientAccessRestrictedParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, setOIDCClientAccessRestricted, arg.AccessRestricted, arg.ClientID)
	var i OidcClient
	err := row.Scan(
		&i.ClientID,
		&i.DisplayName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.AllowedScopes,
		&i.RequirePkce,
		&i.AllowedCodeChallengeMethods,
		&i.ClientAuthMethod,
		&i.SubjectType,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Disabled,
		&i.RequireConsent,
		&i.CreatedAt,
		&i.AccessRestricted,
		&i.ForwardAuthEnabled,
		&i.ForwardAuthHost,
		&i.ForwardAuthScopes,
		&i.LaunchUrl,
		&i.PrincipalSource,
		&i.ClaimAliases,
	)
	return i, err
}

const setSAMLSPAccessRestricted = `-- name: SetSAMLSPAccessRestricted :one
UPDATE saml_sp
SET access_restricted = $1
WHERE id = $2
RETURNING id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled, access_restricted
`

type SetSAMLSPAccessRestrictedParams struct {
	AccessRestricted bool  `json:"accessRestricted"`
	SamlSpID         int64 `json:"samlSpId"`
}

func (q *Queries) SetSAMLSPAccessRestricted(ctx context.Context, arg SetSAMLSPAccessRestrictedParams) (SamlSp, error) {
	row := q.db.QueryRow(ctx, setSAMLSPAccessRestricted, arg.AccessRestricted, arg.SamlSpID)
	var i SamlSp
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.DisplayName,
		&i.SpKind,
		&i.NameIDFormat,
		&i.AttributeMap,
		&i.RequireSignedAuthnRequest,
		&i.AllowIdpInitiated,
		&i.SessionLifetime,
		&i.MetadataXml,
		&i.MetadataValidUntil,
		&i.MetadataCacheDuration,
		&i.MetadataFetchedAt,
		&i.CreatedAt,
		&i.Disabled,
		&i.AccessRestricted,
	)
	return i, err
}

const updateAppGroup = `-- name: UpdateAppGroup :one
UPDATE user_group
SET slug = $1,
    display_name = $2,
    description = $3,
    exposed_to_downstream = $4,
    rule = $5,
    updated_at = now()
WHERE id = $6
  AND ($7::text IS NULL OR EXISTS (
    SELECT 1 FROM oidc_client_group og WHERE og.group_id = user_group.id
      AND og.client_id = $7::text
  ))
  AND ($8::bigint IS NULL OR EXISTS (
    SELECT 1 FROM saml_sp_group sg WHERE sg.group_id = user_group.id
      AND sg.saml_sp_id = $8::bigint
  ))
RETURNING id, kind, slug, display_name, description, exposed_to_downstream, rule, created_at, updated_at
`

type UpdateAppGroupParams struct {
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
	Rule                []byte      `json:"rule"`
	GroupID             int32       `json:"groupId"`
	OidcClientID        pgtype.Text `json:"oidcClientId"`
	SamlSpID            pgtype.Int8 `json:"samlSpId"`
}

func (q *Queries) UpdateAppGroup(ctx context.Context, arg UpdateAppGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, updateAppGroup,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
		arg.Rule,
		arg.GroupID,
		arg.OidcClientID,
		arg.SamlSpID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGlobalGroup = `-- name: UpdateGlobalGroup :one
UPDATE user_group
SET slug = $1, display_name = $2,
    description = $3, exposed_to_downstream = $4,
    rule = $5, updated_at = now()
WHERE id = $6
RETURNING id, kind, slug, display_name, description, exposed_to_downstream, rule, created_at, updated_at
`

type UpdateGlobalGroupParams struct {
	Slug                string      `json:"slug"`
	DisplayName         string      `json:"displayName"`
	Description         pgtype.Text `json:"description"`
	ExposedToDownstream bool        `json:"exposedToDownstream"`
	Rule                []byte      `json:"rule"`
	GroupID             int32       `json:"groupId"`
}

func (q *Queries) UpdateGlobalGroup(ctx context.Context, arg UpdateGlobalGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, updateGlobalGroup,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.ExposedToDownstream,
		arg.Rule,
		arg.GroupID,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ExposedToDownstream,
		&i.Rule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertManualDecision = `-- name: UpsertManualDecision :one
INSERT INTO group_manual_decision (group_id, account_id, effect, created_by)
VALUES (
  $1, $2, $3, $4
)
ON CONFLICT (group_id, account_id) DO UPDATE
SET effect = EXCLUDED.effect,
    updated_at = now()
RETURNING group_id, group_kind, account_id, effect, created_at, updated_at, created_by
`

type UpsertManualDecisionParams struct {
	GroupID   int32       `json:"groupId"`
	AccountID int32       `json:"accountId"`
	Effect    string      `json:"effect"`
	CreatedBy pgtype.Int4 `json:"createdBy"`
}

func (q *Queries) UpsertManualDecision(ctx context.Context, arg UpsertManualDecisionParams) (GroupManualDecision, error) {
	row := q.db.QueryRow(ctx, upsertManualDecision,
		arg.GroupID,
		arg.AccountID,
		arg.Effect,
		arg.CreatedBy,
	)
	var i GroupManualDecision
	err := row.Scan(
		&i.GroupID,
		&i.GroupKind,
		&i.AccountID,
		&i.Effect,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
