// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery_code.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE recovery_code
SET used_at = now(), used_session_id = $2, used_ip = $3
WHERE id = $1 AND used_at IS NULL
RETURNING id, account_id, hash, used_at, used_session_id, used_ip, created_at
`

type ConsumeRecoveryCodeParams struct {
	ID            int32       `json:"id"`
	UsedSessionID pgtype.Text `json:"usedSessionId"`
	UsedIp        *netip.Addr `json:"usedIp"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode, arg.ID, arg.UsedSessionID, arg.UsedIp)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Hash,
		&i.UsedAt,
		&i.UsedSessionID,
		&i.UsedIp,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllRecoveryCodesByAccount = `-- name: DeleteAllRecoveryCodesByAccount :exec
DELETE FROM recovery_code WHERE account_id = $1
`

func (q *Queries) DeleteAllRecoveryCodesByAccount(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, deleteAllRecoveryCodesByAccount, accountID)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :one
INSERT INTO recovery_code (account_id, hash) VALUES ($1, $2) RETURNING id, account_id, hash, used_at, used_session_id, used_ip, created_at
`

type InsertRecoveryCodeParams struct {
	AccountID int32  `json:"accountId"`
	Hash      string `json:"hash"`
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, insertRecoveryCode, arg.AccountID, arg.Hash)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Hash,
		&i.UsedAt,
		&i.UsedSessionID,
		&i.UsedIp,
		&i.CreatedAt,
	)
	return i, err
}

const listRecoveryCodesByAccount = `-- name: ListRecoveryCodesByAccount :many
SELECT id, account_id, hash, used_at, used_session_id, used_ip, created_at FROM recovery_code
WHERE account_id = $1 AND used_at IS NULL
ORDER BY id
`

func (q *Queries) ListRecoveryCodesByAccount(ctx context.Context, accountID int32) ([]RecoveryCode, error) {
	rows, err := q.db.Query(ctx, listRecoveryCodesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoveryCode
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Hash,
			&i.UsedAt,
			&i.UsedSessionID,
			&i.UsedIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
