// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saml_consent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSAMLConsent = `-- name: DeleteSAMLConsent :exec
DELETE FROM saml_consent WHERE account_id = $1 AND sp_id = $2
`

type DeleteSAMLConsentParams struct {
	AccountID int32 `json:"accountId"`
	SpID      int64 `json:"spId"`
}

func (q *Queries) DeleteSAMLConsent(ctx context.Context, arg DeleteSAMLConsentParams) error {
	_, err := q.db.Exec(ctx, deleteSAMLConsent, arg.AccountID, arg.SpID)
	return err
}

const hasSAMLConsent = `-- name: HasSAMLConsent :one
SELECT EXISTS (
  SELECT 1 FROM saml_consent WHERE account_id = $1 AND sp_id = $2
) AS has
`

type HasSAMLConsentParams struct {
	AccountID int32 `json:"accountId"`
	SpID      int64 `json:"spId"`
}

func (q *Queries) HasSAMLConsent(ctx context.Context, arg HasSAMLConsentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSAMLConsent, arg.AccountID, arg.SpID)
	var has bool
	err := row.Scan(&has)
	return has, err
}

const listSAMLConsentsByAccount = `-- name: ListSAMLConsentsByAccount :many
SELECT sc.sp_id, sp.entity_id, sp.display_name, sc.updated_at
FROM saml_consent sc
JOIN saml_sp sp ON sp.id = sc.sp_id
WHERE sc.account_id = $1
ORDER BY sp.display_name
`

type ListSAMLConsentsByAccountRow struct {
	SpID        int64              `json:"spId"`
	EntityID    string             `json:"entityId"`
	DisplayName string             `json:"displayName"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListSAMLConsentsByAccount(ctx context.Context, accountID int32) ([]ListSAMLConsentsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listSAMLConsentsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSAMLConsentsByAccountRow
	for rows.Next() {
		var i ListSAMLConsentsByAccountRow
		if err := rows.Scan(
			&i.SpID,
			&i.EntityID,
			&i.DisplayName,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSAMLConsent = `-- name: UpsertSAMLConsent :exec
INSERT INTO saml_consent (account_id, sp_id, created_at, updated_at)
VALUES ($1, $2, now(), now())
ON CONFLICT (account_id, sp_id)
DO UPDATE SET updated_at = now()
`

type UpsertSAMLConsentParams struct {
	AccountID int32 `json:"accountId"`
	SpID      int64 `json:"spId"`
}

func (q *Queries) UpsertSAMLConsent(ctx context.Context, arg UpsertSAMLConsentParams) error {
	_, err := q.db.Exec(ctx, upsertSAMLConsent, arg.AccountID, arg.SpID)
	return err
}
