// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saml_sp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredSAMLSessions = `-- name: DeleteExpiredSAMLSessions :execrows
DELETE FROM saml_session WHERE not_on_or_after < now()
`

func (q *Queries) DeleteExpiredSAMLSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSAMLSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSAMLSP = `-- name: DeleteSAMLSP :execrows
DELETE FROM saml_sp WHERE id = $1
`

func (q *Queries) DeleteSAMLSP(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSAMLSP, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSAMLSPACSByID = `-- name: DeleteSAMLSPACSByID :exec
DELETE FROM saml_sp_acs WHERE sp_id = $1
`

func (q *Queries) DeleteSAMLSPACSByID(ctx context.Context, spID int64) error {
	_, err := q.db.Exec(ctx, deleteSAMLSPACSByID, spID)
	return err
}

const deleteSAMLSPKeysByID = `-- name: DeleteSAMLSPKeysByID :exec
DELETE FROM saml_sp_key WHERE sp_id = $1
`

func (q *Queries) DeleteSAMLSPKeysByID(ctx context.Context, spID int64) error {
	_, err := q.db.Exec(ctx, deleteSAMLSPKeysByID, spID)
	return err
}

const deleteSAMLSessionsBySession = `-- name: DeleteSAMLSessionsBySession :exec
DELETE FROM saml_session WHERE session_id = $1
`

func (q *Queries) DeleteSAMLSessionsBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSAMLSessionsBySession, sessionID)
	return err
}

const getSAMLSPByEntityID = `-- name: GetSAMLSPByEntityID :one
SELECT id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled FROM saml_sp WHERE entity_id = $1
`

func (q *Queries) GetSAMLSPByEntityID(ctx context.Context, entityID string) (SamlSp, error) {
	row := q.db.QueryRow(ctx, getSAMLSPByEntityID, entityID)
	var i SamlSp
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.DisplayName,
		&i.SpKind,
		&i.NameIDFormat,
		&i.AttributeMap,
		&i.RequireSignedAuthnRequest,
		&i.AllowIdpInitiated,
		&i.SessionLifetime,
		&i.MetadataXml,
		&i.MetadataValidUntil,
		&i.MetadataCacheDuration,
		&i.MetadataFetchedAt,
		&i.CreatedAt,
		&i.Disabled,
	)
	return i, err
}

const getSAMLSPByID = `-- name: GetSAMLSPByID :one
SELECT id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled FROM saml_sp WHERE id = $1
`

func (q *Queries) GetSAMLSPByID(ctx context.Context, id int64) (SamlSp, error) {
	row := q.db.QueryRow(ctx, getSAMLSPByID, id)
	var i SamlSp
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.DisplayName,
		&i.SpKind,
		&i.NameIDFormat,
		&i.AttributeMap,
		&i.RequireSignedAuthnRequest,
		&i.AllowIdpInitiated,
		&i.SessionLifetime,
		&i.MetadataXml,
		&i.MetadataValidUntil,
		&i.MetadataCacheDuration,
		&i.MetadataFetchedAt,
		&i.CreatedAt,
		&i.Disabled,
	)
	return i, err
}

const getSAMLSubjectID = `-- name: GetSAMLSubjectID :one
SELECT account_id, sp_id, name_id, name_id_format, created_at FROM saml_subject_id WHERE account_id = $1 AND sp_id = $2
`

type GetSAMLSubjectIDParams struct {
	AccountID int32 `json:"accountId"`
	SpID      int64 `json:"spId"`
}

func (q *Queries) GetSAMLSubjectID(ctx context.Context, arg GetSAMLSubjectIDParams) (SamlSubjectID, error) {
	row := q.db.QueryRow(ctx, getSAMLSubjectID, arg.AccountID, arg.SpID)
	var i SamlSubjectID
	err := row.Scan(
		&i.AccountID,
		&i.SpID,
		&i.NameID,
		&i.NameIDFormat,
		&i.CreatedAt,
	)
	return i, err
}

const insertSAMLSP = `-- name: InsertSAMLSP :one
INSERT INTO saml_sp (entity_id, display_name, sp_kind, name_id_format,
  attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime,
  metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled
`

type InsertSAMLSPParams struct {
	EntityID                  string             `json:"entityId"`
	DisplayName               string             `json:"displayName"`
	SpKind                    pgtype.Text        `json:"spKind"`
	NameIDFormat              string             `json:"nameIdFormat"`
	AttributeMap              []byte             `json:"attributeMap"`
	RequireSignedAuthnRequest bool               `json:"requireSignedAuthnRequest"`
	AllowIdpInitiated         bool               `json:"allowIdpInitiated"`
	SessionLifetime           pgtype.Interval    `json:"sessionLifetime"`
	MetadataXml               pgtype.Text        `json:"metadataXml"`
	MetadataValidUntil        pgtype.Timestamptz `json:"metadataValidUntil"`
	MetadataCacheDuration     pgtype.Interval    `json:"metadataCacheDuration"`
	MetadataFetchedAt         pgtype.Timestamptz `json:"metadataFetchedAt"`
}

func (q *Queries) InsertSAMLSP(ctx context.Context, arg InsertSAMLSPParams) (SamlSp, error) {
	row := q.db.QueryRow(ctx, insertSAMLSP,
		arg.EntityID,
		arg.DisplayName,
		arg.SpKind,
		arg.NameIDFormat,
		arg.AttributeMap,
		arg.RequireSignedAuthnRequest,
		arg.AllowIdpInitiated,
		arg.SessionLifetime,
		arg.MetadataXml,
		arg.MetadataValidUntil,
		arg.MetadataCacheDuration,
		arg.MetadataFetchedAt,
	)
	var i SamlSp
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.DisplayName,
		&i.SpKind,
		&i.NameIDFormat,
		&i.AttributeMap,
		&i.RequireSignedAuthnRequest,
		&i.AllowIdpInitiated,
		&i.SessionLifetime,
		&i.MetadataXml,
		&i.MetadataValidUntil,
		&i.MetadataCacheDuration,
		&i.MetadataFetchedAt,
		&i.CreatedAt,
		&i.Disabled,
	)
	return i, err
}

const insertSAMLSPACS = `-- name: InsertSAMLSPACS :exec
INSERT INTO saml_sp_acs (sp_id, idx, binding, location, is_default)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSAMLSPACSParams struct {
	SpID      int64  `json:"spId"`
	Idx       int32  `json:"idx"`
	Binding   string `json:"binding"`
	Location  string `json:"location"`
	IsDefault bool   `json:"isDefault"`
}

func (q *Queries) InsertSAMLSPACS(ctx context.Context, arg InsertSAMLSPACSParams) error {
	_, err := q.db.Exec(ctx, insertSAMLSPACS,
		arg.SpID,
		arg.Idx,
		arg.Binding,
		arg.Location,
		arg.IsDefault,
	)
	return err
}

const insertSAMLSPKey = `-- name: InsertSAMLSPKey :exec
INSERT INTO saml_sp_key (sp_id, use, cert_pem, not_after)
VALUES ($1, $2, $3, $4)
`

type InsertSAMLSPKeyParams struct {
	SpID     int64              `json:"spId"`
	Use      string             `json:"use"`
	CertPem  string             `json:"certPem"`
	NotAfter pgtype.Timestamptz `json:"notAfter"`
}

func (q *Queries) InsertSAMLSPKey(ctx context.Context, arg InsertSAMLSPKeyParams) error {
	_, err := q.db.Exec(ctx, insertSAMLSPKey,
		arg.SpID,
		arg.Use,
		arg.CertPem,
		arg.NotAfter,
	)
	return err
}

const insertSAMLSession = `-- name: InsertSAMLSession :one
INSERT INTO saml_session (session_id, sp_id, name_id, session_index, not_on_or_after)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id, sp_id, session_index)
  DO UPDATE SET not_on_or_after = EXCLUDED.not_on_or_after
RETURNING id, session_id, sp_id, name_id, session_index, not_on_or_after, created_at
`

type InsertSAMLSessionParams struct {
	SessionID    string             `json:"sessionId"`
	SpID         int64              `json:"spId"`
	NameID       string             `json:"nameId"`
	SessionIndex string             `json:"sessionIndex"`
	NotOnOrAfter pgtype.Timestamptz `json:"notOnOrAfter"`
}

func (q *Queries) InsertSAMLSession(ctx context.Context, arg InsertSAMLSessionParams) (SamlSession, error) {
	row := q.db.QueryRow(ctx, insertSAMLSession,
		arg.SessionID,
		arg.SpID,
		arg.NameID,
		arg.SessionIndex,
		arg.NotOnOrAfter,
	)
	var i SamlSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SpID,
		&i.NameID,
		&i.SessionIndex,
		&i.NotOnOrAfter,
		&i.CreatedAt,
	)
	return i, err
}

const insertSAMLSubjectID = `-- name: InsertSAMLSubjectID :one
INSERT INTO saml_subject_id (account_id, sp_id, name_id, name_id_format)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, sp_id) DO UPDATE SET name_id = saml_subject_id.name_id
RETURNING account_id, sp_id, name_id, name_id_format, created_at
`

type InsertSAMLSubjectIDParams struct {
	AccountID    int32  `json:"accountId"`
	SpID         int64  `json:"spId"`
	NameID       string `json:"nameId"`
	NameIDFormat string `json:"nameIdFormat"`
}

func (q *Queries) InsertSAMLSubjectID(ctx context.Context, arg InsertSAMLSubjectIDParams) (SamlSubjectID, error) {
	row := q.db.QueryRow(ctx, insertSAMLSubjectID,
		arg.AccountID,
		arg.SpID,
		arg.NameID,
		arg.NameIDFormat,
	)
	var i SamlSubjectID
	err := row.Scan(
		&i.AccountID,
		&i.SpID,
		&i.NameID,
		&i.NameIDFormat,
		&i.CreatedAt,
	)
	return i, err
}

const listSAMLSPACSEndpoints = `-- name: ListSAMLSPACSEndpoints :many
SELECT sp_id, idx, binding, location, is_default FROM saml_sp_acs WHERE sp_id = $1 ORDER BY idx
`

func (q *Queries) ListSAMLSPACSEndpoints(ctx context.Context, spID int64) ([]SamlSpAc, error) {
	rows, err := q.db.Query(ctx, listSAMLSPACSEndpoints, spID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamlSpAc
	for rows.Next() {
		var i SamlSpAc
		if err := rows.Scan(
			&i.SpID,
			&i.Idx,
			&i.Binding,
			&i.Location,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPKeys = `-- name: ListSAMLSPKeys :many
SELECT id, sp_id, use, cert_pem, not_after, added_at FROM saml_sp_key WHERE sp_id = $1 AND use = $2
ORDER BY added_at DESC
`

type ListSAMLSPKeysParams struct {
	SpID int64  `json:"spId"`
	Use  string `json:"use"`
}

func (q *Queries) ListSAMLSPKeys(ctx context.Context, arg ListSAMLSPKeysParams) ([]SamlSpKey, error) {
	rows, err := q.db.Query(ctx, listSAMLSPKeys, arg.SpID, arg.Use)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamlSpKey
	for rows.Next() {
		var i SamlSpKey
		if err := rows.Scan(
			&i.ID,
			&i.SpID,
			&i.Use,
			&i.CertPem,
			&i.NotAfter,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSPs = `-- name: ListSAMLSPs :many
SELECT id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled FROM saml_sp ORDER BY display_name
`

func (q *Queries) ListSAMLSPs(ctx context.Context) ([]SamlSp, error) {
	rows, err := q.db.Query(ctx, listSAMLSPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamlSp
	for rows.Next() {
		var i SamlSp
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.DisplayName,
			&i.SpKind,
			&i.NameIDFormat,
			&i.AttributeMap,
			&i.RequireSignedAuthnRequest,
			&i.AllowIdpInitiated,
			&i.SessionLifetime,
			&i.MetadataXml,
			&i.MetadataValidUntil,
			&i.MetadataCacheDuration,
			&i.MetadataFetchedAt,
			&i.CreatedAt,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSessionsByNameID = `-- name: ListSAMLSessionsByNameID :many
SELECT id, session_id, sp_id, name_id, session_index, not_on_or_after, created_at FROM saml_session WHERE sp_id = $1 AND name_id = $2
`

type ListSAMLSessionsByNameIDParams struct {
	SpID   int64  `json:"spId"`
	NameID string `json:"nameId"`
}

func (q *Queries) ListSAMLSessionsByNameID(ctx context.Context, arg ListSAMLSessionsByNameIDParams) ([]SamlSession, error) {
	rows, err := q.db.Query(ctx, listSAMLSessionsByNameID, arg.SpID, arg.NameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamlSession
	for rows.Next() {
		var i SamlSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SpID,
			&i.NameID,
			&i.SessionIndex,
			&i.NotOnOrAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSAMLSessionsBySession = `-- name: ListSAMLSessionsBySession :many
SELECT id, session_id, sp_id, name_id, session_index, not_on_or_after, created_at FROM saml_session WHERE session_id = $1
`

func (q *Queries) ListSAMLSessionsBySession(ctx context.Context, sessionID string) ([]SamlSession, error) {
	rows, err := q.db.Query(ctx, listSAMLSessionsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SamlSession
	for rows.Next() {
		var i SamlSession
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SpID,
			&i.NameID,
			&i.SessionIndex,
			&i.NotOnOrAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSAMLSPDisabled = `-- name: SetSAMLSPDisabled :one
UPDATE saml_sp SET disabled = $2 WHERE id = $1 RETURNING id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled
`

type SetSAMLSPDisabledParams struct {
	ID       int64 `json:"id"`
	Disabled bool  `json:"disabled"`
}

func (q *Queries) SetSAMLSPDisabled(ctx context.Context, arg SetSAMLSPDisabledParams) (SamlSp, error) {
	row := q.db.QueryRow(ctx, setSAMLSPDisabled, arg.ID, arg.Disabled)
	var i SamlSp
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.DisplayName,
		&i.SpKind,
		&i.NameIDFormat,
		&i.AttributeMap,
		&i.RequireSignedAuthnRequest,
		&i.AllowIdpInitiated,
		&i.SessionLifetime,
		&i.MetadataXml,
		&i.MetadataValidUntil,
		&i.MetadataCacheDuration,
		&i.MetadataFetchedAt,
		&i.CreatedAt,
		&i.Disabled,
	)
	return i, err
}

const updateSAMLSP = `-- name: UpdateSAMLSP :one
UPDATE saml_sp SET
  display_name                 = $2,
  name_id_format               = $3,
  require_signed_authn_request = $4,
  allow_idp_initiated          = $5,
  session_lifetime             = $6,
  attribute_map                = $7
WHERE id = $1
RETURNING id, entity_id, display_name, sp_kind, name_id_format, attribute_map, require_signed_authn_request, allow_idp_initiated, session_lifetime, metadata_xml, metadata_valid_until, metadata_cache_duration, metadata_fetched_at, created_at, disabled
`

type UpdateSAMLSPParams struct {
	ID                        int64           `json:"id"`
	DisplayName               string          `json:"displayName"`
	NameIDFormat              string          `json:"nameIdFormat"`
	RequireSignedAuthnRequest bool            `json:"requireSignedAuthnRequest"`
	AllowIdpInitiated         bool            `json:"allowIdpInitiated"`
	SessionLifetime           pgtype.Interval `json:"sessionLifetime"`
	AttributeMap              []byte          `json:"attributeMap"`
}

func (q *Queries) UpdateSAMLSP(ctx context.Context, arg UpdateSAMLSPParams) (SamlSp, error) {
	row := q.db.QueryRow(ctx, updateSAMLSP,
		arg.ID,
		arg.DisplayName,
		arg.NameIDFormat,
		arg.RequireSignedAuthnRequest,
		arg.AllowIdpInitiated,
		arg.SessionLifetime,
		arg.AttributeMap,
	)
	var i SamlSp
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.DisplayName,
		&i.SpKind,
		&i.NameIDFormat,
		&i.AttributeMap,
		&i.RequireSignedAuthnRequest,
		&i.AllowIdpInitiated,
		&i.SessionLifetime,
		&i.MetadataXml,
		&i.MetadataValidUntil,
		&i.MetadataCacheDuration,
		&i.MetadataFetchedAt,
		&i.CreatedAt,
		&i.Disabled,
	)
	return i, err
}
