// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSession = `-- name: GetSession :one
SELECT id, account_id, auth_time, amr, acr, created_at, revoked_at FROM session WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AuthTime,
		&i.Amr,
		&i.Acr,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO session (id, account_id, auth_time, amr, acr)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, auth_time, amr, acr, created_at, revoked_at
`

type InsertSessionParams struct {
	ID        string             `json:"id"`
	AccountID int32              `json:"accountId"`
	AuthTime  pgtype.Timestamptz `json:"authTime"`
	Amr       []string           `json:"amr"`
	Acr       pgtype.Text        `json:"acr"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.AccountID,
		arg.AuthTime,
		arg.Amr,
		arg.Acr,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AuthTime,
		&i.Amr,
		&i.Acr,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listSessionsByAccount = `-- name: ListSessionsByAccount :many
SELECT id, account_id, auth_time, amr, acr, created_at, revoked_at FROM session
WHERE account_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByAccount(ctx context.Context, accountID int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AuthTime,
			&i.Amr,
			&i.Acr,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsByAccount = `-- name: RevokeAllSessionsByAccount :exec
UPDATE session SET revoked_at = now()
WHERE account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsByAccount(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsByAccount, accountID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE session SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
