// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: totp_credential.sql

package db

import (
	"context"
)

const confirmTOTPCredential = `-- name: ConfirmTOTPCredential :exec
UPDATE totp_credential SET confirmed_at = now()
WHERE account_id = $1 AND confirmed_at IS NULL
`

func (q *Queries) ConfirmTOTPCredential(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, confirmTOTPCredential, accountID)
	return err
}

const deleteTOTPCredential = `-- name: DeleteTOTPCredential :exec
DELETE FROM totp_credential WHERE account_id = $1
`

func (q *Queries) DeleteTOTPCredential(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, deleteTOTPCredential, accountID)
	return err
}

const getTOTPCredential = `-- name: GetTOTPCredential :one
SELECT account_id, secret_enc, secret_nonce, key_version, period, digits, algorithm, last_step, confirmed_at, created_at FROM totp_credential WHERE account_id = $1
`

func (q *Queries) GetTOTPCredential(ctx context.Context, accountID int32) (TotpCredential, error) {
	row := q.db.QueryRow(ctx, getTOTPCredential, accountID)
	var i TotpCredential
	err := row.Scan(
		&i.AccountID,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Period,
		&i.Digits,
		&i.Algorithm,
		&i.LastStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertTOTPCredential = `-- name: InsertTOTPCredential :one
INSERT INTO totp_credential (account_id, secret_enc, secret_nonce, key_version, period, digits, algorithm)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING account_id, secret_enc, secret_nonce, key_version, period, digits, algorithm, last_step, confirmed_at, created_at
`

type InsertTOTPCredentialParams struct {
	AccountID   int32  `json:"accountId"`
	SecretEnc   []byte `json:"secretEnc"`
	SecretNonce []byte `json:"secretNonce"`
	KeyVersion  int32  `json:"keyVersion"`
	Period      int32  `json:"period"`
	Digits      int32  `json:"digits"`
	Algorithm   string `json:"algorithm"`
}

func (q *Queries) InsertTOTPCredential(ctx context.Context, arg InsertTOTPCredentialParams) (TotpCredential, error) {
	row := q.db.QueryRow(ctx, insertTOTPCredential,
		arg.AccountID,
		arg.SecretEnc,
		arg.SecretNonce,
		arg.KeyVersion,
		arg.Period,
		arg.Digits,
		arg.Algorithm,
	)
	var i TotpCredential
	err := row.Scan(
		&i.AccountID,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Period,
		&i.Digits,
		&i.Algorithm,
		&i.LastStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateTOTPLastStep = `-- name: UpdateTOTPLastStep :exec
UPDATE totp_credential SET last_step = $2
WHERE account_id = $1 AND $2 > last_step
`

type UpdateTOTPLastStepParams struct {
	AccountID int32 `json:"accountId"`
	LastStep  int64 `json:"lastStep"`
}

func (q *Queries) UpdateTOTPLastStep(ctx context.Context, arg UpdateTOTPLastStepParams) error {
	_, err := q.db.Exec(ctx, updateTOTPLastStep, arg.AccountID, arg.LastStep)
	return err
}
