// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upstream_idp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUpstreamIDP = `-- name: DeleteUpstreamIDP :exec
DELETE FROM upstream_idp WHERE id = $1
`

func (q *Queries) DeleteUpstreamIDP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUpstreamIDP, id)
	return err
}

const getUpstreamIDPBySlug = `-- name: GetUpstreamIDPBySlug :one
SELECT id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at FROM upstream_idp WHERE slug = $1 AND NOT disabled
`

func (q *Queries) GetUpstreamIDPBySlug(ctx context.Context, slug string) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, getUpstreamIDPBySlug, slug)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Mode,
		&i.Disabled,
		&i.CreatedAt,
		&i.Protocol,
		&i.ProviderConfig,
		&i.SecretStatus,
		&i.SecretValidatedAt,
	)
	return i, err
}

const getUpstreamIDPBySlugAny = `-- name: GetUpstreamIDPBySlugAny :one
SELECT id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at FROM upstream_idp WHERE slug = $1
`

func (q *Queries) GetUpstreamIDPBySlugAny(ctx context.Context, slug string) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, getUpstreamIDPBySlugAny, slug)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Mode,
		&i.Disabled,
		&i.CreatedAt,
		&i.Protocol,
		&i.ProviderConfig,
		&i.SecretStatus,
		&i.SecretValidatedAt,
	)
	return i, err
}

const insertUpstreamIDP = `-- name: InsertUpstreamIDP :one
INSERT INTO upstream_idp (
  slug, display_name, protocol, mode, provider_config,
  secret_enc, secret_nonce, key_version, secret_status,
  secret_validated_at, disabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at
`

type InsertUpstreamIDPParams struct {
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"displayName"`
	Protocol          string             `json:"protocol"`
	Mode              string             `json:"mode"`
	ProviderConfig    []byte             `json:"providerConfig"`
	SecretEnc         []byte             `json:"secretEnc"`
	SecretNonce       []byte             `json:"secretNonce"`
	KeyVersion        pgtype.Int4        `json:"keyVersion"`
	SecretStatus      string             `json:"secretStatus"`
	SecretValidatedAt pgtype.Timestamptz `json:"secretValidatedAt"`
	Disabled          bool               `json:"disabled"`
}

func (q *Queries) InsertUpstreamIDP(ctx context.Context, arg InsertUpstreamIDPParams) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, insertUpstreamIDP,
		arg.Slug,
		arg.DisplayName,
		arg.Protocol,
		arg.Mode,
		arg.ProviderConfig,
		arg.SecretEnc,
		arg.SecretNonce,
		arg.KeyVersion,
		arg.SecretStatus,
		arg.SecretValidatedAt,
		arg.Disabled,
	)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Mode,
		&i.Disabled,
		&i.CreatedAt,
		&i.Protocol,
		&i.ProviderConfig,
		&i.SecretStatus,
		&i.SecretValidatedAt,
	)
	return i, err
}

const listAllUpstreamIDPs = `-- name: ListAllUpstreamIDPs :many
SELECT id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at FROM upstream_idp
WHERE ($1::timestamptz IS NULL OR (created_at, id) < ($1, $2::int8))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAllUpstreamIDPsParams struct {
	AfterCreatedAt pgtype.Timestamptz `json:"afterCreatedAt"`
	AfterID        pgtype.Int8        `json:"afterId"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListAllUpstreamIDPs(ctx context.Context, arg ListAllUpstreamIDPsParams) ([]UpstreamIdp, error) {
	rows, err := q.db.Query(ctx, listAllUpstreamIDPs, arg.AfterCreatedAt, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamIdp
	for rows.Next() {
		var i UpstreamIdp
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.SecretEnc,
			&i.SecretNonce,
			&i.KeyVersion,
			&i.Mode,
			&i.Disabled,
			&i.CreatedAt,
			&i.Protocol,
			&i.ProviderConfig,
			&i.SecretStatus,
			&i.SecretValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpstreamIDPs = `-- name: ListUpstreamIDPs :many
SELECT id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at FROM upstream_idp WHERE NOT disabled ORDER BY display_name
`

func (q *Queries) ListUpstreamIDPs(ctx context.Context) ([]UpstreamIdp, error) {
	rows, err := q.db.Query(ctx, listUpstreamIDPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamIdp
	for rows.Next() {
		var i UpstreamIdp
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.SecretEnc,
			&i.SecretNonce,
			&i.KeyVersion,
			&i.Mode,
			&i.Disabled,
			&i.CreatedAt,
			&i.Protocol,
			&i.ProviderConfig,
			&i.SecretStatus,
			&i.SecretValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUpstreamIDPDisabled = `-- name: SetUpstreamIDPDisabled :one
UPDATE upstream_idp SET disabled = $2 WHERE slug = $1 RETURNING id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at
`

type SetUpstreamIDPDisabledParams struct {
	Slug     string `json:"slug"`
	Disabled bool   `json:"disabled"`
}

func (q *Queries) SetUpstreamIDPDisabled(ctx context.Context, arg SetUpstreamIDPDisabledParams) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, setUpstreamIDPDisabled, arg.Slug, arg.Disabled)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Mode,
		&i.Disabled,
		&i.CreatedAt,
		&i.Protocol,
		&i.ProviderConfig,
		&i.SecretStatus,
		&i.SecretValidatedAt,
	)
	return i, err
}

const updateUpstreamIDPConfig = `-- name: UpdateUpstreamIDPConfig :one
UPDATE upstream_idp SET
  display_name = $2, mode = $3, provider_config = $4
WHERE slug = $1
RETURNING id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at
`

type UpdateUpstreamIDPConfigParams struct {
	Slug           string `json:"slug"`
	DisplayName    string `json:"displayName"`
	Mode           string `json:"mode"`
	ProviderConfig []byte `json:"providerConfig"`
}

func (q *Queries) UpdateUpstreamIDPConfig(ctx context.Context, arg UpdateUpstreamIDPConfigParams) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, updateUpstreamIDPConfig,
		arg.Slug,
		arg.DisplayName,
		arg.Mode,
		arg.ProviderConfig,
	)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Mode,
		&i.Disabled,
		&i.CreatedAt,
		&i.Protocol,
		&i.ProviderConfig,
		&i.SecretStatus,
		&i.SecretValidatedAt,
	)
	return i, err
}

const updateUpstreamIDPHealth = `-- name: UpdateUpstreamIDPHealth :one
UPDATE upstream_idp SET secret_status = $2, secret_validated_at = $3
WHERE slug = $1
RETURNING id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at
`

type UpdateUpstreamIDPHealthParams struct {
	Slug              string             `json:"slug"`
	SecretStatus      string             `json:"secretStatus"`
	SecretValidatedAt pgtype.Timestamptz `json:"secretValidatedAt"`
}

func (q *Queries) UpdateUpstreamIDPHealth(ctx context.Context, arg UpdateUpstreamIDPHealthParams) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, updateUpstreamIDPHealth, arg.Slug, arg.SecretStatus, arg.SecretValidatedAt)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Mode,
		&i.Disabled,
		&i.CreatedAt,
		&i.Protocol,
		&i.ProviderConfig,
		&i.SecretStatus,
		&i.SecretValidatedAt,
	)
	return i, err
}

const updateUpstreamIDPSecret = `-- name: UpdateUpstreamIDPSecret :one
UPDATE upstream_idp SET
  secret_enc = $2, secret_nonce = $3, key_version = $4,
  secret_status = $5, secret_validated_at = $6
WHERE slug = $1
RETURNING id, slug, display_name, secret_enc, secret_nonce, key_version, mode, disabled, created_at, protocol, provider_config, secret_status, secret_validated_at
`

type UpdateUpstreamIDPSecretParams struct {
	Slug              string             `json:"slug"`
	SecretEnc         []byte             `json:"secretEnc"`
	SecretNonce       []byte             `json:"secretNonce"`
	KeyVersion        pgtype.Int4        `json:"keyVersion"`
	SecretStatus      string             `json:"secretStatus"`
	SecretValidatedAt pgtype.Timestamptz `json:"secretValidatedAt"`
}

func (q *Queries) UpdateUpstreamIDPSecret(ctx context.Context, arg UpdateUpstreamIDPSecretParams) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, updateUpstreamIDPSecret,
		arg.Slug,
		arg.SecretEnc,
		arg.SecretNonce,
		arg.KeyVersion,
		arg.SecretStatus,
		arg.SecretValidatedAt,
	)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.SecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Mode,
		&i.Disabled,
		&i.CreatedAt,
		&i.Protocol,
		&i.ProviderConfig,
		&i.SecretStatus,
		&i.SecretValidatedAt,
	)
	return i, err
}
