// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upstream_idp.sql

package db

import (
	"context"
)

const deleteUpstreamIDP = `-- name: DeleteUpstreamIDP :exec
DELETE FROM upstream_idp WHERE id = $1
`

func (q *Queries) DeleteUpstreamIDP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUpstreamIDP, id)
	return err
}

const getUpstreamIDPBySlug = `-- name: GetUpstreamIDPBySlug :one
SELECT id, slug, display_name, issuer_url, client_id, client_secret_enc, secret_nonce, key_version, scopes, mode, allowed_domains, username_claim, display_name_claim, email_claim, disabled, created_at, require_verified_email FROM upstream_idp WHERE slug = $1 AND NOT disabled
`

func (q *Queries) GetUpstreamIDPBySlug(ctx context.Context, slug string) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, getUpstreamIDPBySlug, slug)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Scopes,
		&i.Mode,
		&i.AllowedDomains,
		&i.UsernameClaim,
		&i.DisplayNameClaim,
		&i.EmailClaim,
		&i.Disabled,
		&i.CreatedAt,
		&i.RequireVerifiedEmail,
	)
	return i, err
}

const insertUpstreamIDP = `-- name: InsertUpstreamIDP :one
INSERT INTO upstream_idp (slug, display_name, issuer_url, client_id,
  client_secret_enc, secret_nonce, key_version, scopes, mode,
  allowed_domains, username_claim, display_name_claim, email_claim,
  require_verified_email)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, slug, display_name, issuer_url, client_id, client_secret_enc, secret_nonce, key_version, scopes, mode, allowed_domains, username_claim, display_name_claim, email_claim, disabled, created_at, require_verified_email
`

type InsertUpstreamIDPParams struct {
	Slug                 string   `json:"slug"`
	DisplayName          string   `json:"displayName"`
	IssuerUrl            string   `json:"issuerUrl"`
	ClientID             string   `json:"clientId"`
	ClientSecretEnc      []byte   `json:"clientSecretEnc"`
	SecretNonce          []byte   `json:"secretNonce"`
	KeyVersion           int32    `json:"keyVersion"`
	Scopes               []string `json:"scopes"`
	Mode                 string   `json:"mode"`
	AllowedDomains       []string `json:"allowedDomains"`
	UsernameClaim        string   `json:"usernameClaim"`
	DisplayNameClaim     string   `json:"displayNameClaim"`
	EmailClaim           string   `json:"emailClaim"`
	RequireVerifiedEmail bool     `json:"requireVerifiedEmail"`
}

func (q *Queries) InsertUpstreamIDP(ctx context.Context, arg InsertUpstreamIDPParams) (UpstreamIdp, error) {
	row := q.db.QueryRow(ctx, insertUpstreamIDP,
		arg.Slug,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.SecretNonce,
		arg.KeyVersion,
		arg.Scopes,
		arg.Mode,
		arg.AllowedDomains,
		arg.UsernameClaim,
		arg.DisplayNameClaim,
		arg.EmailClaim,
		arg.RequireVerifiedEmail,
	)
	var i UpstreamIdp
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.SecretNonce,
		&i.KeyVersion,
		&i.Scopes,
		&i.Mode,
		&i.AllowedDomains,
		&i.UsernameClaim,
		&i.DisplayNameClaim,
		&i.EmailClaim,
		&i.Disabled,
		&i.CreatedAt,
		&i.RequireVerifiedEmail,
	)
	return i, err
}

const listUpstreamIDPs = `-- name: ListUpstreamIDPs :many
SELECT id, slug, display_name, issuer_url, client_id, client_secret_enc, secret_nonce, key_version, scopes, mode, allowed_domains, username_claim, display_name_claim, email_claim, disabled, created_at, require_verified_email FROM upstream_idp WHERE NOT disabled ORDER BY display_name
`

func (q *Queries) ListUpstreamIDPs(ctx context.Context) ([]UpstreamIdp, error) {
	rows, err := q.db.Query(ctx, listUpstreamIDPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamIdp
	for rows.Next() {
		var i UpstreamIdp
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.IssuerUrl,
			&i.ClientID,
			&i.ClientSecretEnc,
			&i.SecretNonce,
			&i.KeyVersion,
			&i.Scopes,
			&i.Mode,
			&i.AllowedDomains,
			&i.UsernameClaim,
			&i.DisplayNameClaim,
			&i.EmailClaim,
			&i.Disabled,
			&i.CreatedAt,
			&i.RequireVerifiedEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUpstreamIDP = `-- name: UpdateUpstreamIDP :exec
UPDATE upstream_idp
SET display_name = $2, issuer_url = $3, client_id = $4,
    client_secret_enc = $5, secret_nonce = $6, key_version = $7,
    scopes = $8, mode = $9, allowed_domains = $10,
    username_claim = $11, display_name_claim = $12, email_claim = $13,
    disabled = $14, require_verified_email = $15
WHERE id = $1
`

type UpdateUpstreamIDPParams struct {
	ID                   int64    `json:"id"`
	DisplayName          string   `json:"displayName"`
	IssuerUrl            string   `json:"issuerUrl"`
	ClientID             string   `json:"clientId"`
	ClientSecretEnc      []byte   `json:"clientSecretEnc"`
	SecretNonce          []byte   `json:"secretNonce"`
	KeyVersion           int32    `json:"keyVersion"`
	Scopes               []string `json:"scopes"`
	Mode                 string   `json:"mode"`
	AllowedDomains       []string `json:"allowedDomains"`
	UsernameClaim        string   `json:"usernameClaim"`
	DisplayNameClaim     string   `json:"displayNameClaim"`
	EmailClaim           string   `json:"emailClaim"`
	Disabled             bool     `json:"disabled"`
	RequireVerifiedEmail bool     `json:"requireVerifiedEmail"`
}

func (q *Queries) UpdateUpstreamIDP(ctx context.Context, arg UpdateUpstreamIDPParams) error {
	_, err := q.db.Exec(ctx, updateUpstreamIDP,
		arg.ID,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.SecretNonce,
		arg.KeyVersion,
		arg.Scopes,
		arg.Mode,
		arg.AllowedDomains,
		arg.UsernameClaim,
		arg.DisplayNameClaim,
		arg.EmailClaim,
		arg.Disabled,
		arg.RequireVerifiedEmail,
	)
	return err
}
