// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webauthn_credential.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCredentialsByAccount = `-- name: CountCredentialsByAccount :one
SELECT COUNT(*) FROM webauthn_credential WHERE account_id = $1
`

func (q *Queries) CountCredentialsByAccount(ctx context.Context, accountID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentialsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllCredentialsForAccount = `-- name: DeleteAllCredentialsForAccount :exec
DELETE FROM webauthn_credential WHERE account_id = $1
`

func (q *Queries) DeleteAllCredentialsForAccount(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, deleteAllCredentialsForAccount, accountID)
	return err
}

const deleteCredentialByID = `-- name: DeleteCredentialByID :execrows
DELETE FROM webauthn_credential
WHERE id = $1 AND account_id = $2
`

type DeleteCredentialByIDParams struct {
	ID        int32 `json:"id"`
	AccountID int32 `json:"accountId"`
}

// Owner-scoped delete: zero rows affected means the id doesn't match an owned
// credential; handlers map that to credential_not_found.
func (q *Queries) DeleteCredentialByID(ctx context.Context, arg DeleteCredentialByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCredentialByID, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredentialByCredentialID = `-- name: GetCredentialByCredentialID :one
SELECT id, account_id, credential_id, public_key, cose_alg, user_handle, sign_count, transports, aaguid, attestation_type, backup_eligible, backup_state, uv_initialized, nickname, last_used_at, clone_warning_at, created_at FROM webauthn_credential WHERE credential_id = $1
`

func (q *Queries) GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CredentialID,
		&i.PublicKey,
		&i.CoseAlg,
		&i.UserHandle,
		&i.SignCount,
		&i.Transports,
		&i.Aaguid,
		&i.AttestationType,
		&i.BackupEligible,
		&i.BackupState,
		&i.UvInitialized,
		&i.Nickname,
		&i.LastUsedAt,
		&i.CloneWarningAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :one
INSERT INTO webauthn_credential (
  account_id, credential_id, public_key, cose_alg, user_handle, sign_count,
  transports, aaguid, attestation_type, backup_eligible, backup_state,
  uv_initialized, nickname
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, account_id, credential_id, public_key, cose_alg, user_handle, sign_count, transports, aaguid, attestation_type, backup_eligible, backup_state, uv_initialized, nickname, last_used_at, clone_warning_at, created_at
`

type InsertCredentialParams struct {
	AccountID       int32       `json:"accountId"`
	CredentialID    []byte      `json:"credentialId"`
	PublicKey       []byte      `json:"publicKey"`
	CoseAlg         int32       `json:"coseAlg"`
	UserHandle      []byte      `json:"userHandle"`
	SignCount       int64       `json:"signCount"`
	Transports      []string    `json:"transports"`
	Aaguid          []byte      `json:"aaguid"`
	AttestationType pgtype.Text `json:"attestationType"`
	BackupEligible  pgtype.Bool `json:"backupEligible"`
	BackupState     pgtype.Bool `json:"backupState"`
	UvInitialized   bool        `json:"uvInitialized"`
	Nickname        pgtype.Text `json:"nickname"`
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, insertCredential,
		arg.AccountID,
		arg.CredentialID,
		arg.PublicKey,
		arg.CoseAlg,
		arg.UserHandle,
		arg.SignCount,
		arg.Transports,
		arg.Aaguid,
		arg.AttestationType,
		arg.BackupEligible,
		arg.BackupState,
		arg.UvInitialized,
		arg.Nickname,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CredentialID,
		&i.PublicKey,
		&i.CoseAlg,
		&i.UserHandle,
		&i.SignCount,
		&i.Transports,
		&i.Aaguid,
		&i.AttestationType,
		&i.BackupEligible,
		&i.BackupState,
		&i.UvInitialized,
		&i.Nickname,
		&i.LastUsedAt,
		&i.CloneWarningAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCredentialsByAccount = `-- name: ListCredentialsByAccount :many
SELECT id, account_id, credential_id, public_key, cose_alg, user_handle, sign_count, transports, aaguid, attestation_type, backup_eligible, backup_state, uv_initialized, nickname, last_used_at, clone_warning_at, created_at FROM webauthn_credential WHERE account_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCredentialsByAccount(ctx context.Context, accountID int32) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CredentialID,
			&i.PublicKey,
			&i.CoseAlg,
			&i.UserHandle,
			&i.SignCount,
			&i.Transports,
			&i.Aaguid,
			&i.AttestationType,
			&i.BackupEligible,
			&i.BackupState,
			&i.UvInitialized,
			&i.Nickname,
			&i.LastUsedAt,
			&i.CloneWarningAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByAccountPage = `-- name: ListCredentialsByAccountPage :many
SELECT id, account_id, credential_id, public_key, cose_alg, user_handle, sign_count, transports, aaguid, attestation_type, backup_eligible, backup_state, uv_initialized, nickname, last_used_at, clone_warning_at, created_at FROM webauthn_credential
WHERE account_id = $1
  AND ($2::timestamptz IS NULL OR (created_at, id) < ($2, $3::integer))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListCredentialsByAccountPageParams struct {
	AccountID      int32              `json:"accountId"`
	AfterCreatedAt pgtype.Timestamptz `json:"afterCreatedAt"`
	AfterID        int32              `json:"afterId"`
	RowLimit       int32              `json:"rowLimit"`
}

// Keyset-paginated credentials for an account, ordered by (created_at DESC, id DESC).
// The after_created_at / after_id pair is the keyset cursor from the last row
// of the previous page; NULL starts a new page. LIMIT is limit+1 so the handler
// can detect the presence of a next page without a separate count.
func (q *Queries) ListCredentialsByAccountPage(ctx context.Context, arg ListCredentialsByAccountPageParams) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByAccountPage,
		arg.AccountID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CredentialID,
			&i.PublicKey,
			&i.CoseAlg,
			&i.UserHandle,
			&i.SignCount,
			&i.Transports,
			&i.Aaguid,
			&i.AttestationType,
			&i.BackupEligible,
			&i.BackupState,
			&i.UvInitialized,
			&i.Nickname,
			&i.LastUsedAt,
			&i.CloneWarningAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCredentialCloneWarning = `-- name: SetCredentialCloneWarning :exec
UPDATE webauthn_credential
SET clone_warning_at = now()
WHERE id = $1 AND clone_warning_at IS NULL
`

func (q *Queries) SetCredentialCloneWarning(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setCredentialCloneWarning, id)
	return err
}

const updateCredentialUsage = `-- name: UpdateCredentialUsage :exec
UPDATE webauthn_credential
SET sign_count = $3, last_used_at = now()
WHERE id = $1 AND account_id = $2
`

type UpdateCredentialUsageParams struct {
	ID        int32 `json:"id"`
	AccountID int32 `json:"accountId"`
	SignCount int64 `json:"signCount"`
}

func (q *Queries) UpdateCredentialUsage(ctx context.Context, arg UpdateCredentialUsageParams) error {
	_, err := q.db.Exec(ctx, updateCredentialUsage, arg.ID, arg.AccountID, arg.SignCount)
	return err
}

const updateMyCredentialNickname = `-- name: UpdateMyCredentialNickname :execrows
UPDATE webauthn_credential
SET nickname = $3
WHERE id = $1 AND account_id = $2
`

type UpdateMyCredentialNicknameParams struct {
	ID        int32       `json:"id"`
	AccountID int32       `json:"accountId"`
	Nickname  pgtype.Text `json:"nickname"`
}

// Owner-scoped update: only the account's own credential row is updated.
// Zero rows affected means the id doesn't match an owned credential; the
// handler then surfaces credential_not_found.
func (q *Queries) UpdateMyCredentialNickname(ctx context.Context, arg UpdateMyCredentialNicknameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMyCredentialNickname, arg.ID, arg.AccountID, arg.Nickname)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
