/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedIndexRouteImport } from './routes/_protected.index'
import { Route as PublicPreviewRouteImport } from './routes/_public._preview'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicLoginRecoveryRouteImport } from './routes/_public.login_.recovery'
import { Route as PublicLoginTotpRouteImport } from './routes/_public.login_.totp'
import { Route as PublicPreview_devFormsRouteImport } from './routes/_public._preview.[_]_dev.forms'
import { Route as PublicPreviewPreviewApiRouteImport } from './routes/_public._preview.preview.api'
import { Route as PublicPreviewPreviewComponentsRouteImport } from './routes/_public._preview.preview.components'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicPreviewRoute = PublicPreviewRouteImport.update({
  id: '/_preview',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRecoveryRoute = PublicLoginRecoveryRouteImport.update({
  id: '/login_/recovery',
  path: '/login/recovery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginTotpRoute = PublicLoginTotpRouteImport.update({
  id: '/login_/totp',
  path: '/login/totp',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPreview_devFormsRoute = PublicPreview_devFormsRouteImport.update({
  id: '/__dev/forms',
  path: '/__dev/forms',
  getParentRoute: () => PublicPreviewRoute,
} as any)
const PublicPreviewPreviewApiRoute = PublicPreviewPreviewApiRouteImport.update({
  id: '/preview/api',
  path: '/preview/api',
  getParentRoute: () => PublicPreviewRoute,
} as any)
const PublicPreviewPreviewComponentsRoute =
  PublicPreviewPreviewComponentsRouteImport.update({
    id: '/preview/components',
    path: '/preview/components',
    getParentRoute: () => PublicPreviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof PublicLoginRoute
  '/login/recovery': typeof PublicLoginRecoveryRoute
  '/login/totp': typeof PublicLoginTotpRoute
  '/__dev/forms': typeof PublicPreview_devFormsRoute
  '/preview/api': typeof PublicPreviewPreviewApiRoute
  '/preview/components': typeof PublicPreviewPreviewComponentsRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/login': typeof PublicLoginRoute
  '/login/recovery': typeof PublicLoginRecoveryRoute
  '/login/totp': typeof PublicLoginTotpRoute
  '/__dev/forms': typeof PublicPreview_devFormsRoute
  '/preview/api': typeof PublicPreviewPreviewApiRoute
  '/preview/components': typeof PublicPreviewPreviewComponentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/_preview': typeof PublicPreviewRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_public/login_/recovery': typeof PublicLoginRecoveryRoute
  '/_public/login_/totp': typeof PublicLoginTotpRoute
  '/_public/_preview/__dev/forms': typeof PublicPreview_devFormsRoute
  '/_public/_preview/preview/api': typeof PublicPreviewPreviewApiRoute
  '/_public/_preview/preview/components': typeof PublicPreviewPreviewComponentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login/recovery'
    | '/login/totp'
    | '/__dev/forms'
    | '/preview/api'
    | '/preview/components'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login/recovery'
    | '/login/totp'
    | '/__dev/forms'
    | '/preview/api'
    | '/preview/components'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/_preview'
    | '/_public/login'
    | '/_protected/'
    | '/_public/login_/recovery'
    | '/_public/login_/totp'
    | '/_public/_preview/__dev/forms'
    | '/_public/_preview/preview/api'
    | '/_public/_preview/preview/components'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/_preview': {
      id: '/_public/_preview'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicPreviewRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login_/recovery': {
      id: '/_public/login_/recovery'
      path: '/login/recovery'
      fullPath: '/login/recovery'
      preLoaderRoute: typeof PublicLoginRecoveryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login_/totp': {
      id: '/_public/login_/totp'
      path: '/login/totp'
      fullPath: '/login/totp'
      preLoaderRoute: typeof PublicLoginTotpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_preview/__dev/forms': {
      id: '/_public/_preview/__dev/forms'
      path: '/__dev/forms'
      fullPath: '/__dev/forms'
      preLoaderRoute: typeof PublicPreview_devFormsRouteImport
      parentRoute: typeof PublicPreviewRoute
    }
    '/_public/_preview/preview/api': {
      id: '/_public/_preview/preview/api'
      path: '/preview/api'
      fullPath: '/preview/api'
      preLoaderRoute: typeof PublicPreviewPreviewApiRouteImport
      parentRoute: typeof PublicPreviewRoute
    }
    '/_public/_preview/preview/components': {
      id: '/_public/_preview/preview/components'
      path: '/preview/components'
      fullPath: '/preview/components'
      preLoaderRoute: typeof PublicPreviewPreviewComponentsRouteImport
      parentRoute: typeof PublicPreviewRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicPreviewRouteChildren {
  PublicPreview_devFormsRoute: typeof PublicPreview_devFormsRoute
  PublicPreviewPreviewApiRoute: typeof PublicPreviewPreviewApiRoute
  PublicPreviewPreviewComponentsRoute: typeof PublicPreviewPreviewComponentsRoute
}

const PublicPreviewRouteChildren: PublicPreviewRouteChildren = {
  PublicPreview_devFormsRoute: PublicPreview_devFormsRoute,
  PublicPreviewPreviewApiRoute: PublicPreviewPreviewApiRoute,
  PublicPreviewPreviewComponentsRoute: PublicPreviewPreviewComponentsRoute,
}

const PublicPreviewRouteWithChildren = PublicPreviewRoute._addFileChildren(
  PublicPreviewRouteChildren,
)

interface PublicRouteChildren {
  PublicPreviewRoute: typeof PublicPreviewRouteWithChildren
  PublicLoginRoute: typeof PublicLoginRoute
  PublicLoginRecoveryRoute: typeof PublicLoginRecoveryRoute
  PublicLoginTotpRoute: typeof PublicLoginTotpRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPreviewRoute: PublicPreviewRouteWithChildren,
  PublicLoginRoute: PublicLoginRoute,
  PublicLoginRecoveryRoute: PublicLoginRecoveryRoute,
  PublicLoginTotpRoute: PublicLoginTotpRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
