import {
  Checkbox,
  CheckboxGroup,
  Label,
  Modal,
  Radio,
  RadioGroup,
} from "@heroui/react";
import { msg } from "@lingui/core/macro";
import { Trans, useLingui } from "@lingui/react/macro";
import { useMutation } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { isCancellation } from "@/api/errors";
import { createOidcAppMutationOptions } from "@/api/mutations";
import type { CreateOidcAppResponse } from "@/api/raw-admin-paths";
import { ConsoleCard } from "@/components/custom/ConsoleCard";
import { SecretReveal } from "@/components/custom/SecretReveal";
import { lineProblemMessage, parseLines } from "@/forms/lines";
import { applyServerError } from "@/forms/server-errors";
import { useAppForm } from "@/forms/use-app-form";
import { clientSecretCopy } from "@/pages/admin/oidc-applications/secret-copy";

/**
 * The Client ID rule the server enforces, tightened by the console.
 *
 * The server accepts any non-empty string; this refuses one that would not
 * survive the trip. The identifier becomes a path segment in the access and
 * manager endpoints, an `aud` claim, and part of a URL a client is configured
 * with, so a `?` or a space is a problem to discover later. Leading
 * alphanumeric keeps it out of the reach of a path traversal and of a client
 * that treats a leading dot as a hidden file.
 */
const clientIdPattern = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

const clientIdInvalid = msg({
  id: "admin.oidc-apps.new.client-id.invalid",
  message:
    "Use letters, digits, dots, underscores and hyphens, starting with a letter or a digit, up to 128 characters.",
});

const clientIdRequired = msg({
  id: "admin.oidc-apps.new.client-id.required",
  message: "Enter a Client ID.",
});

const nameRequired = msg({
  id: "admin.oidc-apps.new.name.required",
  message: "Enter a name.",
});

const redirectRequired = msg({
  id: "admin.oidc-apps.new.redirect.required",
  message: "Enter at least one redirect URI.",
});

const redirectInvalid = msg({
  id: "admin.oidc-apps.new.redirect.invalid",
  message: "Use an absolute http or https address.",
});

/**
 * Why one redirect URI is not usable.
 *
 * Checked here and not on the server: the endpoint takes the strings as given,
 * so a typo is accepted and then breaks a sign-in that is otherwise set up
 * correctly. The check is deliberately only "absolute http(s) with a host and no
 * credentials" — the server's discovery document and every mainstream library
 * expect an https origin, but a native client may legitimately loop back to
 * localhost over http, and a tighter check would refuse a working client.
 */
function redirectUriProblem(value: string) {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return redirectInvalid;
  }
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    return redirectInvalid;
  }
  if (url.host === "" || url.username !== "" || url.password !== "") {
    return redirectInvalid;
  }
  return undefined;
}

/** The scopes the server accepts, in the order the specification names them. */
const scopeOptions = ["openid", "profile", "email", "offline_access", "groups"];

/**
 * Registering an OIDC client with the instance.
 *
 * Only what the server cannot default is asked for. The launch URL, the
 * post-logout redirect URIs, the identity projection and the access policy all
 * have a working default — the record's own — and are set on the detail page,
 * where the application as it currently stands is beside the field.
 *
 * ## The secret
 *
 * A confidential client's secret is generated by the server and returned once.
 * It is therefore shown in a dialog before the reader leaves for the detail
 * page, and the navigation happens from the dialog rather than before it: going
 * to the detail page first and revealing on top of it would put the secret
 * behind a page load that a reload could lose. A public client has no secret, so
 * it goes straight through.
 */
export function AdminOidcApplicationNew() {
  const { t } = useLingui();
  const navigate = useNavigate();
  const create = useMutation(createOidcAppMutationOptions());

  const [isPublic, setIsPublic] = useState(false);
  // Held as the whole response: the dialog names the application as well as
  // showing the secret, and the secret exists only in this value.
  const [created, setCreated] = useState<CreateOidcAppResponse | null>(null);

  const form = useAppForm({
    defaultValues: {
      displayName: "",
      clientId: "",
      // One per line, because these are copied from a client's configuration as a
      // block and the order the client sent them in is worth keeping.
      redirectUris: "",
      scopes: ["openid", "profile", "email"] as string[],
      requireConsent: false,
      requirePkce: true,
      accessRestricted: false,
    },
    onSubmit: async ({ value }) => {
      const redirects = parseLines(value.redirectUris, redirectUriProblem);
      if (!redirects.ok) {
        form.setFieldMeta("redirectUris", (meta) => ({
          ...meta,
          errors: [lineProblemMessage(redirects.problem)],
        }));
        return;
      }
      if (redirects.values.length === 0) {
        form.setFieldMeta("redirectUris", (meta) => ({
          ...meta,
          errors: [redirectRequired],
        }));
        return;
      }

      try {
        const response = await create.mutateAsync({
          clientId: value.clientId.trim(),
          displayName: value.displayName.trim() || undefined,
          redirectUris: redirects.values,
          scopes: value.scopes,
          // The wire field is the inverse of the console's wording: the reader
          // chooses "confidential" or "public", and only the second sets this.
          public: isPublic,
          requireConsent: value.requireConsent,
          // A public client cannot turn PKCE off, so the switch is locked on
          // rather than merely defaulted; the server rejects `false` for one.
          requirePkce: isPublic ? true : value.requirePkce,
          accessRestricted: value.accessRestricted,
        });
        if (response.secret === undefined) {
          await navigate({
            to: "/admin/oidc-applications/$clientId",
            params: { clientId: response.clientId },
          });
          return;
        }
        setCreated(response);
      } catch (error) {
        if (isCancellation(error)) return;
        applyServerError(form, error, {
          codes: { oidc_client_already_exists: "clientId" },
          locations: {},
        });
      }
    },
  });

  return (
    <>
      <ConsoleCard>
        <form.AppForm>
          <form.Form
            label={t({
              id: "admin.oidc-apps.new.form",
              message: "New OIDC application",
            })}
          >
            <form.FormError />

            <form.AppField
              name="displayName"
              validators={{
                onSubmit: ({ value }) =>
                  value.trim() === "" ? nameRequired : undefined,
              }}
            >
              {(field) => (
                <field.FormField
                  label={<Trans id="admin.oidc-apps.field.name">Name</Trans>}
                  variant="secondary"
                />
              )}
            </form.AppField>

            <form.AppField
              name="clientId"
              validators={{
                onSubmit: ({ value }) => {
                  const clientId = value.trim();
                  if (clientId === "") return clientIdRequired;
                  return clientIdPattern.test(clientId)
                    ? undefined
                    : clientIdInvalid;
                },
              }}
            >
              {(field) => (
                <field.FormField
                  label={
                    <Trans id="admin.oidc-apps.field.client-id">
                      Client ID
                    </Trans>
                  }
                  description={
                    <Trans id="admin.oidc-apps.field.client-id.hint">
                      The client is configured with this value; it cannot
                      change.
                    </Trans>
                  }
                  autoComplete="off"
                  spellCheck={false}
                  variant="secondary"
                />
              )}
            </form.AppField>

            {/* The reader's choice, not the form's: the type is what the rest of
                this form reads, so it stays in component state with the value it
                decides (`isPublic`). */}
            <RadioGroup
              variant="secondary"
              value={isPublic ? "public" : "confidential"}
              onChange={(next) => setIsPublic(next === "public")}
            >
              <Label>
                <Trans id="admin.oidc-apps.field.kind">Client type</Trans>
              </Label>
              <Radio value="confidential">
                <Radio.Content>
                  <Radio.Control>
                    <Radio.Indicator />
                  </Radio.Control>
                  <Trans id="admin.oidc-apps.kind.confidential">
                    Confidential
                  </Trans>
                </Radio.Content>
              </Radio>
              <Radio value="public">
                <Radio.Content>
                  <Radio.Control>
                    <Radio.Indicator />
                  </Radio.Control>
                  <Trans id="admin.oidc-apps.kind.public">Public</Trans>
                </Radio.Content>
              </Radio>
            </RadioGroup>

            <form.AppField
              name="redirectUris"
              validators={{
                onSubmit: ({ value }) => {
                  const parsed = parseLines(value, redirectUriProblem);
                  if (!parsed.ok) {
                    return lineProblemMessage(parsed.problem);
                  }
                  return parsed.values.length === 0
                    ? redirectRequired
                    : undefined;
                },
              }}
            >
              {(field) => (
                <field.TextAreaField
                  label={
                    <Trans id="admin.oidc-apps.field.redirects">
                      Redirect URIs
                    </Trans>
                  }
                  description={
                    <Trans id="admin.oidc-apps.field.redirects.hint">
                      One per line. Absolute http or https addresses.
                    </Trans>
                  }
                  rows={3}
                  spellCheck={false}
                  variant="secondary"
                />
              )}
            </form.AppField>

            <form.Field name="scopes">
              {(field) => (
                <CheckboxGroup
                  variant="secondary"
                  value={field.state.value}
                  isDisabled={form.state.isSubmitting}
                  onChange={(next) => field.handleChange(next as string[])}
                >
                  <Label>
                    <Trans id="admin.oidc-apps.field.scopes">Scopes</Trans>
                  </Label>
                  {scopeOptions.map((scope) => (
                    <Checkbox key={scope} value={scope}>
                      <Checkbox.Content>
                        <Checkbox.Control>
                          <Checkbox.Indicator />
                        </Checkbox.Control>
                        <span className="font-mono text-sm">{scope}</span>
                      </Checkbox.Content>
                    </Checkbox>
                  ))}
                </CheckboxGroup>
              )}
            </form.Field>

            <form.AppField name="requirePkce">
              {(field) => (
                <field.SwitchField
                  label={
                    <Trans id="admin.oidc-apps.field.pkce">Require PKCE</Trans>
                  }
                  isDisabled={isPublic}
                  description={
                    isPublic ? (
                      <Trans id="admin.oidc-apps.field.pkce.public">
                        A public client always proves the request it started.
                      </Trans>
                    ) : undefined
                  }
                />
              )}
            </form.AppField>

            <form.AppField name="requireConsent">
              {(field) => (
                <field.SwitchField
                  label={
                    <Trans id="admin.oidc-apps.field.consent">
                      Require consent
                    </Trans>
                  }
                  description={
                    <Trans id="admin.oidc-apps.field.consent.hint">
                      Ask the account to approve the scopes before signing them
                      in.
                    </Trans>
                  }
                />
              )}
            </form.AppField>

            <form.AppField name="accessRestricted">
              {(field) => (
                <field.SwitchField
                  label={
                    <Trans id="admin.oidc-apps.field.restricted">
                      Restrict access
                    </Trans>
                  }
                  description={
                    <Trans id="admin.oidc-apps.field.restricted.hint">
                      Nobody can use the application until you select a user
                      group.
                    </Trans>
                  }
                />
              )}
            </form.AppField>

            <form.SubmitButton>
              <Trans id="admin.oidc-apps.new.submit">Create application</Trans>
            </form.SubmitButton>
          </form.Form>
        </form.AppForm>
      </ConsoleCard>

      {created?.secret !== undefined && (
        // Open and non-dismissable while the secret is held here, so it cannot
        // outlive the value: the reveal's own continue control is the only way
        // out, and it navigates.
        <Modal isOpen onOpenChange={() => {}}>
          <Modal.Backdrop isDismissable={false} isKeyboardDismissDisabled>
            <Modal.Container placement="center" size="lg" scroll="inside">
              <Modal.Dialog>
                <Modal.Header>
                  <Modal.Heading>{t(clientSecretCopy.title)}</Modal.Heading>
                </Modal.Header>
                <SecretReveal
                  text={created.secret}
                  filename={`${created.clientId}-client-secret.txt`}
                  copy={clientSecretCopy}
                  onContinue={async () => {
                    await navigate({
                      to: "/admin/oidc-applications/$clientId",
                      params: { clientId: created.clientId },
                    });
                  }}
                  inDialog
                />
              </Modal.Dialog>
            </Modal.Container>
          </Modal.Backdrop>
        </Modal>
      )}
    </>
  );
}
