import { Label, Modal, Radio, RadioGroup } from "@heroui/react";
import { msg } from "@lingui/core/macro";
import { Trans, useLingui } from "@lingui/react/macro";
import { useMutation } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { isCancellation } from "@/api/errors";
import { createOidcAppMutationOptions } from "@/api/mutations";
import type { CreateOidcAppResponse } from "@/api/raw-admin-paths";
import { ConsoleCard } from "@/components/custom/ConsoleCard";
import { SecretReveal } from "@/components/custom/SecretReveal";
import { applyServerError } from "@/forms/server-errors";
import { useAppForm } from "@/forms/use-app-form";
import { OidcScopesField } from "@/pages/admin/oidc-applications/OidcScopesField";
import {
  type OidcScope,
  uriListProblem,
} from "@/pages/admin/oidc-applications/oidc-validation";
import { clientSecretCopy } from "@/pages/admin/oidc-applications/secret-copy";
import {
  UriListField,
  uriRowProblem,
} from "@/pages/admin/oidc-applications/UriListField";

/**
 * The Client ID rule the server enforces, tightened by the console.
 *
 * The server accepts any non-empty string; this refuses one that would not
 * survive the trip. The identifier becomes a path segment in the access and
 * manager endpoints, an `aud` claim, and part of a URL a client is configured
 * with, so a `?` or a space is a problem to discover later. Leading
 * alphanumeric keeps it out of the reach of a path traversal and of a client
 * that treats a leading dot as a hidden file.
 */
const clientIdPattern = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

const clientIdInvalid = msg({
  id: "admin.oidc-apps.new.client-id.invalid",
  message:
    "Use letters, digits, dots, underscores and hyphens, starting with a letter or a digit, up to 128 characters.",
});

const clientIdRequired = msg({
  id: "admin.oidc-apps.new.client-id.required",
  message: "Enter a Client ID.",
});

const nameRequired = msg({
  id: "admin.oidc-apps.new.name.required",
  message: "Enter a name.",
});

/**
 * Registering an OIDC client with the instance.
 *
 * Only what the server cannot default is asked for. The launch URL, the
 * post-logout redirect URIs, the identity projection and the access policy all
 * have a working default — the record's own — and are set on the detail page,
 * where the application as it currently stands is beside the field.
 *
 * ## The secret
 *
 * A confidential client's secret is generated by the server and returned once.
 * It is therefore shown in a dialog before the reader leaves for the detail
 * page, and the navigation happens from the dialog rather than before it: going
 * to the detail page first and revealing on top of it would put the secret
 * behind a page load that a reload could lose. A public client has no secret, so
 * it goes straight through.
 */
export function AdminOidcApplicationNew() {
  const { t } = useLingui();
  const navigate = useNavigate();
  const create = useMutation(createOidcAppMutationOptions());

  const [isPublic, setIsPublic] = useState(false);
  // Held as the whole response: the dialog names the application as well as
  // showing the secret, and the secret exists only in this value.
  const [created, setCreated] = useState<CreateOidcAppResponse | null>(null);

  const form = useAppForm({
    defaultValues: {
      displayName: "",
      clientId: "",
      // One row to fill: a client signs in through at least one of these, so
      // the last row cannot be removed.
      redirectUris: [""],
      scopes: ["openid", "profile", "email"] as OidcScope[],
      requireConsent: false,
      requirePkce: true,
      accessRestricted: false,
    },
    onSubmit: async ({ value }) => {
      const problem = uriListProblem(value.redirectUris);
      if (problem !== undefined) {
        form.setFieldMeta("redirectUris", (meta) => ({
          ...meta,
          errorMap: { ...meta.errorMap, onSubmit: [uriRowProblem(problem)] },
        }));
        return;
      }

      try {
        const response = await create.mutateAsync({
          clientId: value.clientId.trim(),
          displayName: value.displayName.trim() || undefined,
          redirectUris: value.redirectUris,
          scopes: value.scopes,
          // The wire field is the inverse of the console's wording: the reader
          // chooses "confidential" or "public", and only the second sets this.
          public: isPublic,
          requireConsent: value.requireConsent,
          // A public client cannot turn PKCE off, so the switch is locked on
          // rather than merely defaulted; the server rejects `false` for one.
          requirePkce: isPublic ? true : value.requirePkce,
          accessRestricted: value.accessRestricted,
        });
        if (response.secret === undefined) {
          await navigate({
            to: "/admin/oidc-applications/$clientId",
            params: { clientId: response.clientId },
          });
          return;
        }
        setCreated(response);
      } catch (error) {
        if (isCancellation(error)) return;
        applyServerError(form, error, {
          codes: { oidc_client_already_exists: "clientId" },
          locations: {},
        });
      }
    },
  });

  return (
    <>
      <ConsoleCard>
        <form.AppForm>
          <form.Form
            label={t({
              id: "admin.oidc-apps.new.form",
              message: "New OIDC application",
            })}
          >
            <form.FormError />

            <form.AppField
              name="displayName"
              validators={{
                onSubmit: ({ value }) =>
                  value.trim() === "" ? nameRequired : undefined,
              }}
            >
              {(field) => (
                <field.FormField
                  label={<Trans id="admin.oidc-apps.field.name">Name</Trans>}
                  variant="secondary"
                />
              )}
            </form.AppField>

            <form.AppField
              name="clientId"
              validators={{
                onSubmit: ({ value }) => {
                  const clientId = value.trim();
                  if (clientId === "") return clientIdRequired;
                  return clientIdPattern.test(clientId)
                    ? undefined
                    : clientIdInvalid;
                },
              }}
            >
              {(field) => (
                <field.FormField
                  label={
                    <Trans id="admin.oidc-apps.field.client-id">
                      Client ID
                    </Trans>
                  }
                  description={
                    <Trans id="admin.oidc-apps.field.client-id.hint">
                      The client is configured with this value; it cannot
                      change.
                    </Trans>
                  }
                  autoComplete="off"
                  spellCheck={false}
                  variant="secondary"
                />
              )}
            </form.AppField>

            {/* The reader's choice, not the form's: the type is what the rest of
                this form reads, so it stays in component state with the value it
                decides (`isPublic`). */}
            <RadioGroup
              variant="secondary"
              value={isPublic ? "public" : "confidential"}
              onChange={(next) => setIsPublic(next === "public")}
            >
              <Label>
                <Trans id="admin.oidc-apps.field.kind">Client type</Trans>
              </Label>
              <Radio value="confidential">
                <Radio.Content>
                  <Radio.Control>
                    <Radio.Indicator />
                  </Radio.Control>
                  <Trans id="admin.oidc-apps.kind.confidential">
                    Confidential
                  </Trans>
                </Radio.Content>
              </Radio>
              <Radio value="public">
                <Radio.Content>
                  <Radio.Control>
                    <Radio.Indicator />
                  </Radio.Control>
                  <Trans id="admin.oidc-apps.kind.public">Public</Trans>
                </Radio.Content>
              </Radio>
            </RadioGroup>

            <form.AppField name="redirectUris">
              {() => (
                <UriListField
                  label={t({
                    id: "admin.oidc-apps.field.redirects",
                    message: "Redirect URIs",
                  })}
                  addLabel={
                    <Trans id="admin.oidc-apps.uri.add">Add address</Trans>
                  }
                  placeholder="https://app.example.com/callback"
                  minRows={1}
                  minRowsReason={
                    <Trans id="admin.oidc-apps.field.redirect.required">
                      A client needs at least one redirect URI.
                    </Trans>
                  }
                />
              )}
            </form.AppField>

            <form.AppField name="scopes">
              {() => <OidcScopesField />}
            </form.AppField>

            <form.AppField name="requirePkce">
              {(field) => (
                <field.SwitchField
                  label={
                    <Trans id="admin.oidc-apps.field.pkce">Require PKCE</Trans>
                  }
                  isDisabled={isPublic}
                  description={
                    isPublic ? (
                      <Trans id="admin.oidc-apps.field.pkce.public">
                        A public client always proves the request it started.
                      </Trans>
                    ) : undefined
                  }
                />
              )}
            </form.AppField>

            <form.AppField name="requireConsent">
              {(field) => (
                <field.SwitchField
                  label={
                    <Trans id="admin.oidc-apps.field.consent">
                      Require consent
                    </Trans>
                  }
                  description={
                    <Trans id="admin.oidc-apps.field.consent.hint">
                      Ask the account to approve the scopes before signing them
                      in.
                    </Trans>
                  }
                />
              )}
            </form.AppField>

            <form.AppField name="accessRestricted">
              {(field) => (
                <field.SwitchField
                  label={
                    <Trans id="admin.oidc-apps.field.restricted">
                      Restrict access
                    </Trans>
                  }
                  description={
                    <Trans id="admin.oidc-apps.field.restricted.hint">
                      Nobody can use the application until you select a user
                      group.
                    </Trans>
                  }
                />
              )}
            </form.AppField>

            <form.SubmitButton>
              <Trans id="admin.oidc-apps.new.submit">Create application</Trans>
            </form.SubmitButton>
          </form.Form>
        </form.AppForm>
      </ConsoleCard>

      {created?.secret !== undefined && (
        // Open and non-dismissable while the secret is held here, so it cannot
        // outlive the value: the reveal's own continue control is the only way
        // out, and it navigates.
        <Modal isOpen onOpenChange={() => {}}>
          <Modal.Backdrop isDismissable={false} isKeyboardDismissDisabled>
            <Modal.Container placement="center" size="lg" scroll="inside">
              <Modal.Dialog>
                <Modal.Header>
                  <Modal.Heading>{t(clientSecretCopy.title)}</Modal.Heading>
                </Modal.Header>
                <SecretReveal
                  text={created.secret}
                  filename={`${created.clientId}-client-secret.txt`}
                  copy={clientSecretCopy}
                  onContinue={async () => {
                    await navigate({
                      to: "/admin/oidc-applications/$clientId",
                      params: { clientId: created.clientId },
                    });
                  }}
                  inDialog
                />
              </Modal.Dialog>
            </Modal.Container>
          </Modal.Backdrop>
        </Modal>
      )}
    </>
  );
}
